### ISSUE TITLE
Runtime fail for iOS

### ISSUE THREAD

**Issue by jeffsenn** [kivy/kivy-ios#111]
Xcode 6.1.1 - changed build to "Universal" - running on connected iPhone 5 with iOS 8.1.2
Deploy Target 8.1 (though others fail as well

Both in stable (1.8.0)  and master (1.9.0-dev)

And when attempting to run a simple Kivy "pong" demo... the app fails
almost immediately (during import 'from ivy.app import App')

Output from debug console:
---------------------------------------------------------
2014-12-19 11:23:59.209 pong0[792:422231] PythonHome is: /private/var/mobile/Containers/Bundle/Application/DE7678C1-EB43-4925-A9DA-148DDDCBFF68/pong0.app
2014-12-19 11:23:59.217 pong0[792:422231] Initializing python
2014-12-19 11:23:59.439 pong0[792:422231] Running main.pyo: /private/var/mobile/Containers/Bundle/Application/DE7678C1-EB43-4925-A9DA-148DDDCBFF68/pong0.app/YourApp/main.pyo
[INFO              ] Kivy v1.8.0
 Traceback (most recent call last):
   File "/Users/senn/src/kivy-ios2/app-pong0/YourApp/main.py", line 1, in <module>
   File "/usr/local/lib/python2.7/site-packages/kivy/app.py", line 321, in <module>
   File "/usr/local/lib/python2.7/site-packages/kivy/base.py", line 29, in <module>
   File "/usr/local/lib/python2.7/site-packages/kivy/event.py", line 8, in <module>
   File "<string>", line 29, in load_module
   File "<string>", line 29, in load_module
   File "<string>", line 29, in load_module
   File "<string>", line 29, in load_module
   File "<string>", line 29, in load_module
   File "<string>", line 29, in load_module
   File "<string>", line 29, in load_module
...
   File "<string>", line 29, in load_module
   File "<string>", line 29, in load_module
   File "kivy/_event.pxd", line 1, in init kivy.properties (kivy/properties.c:24779)
   File "<string>", line 29, in load_module
   File "kivy/properties.pxd", line 3, in init kivy._event (kivy/_event.c:6585)
   File "<string>", line 19, in find_module
   File "/Users/senn/src/kivy-ios2/build/python/lib/python2.7/posixpath.py", line 68, in join
 RuntimeError: maximum recursion depth exceeded in cmp
2014-12-19 11:23:59.957 pong0[792:422231] Application quit abnormally!
2014-12-19 11:23:59.974 pong0[792:422231] Leaving

**Comment by tito** [comment]
This was an issue with cython rewriting, and has been fixed in the new toolchain as well.
