### ISSUE TITLE
Gif Images

### ISSUE THREAD

**Issue by meska** [kivy/kivy-ios#126]
Hello, 
I have a trouble with gif images  used by AsyncImageLoader,

```
[...]
[INFO              ] [Loader      ] using a thread pool of 2 workers
 Traceback (most recent call last):
   File "/Users/Meska/kivy-ios/mes-ios/YourApp/main.py", line 39, in <module>
   File "/private/var/mobile/Containers/Bundle/Application/C5E873F5-383F-4441-97D1-058D16F6B168/mes.app/lib/python2.7/site-packages/kivy/core/image/__init__.py", line 511, in __init__
     self.filename = arg
   File "/private/var/mobile/Containers/Bundle/Application/C5E873F5-383F-4441-97D1-058D16F6B168/mes.app/lib/python2.7/site-packages/kivy/core/image/__init__.py", line 699, in _set_filename
     mipmap=self._mipmap, nocache=self._nocache)
   File "/private/var/mobile/Containers/Bundle/Application/C5E873F5-383F-4441-97D1-058D16F6B168/mes.app/lib/python2.7/site-packages/kivy/core/image/__init__.py", line 432, in load
     raise Exception('Unknown <%s> type, no loader found.' % ext)
 Exception: Unknown <gif> type, no loader found.
2015-03-17 09:46:56.626 mes[3683:1458633] Application quit abnormally!
2015-03-17 09:46:56.702 mes[3683:1458633] Leaving
```

**Comment by tito** [comment]
In the main.m, you have something like KIVY_IMAGE putenv/setenv. In the string, try to add ",gif", restart, and tell me if it works

**Comment by meska** [comment]
it works perfectly, thank you
