### ISSUE TITLE
toolchain build error: Could not find platform dependent libraries <exec_prefix>

### ISSUE THREAD

**Issue by meska** [kivy/kivy-ios#127]
Hello,
I have this problem:
If I build plyer first after a "distclean" it builds correctly but "pymoodstocks" will  not build anymore.
If I start with building "pymoodstocks" then plyer will not build.
Error  `Could not find platform dependent libraries <exec_prefix>`  is the same in both occasions.

```
audiostream  - Build OK (built at 2015-03-26 17:41:38.801824)
ffmpeg       - Not built
ffpyplayer   - Not built
freetype     - Build OK (built at 2015-03-26 14:15:13.280294)
host_setuptools - Build OK (built at 2015-03-26 14:41:02.392469)
hostpython   - Build OK (built at 2015-03-26 14:20:36.228041)
ios          - Build OK (built at 2015-03-26 14:31:20.182668)
kivy         - Build OK (built at 2015-03-26 14:38:11.861156)
libffi       - Build OK (built at 2015-03-26 14:17:55.021044)
libjpeg      - Build OK (built at 2015-03-26 14:40:56.815511)
moodstocks   - Build OK (built at 2015-03-26 14:18:06.886778)
numpy        - Not built
pil          - Build OK (built at 2015-03-26 14:41:55.659573)
pkgresources - Build OK (built at 2015-03-26 14:41:02.643361)
plyer        - Not built
pymoodstocks - Build OK (built at 2015-03-26 14:38:13.859407)
pyobjus      - Build OK (built at 2015-03-26 14:32:13.453834)
python       - Build OK (built at 2015-03-26 14:31:10.302693)
sdl2         - Build OK (built at 2015-03-26 14:19:04.069808)
sdl2_image   - Build OK (built at 2015-03-26 14:22:31.390396)
sdl2_mixer   - Build OK (built at 2015-03-26 14:26:25.573881)
sdl2_ttf     - Build OK (built at 2015-03-26 14:27:10.579873)
MiniMac:kivy-ios Meska$ kivy toolchain.py build plyer
Want to build ['plyer']
Loaded recipe plyer (depends of ['python', 'pyobjus'])
Loaded recipe python (depends of ['hostpython', 'libffi'])
Loaded recipe pyobjus (depends of ['python'])
Loaded recipe hostpython (depends of ['libffi'])
Loaded recipe libffi (depends of [])
Build order is ['libffi', 'hostpython', 'python', 'pyobjus', 'plyer']
Global: hostpython located at /Users/Meska/kivy-ios/dist/hostpython/bin/python
Global: hostpgen located at /Users/Meska/kivy-ios/dist/hostpython/bin/pgen
# (ignored) Download libffi
# (ignored) Extract libffi
# (ignored) Build_all libffi
# (ignored) Download hostpython
# (ignored) Extract hostpython
# (ignored) Build_all hostpython
# (ignored) Download python
# (ignored) Extract python
# (ignored) Build_all python
# (ignored) Download pyobjus
# (ignored) Extract pyobjus
# (ignored) Build_all pyobjus
# (ignored) Download plyer
# (ignored) Extract plyer
Build_all plyer
Build plyer for i386 (filtered)
# (ignored) Build plyer
Install include files for plyer
# (ignored) Install_include plyer
Install frameworks for plyer
# (ignored) Install_frameworks plyer
Install sources for plyer
# (ignored) Install_sources plyer
Install plyer
Install plyer
Install plyer into the site-packages
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
/Users/Meska/kivy-ios/dist/hostpython/lib/python2.7/site-packages/setuptools-14.3.1-py2.7.egg/setuptools/dist.py:282: UserWarning: Normalizing '1.2.4-dev' to '1.2.4.dev0'
running install
Checking .pth file support in /Users/Meska/kivy-ios/build/plyer/i386/plyer-master/iosbuild/lib/python2.7/site-packages/
/Users/Meska/kivy-ios/dist/hostpython/bin/python -E -c pass
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
TEST FAILED: /Users/Meska/kivy-ios/build/plyer/i386/plyer-master/iosbuild/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Users/Meska/kivy-ios/build/plyer/i386/plyer-master/iosbuild/lib/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
Traceback (most recent call last):
  File "toolchain.py", line 1151, in <module>
    ToolchainCL()
  File "toolchain.py", line 1014, in __init__
    getattr(self, args.command)()
  File "toolchain.py", line 1028, in build
    build_recipes(args.recipe, ctx)
  File "toolchain.py", line 909, in build_recipes
    recipe.execute()
  File "/Users/Meska/kivy-ios/toolchain.py", line 552, in execute
    self.build_all()
  File "/Users/Meska/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/Meska/kivy-ios/toolchain.py", line 663, in build_all
    self.install()
  File "/Users/Meska/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/Meska/kivy-ios/toolchain.py", line 789, in install
    self.install_python_package()
  File "/Users/Meska/kivy-ios/toolchain.py", line 810, in install_python_package
    _env=env)
  File "/Users/Meska/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "tools/external/sh.py", line 565, in next
    self.wait()
  File "tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/Users/Meska/kivy-ios/dist/hostpython/bin/python setup.py install -O2 --prefix /Users/Meska/kivy-ios/build/plyer/i386/plyer-master/iosbuild'

  STDOUT:
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
/Users/Meska/kivy-ios/dist/hostpython/lib/python2.7/site-packages/setuptools-14.3.1-py2.7.egg/setuptools/dist.py:282: UserWarning: Normalizing '1.2.4-dev' to '1.2.4.dev0'
running install
Checking .pth file support in /Users/Meska/kivy-ios/build/plyer/i386/plyer-master/iosbuild/lib/python2.7/site-packages/
/Users/Meska/kivy-ios/dist/hostpython/bin/python -E -c pass
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
TEST FAILED: /Users/Meska/kivy-ios/build/plyer/i386/plyer-master/iosbuild/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install dir... (1071 more, please see e.stdout)

  STDERR:
```
##

**Comment by tito** [comment]
Maybe distclean miss few things, ok. I'll try to figure out what.

**Comment by Zen-CODE** [comment]
@meska. There have been a few changes that could have effected this. Please retry after pulling the latest from kivy-ios/master. Any change?

**Comment by Zen-CODE** [comment]
Multiple change and upgrade may have addressed this problem? Please retry with a recent checkout and re-raise if the problem persists.
