### ISSUE TITLE
toolchain.py build kivy fails

### ISSUE THREAD

**Issue by masnun** [kivy/kivy-ios#135]
I installed the prerequisites. Cloned the repo and then ran: 
```
./toolchain.py build kivy
```

And here's the error I get: 

```
Writing /Users/masnun/Projects/kivy-ios/build/ios/i386/src/iosbuild/lib/python2.7/site-packages/ios-1.0-py2.7.egg-info
Traceback (most recent call last):
  File "./toolchain.py", line 1160, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1023, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1037, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 918, in build_recipes
    recipe.execute()
  File "/Users/masnun/Projects/kivy-ios/toolchain.py", line 552, in execute
    self.build_all()
  File "/Users/masnun/Projects/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/masnun/Projects/kivy-ios/toolchain.py", line 663, in build_all
    self.install()
  File "/Users/masnun/Projects/kivy-ios/recipes/ios/__init__.py", line 12, in install
    self.install_python_package(name="ios.so", is_dir=False)
  File "/Users/masnun/Projects/kivy-ios/toolchain.py", line 820, in install_python_package
    self.remove_junk(ios_build)
NameError: global name 'ios_build' is not defined
```

**Comment by cbenhagen** [comment]
Hi,
this is fixed in https://github.com/kivy/kivy-ios/pull/134.

Just change the line 820 in /Users/masnun/Projects/kivy-ios/toolchain.py to:
```python
self.remove_junk(iosbuild)
```

**Comment by rnixx** [comment]
this issue should be closed
