### ISSUE TITLE
./toolchain.py build kivy big error

### ISSUE THREAD

**Issue by liubobo** [kivy/kivy-ios#153]
Traceback (most recent call last):
  File "./toolchain.py", line 1160, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1023, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1037, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 918, in build_recipes
    recipe.execute()
  File "/Users/liubo/Desktop/os/kivy-ios/toolchain.py", line 550, in execute
    self.download()
  File "/Users/liubo/Desktop/os/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/liubo/Desktop/os/kivy-ios/toolchain.py", line 579, in download
    self.ctx.state[key] = self.get_archive_rootdir(self.archive_fn)
  File "/Users/liubo/Desktop/os/kivy-ios/toolchain.py", line 416, in get_archive_rootdir
    archive = tarfile.open(filename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

**Comment by Zen-CODE** [comment]
This is a duplicate issue. Please see https://github.com/kivy/kivy-ios/issues/152
