### ISSUE TITLE
Toolchain not compatible with Xcode 7

### ISSUE THREAD

**Issue by othalan** [kivy/kivy-ios#162]
I am attempting to build kivy-ios and receiving a fatal error building python.

System:  OSX 10.10.5
Xcode: 7.0
```
clang -Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -L/Users/morrisde/contract/src/kivy-ios/dist/lib  -o python.exe \
			Modules/python.o \
			libpython2.7.a -ldl  -framework CoreFoundation -L/Users/morrisde/contract/src/kivy-ios/dist/hostpython/lib -lz
ld: warning: directory not found for option '-L/Users/morrisde/contract/src/kivy-ios/dist/hostpython/lib'
ld: in /Users/morrisde/contract/src/kivy-ios/dist/lib/libffi.a(ffi64_x86_64.o), building for OSX, but linking in object file built for iOS, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python.exe] Error 1
Traceback (most recent call last):
  File "./toolchain.py", line 1224, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1040, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1064, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 933, in build_recipes
    recipe.execute()
  File "/Users/morrisde/contract/src/kivy-ios/toolchain.py", line 556, in execute
    self.build_all()
  File "/Users/morrisde/contract/src/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/morrisde/contract/src/kivy-ios/toolchain.py", line 643, in build_all
    self.build(arch)
  File "/Users/morrisde/contract/src/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/morrisde/contract/src/kivy-ios/toolchain.py", line 630, in build
    self.build_arch(arch)
  File "/Users/morrisde/contract/src/kivy-ios/toolchain.py", line 678, in build_arch
    getattr(self, build)()
  File "/Users/morrisde/contract/src/kivy-ios/recipes/hostpython/__init__.py", line 68, in build_i386
    _env=build_env)
  File "/Users/morrisde/contract/src/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2:

  RAN: '/usr/bin/make -C /Users/morrisde/contract/src/kivy-ios/build/hostpython/i386/Python-2.7.1 -j4 python.exe Parser/pgen'

  STDOUT:
Makefile:1393: warning: overriding commands for target `Modules/posixmodule.o'
Makefile:1285: warning: ignoring old commands for target `Modules/posixmodule.o'
Makefile:1394: warning: overriding commands for target `Modules/posixmodule.so'
Makefile:1286: warning: ignoring old commands for target `Modules/posixmodule.so'
Makefile:1395: warning: overriding commands for target `Modules/errnomodule.o'
Makefile:1287: warning: ignoring old commands for target `Modules/errnomodule.o'
Makefile:1396: warning: overriding commands for target `Modules/errnomodule.so'
Makefile:1288: warning: ignoring old commands for target `Modules/errnomodule.so'
Makefile:1397: warning: overriding commands for target `Modules/pwdmodule.o'
Makefile:1289: warning: ignor... (77699 more, please see e.stdout)

  STDERR:

```

**Comment by othalan** [comment]
Note that I am using Python 2.7.10 installed via pyenv and configured via the command:
```
pyenv local 2.7.10
```

**Comment by othalan** [comment]
Running the link command manually with the -v option produces the following additional information:

```
>> clang -Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -L/Users/morrisde/contract/src/kivy-ios/dist/lib  -o python.exe Modules/python.o libpython2.7.a -ldl  -framework CoreFoundation -L/Users/morrisde/contract/src/kivy-ios/dist/hostpython/lib -lz -v

Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.10.0 -o python.exe -L/Users/morrisde/contract/src/kivy-ios/dist/lib -L/Users/morrisde/contract/src/kivy-ios/dist/hostpython/lib -lsqlite3 -lffi Modules/python.o libpython2.7.a -ldl -framework CoreFoundation -lz -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/lib/darwin/libclang_rt.osx.a
ld: warning: directory not found for option '-L/Users/morrisde/contract/src/kivy-ios/dist/hostpython/lib'
ld: in /Users/morrisde/contract/src/kivy-ios/dist/lib/libffi.a(ffi64_x86_64.o), building for OSX, but linking in object file built for iOS, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Examining the file it complains about:

```
>> ile libffi.a
libffi.a: Mach-O universal binary with 4 architectures
libffi.a (for architecture i386):	current ar archive random library
libffi.a (for architecture armv7):	current ar archive random library
libffi.a (for architecture x86_64):	current ar archive random library
libffi.a (for architecture arm64):	current ar archive random library
```

**Comment by tito** [comment]
Please post the full uncut log, the issue might be found with previous informations.

**Comment by LucaInfante** [comment]
Also for me same problem with Xcode 7 and OS X 10.11 GM

**Comment by SatoshiMiyazaki** [comment]
I encountered the same problem. This might have something to do with the change of linker rule in Xcode 7 ?  There is a report on the web. 

http://karp.id.au/post/xcode_7_linker_rules/

but I could not solve the problem.

**Comment by LTGIV** [comment]
Encountered problem with kivy-ios on host machine just upgraded to OSX 10.11 (https://twitter.com/ltgiv/status/649854171932299264) and decided to install a fresh copy of OSX 10.11 to see what would happen.  Different error message that's more in-line with what I found here on GitHub with this specific issue after searching on Google, and I've pasted the entire 3 megabyte log here:

https://gist.github.com/LTGIV/400efe772af16031c7dd#file-2015-10-02_kivy-ios_toolchain_build_fail_log-txt

**Comment by Ramalus** [comment]
I'm also running into this.

**Comment by satels** [comment]
+1

**Comment by satels** [comment]
After i past new target to libffi:
```diff
diff --git a/recipes/libffi/__init__.py b/recipes/libffi/__init__.py
index e486476..03c0731 100644
--- a/recipes/libffi/__init__.py
+++ b/recipes/libffi/__init__.py
@@ -28,6 +28,7 @@ class LibffiRecipe(Recipe):
                 "-sdk", arch.sdk,
                 "-project", "libffi.xcodeproj",
                 "-target", "libffi-iOS",
+                "-target", "libffi-Mac",
                 "-configuration", "Release")


```
then the error:
```bash
Check dependencies
CodeSign error: code signing is required for product type 'Dynamic Library' in SDK 'iOS 9.0'
```
continue solution is here
https://www.reddit.com/r/iOSProgramming/comments/39rcby/ios_9_os_x_1011_xcode_7_development_with_dynamic/

We just edit xcode project with 
```python
from mod_pbxproj import XcodeProject
...edit xcode project conf..
# mod_pbxproj documentation https://github.com/kronenthaler/mod-pbxproj
```

**Comment by tito** [comment]
I don't have my laptop in 10.11 / XCode 7 yet, so i can't really help right now. If anybody have a PR for that, please link here.

**Comment by LTGIV** [comment]
@tito: I'm going to try and spend some time on @satels suggestion today and see if I can make any progress.  Side note: do you have VMWare Fusion [8] by chance?  It's able to run 10.11 if you want to try this before upgrading the host machine (e.g. your laptop).

**Comment by tito** [comment]
I don't own VMWare Fusion, but that can be doable. I'll check for that.

**Comment by LTGIV** [comment]
@tito: when a donation is made, where does it go?  You?  Team?  The reason I ask, is I can kick some ducats in the bucket for you to buy VMWare Fusion 8.

As soon as these issues are resolved, I want to write up a more recent guide to throw on my pet project: https://www.opensour.cc/ as there's several projects that I want to use Kivy-iOS for and I haven't found a steps 1-x 'for dummies' guide, including for tying back to a home automation repository:

http://thad.getterman.org/post/130168270063/adding-zwave-nodes-to-aeotec-controller

Things are very clunky and horrible right now for how I use my iPhone to control systems in my house, and the WAF (Wife Acceptance Factor) is incredibly low, which means I'll probably have to shift everything over to "Smart Things" hub to raise the WAF until I can try and do some razzle-dazzle in Kivy.

**Comment by tito** [comment]
If the donation is made via the website, it goes to the organization, which we need to meet in order to "ack" a possible expense. You could give a direct donation, but it wont help, as i need time to check it which i don't have currently. That's why i can only help remotely, or when i'll hit the issue (after upgrading) :)

**Comment by satels** [comment]
After some changes (see diff): i run ./toolchain.py build hostpython:

https://github.com/kivy/kivy-ios/compare/master...satels:f/test-macosx

i have error

```bash
If you meant to cross compile, use `--host
```

**Comment by diegopelusa** [comment]
Hi!
I am running in similar problems as shown in this thread.
The main issue that I am finding is that libraries are tried to be built with objects/libs from another platform. Message like:
"building for OSX, but linking in object file built for iOS"
is the one shown in many cases.
Thanks! (I can spend 1-2 days helping if someone can advice me a little)

**Comment by tito** [comment]
Ok, Could you try few things? As the http://karp.id.au/post/xcode_7_linker_rules/ explained, it might be a mix between the `-miphoneos-version-min` flag.
My system show that:
    
    recipes/libffi/__init__.py
    19:                "s/-miphoneos-version-min=5.1.1/-miphoneos-version-min=6.0/g",

    toolchain.py
    177:    version_min = "-miphoneos-version-min=6.0.0"
    185:    version_min = "-miphoneos-version-min=7.0"
    193:    version_min = "-miphoneos-version-min=6.0.0"
    201:    version_min = "-miphoneos-version-min=7.0"

Could you try to change all the reference to `6.0.0` to `7.0` (in toolchain and libffi) ?

**Comment by diegopelusa** [comment]
I've tried it but the same error happens:
````
-Qunused-arguments -fcolor-diagnostics -lsqlite3 -lffi -L/Users/user/kivy-ios/dist/lib  -o python.exe \
			Modules/python.o \
			libpython2.7.a -ldl  -framework CoreFoundation -L/Users/user/kivy-ios/dist/hostpython/lib -    lz                      
ld: : directory not found for option '-L/Users/user/kivy-ios/dist/hostpython/lib'
ld: in /Users/user/kivy-ios/dist/lib/libffi.a(ffi64_x86_64.o), building for OSX, but linking in object file built for iOS, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python.exe] Error 1
Traceback (most recent call last):
  File "./toolchain.py", line 1224, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1040, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1064, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 933, in build_recipes
    recipe.execute()
  File "/Users/user/kivy-ios/toolchain.py", line 556, in execute
    self.build_all()
  File "/Users/user/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/user/kivy-ios/toolchain.py", line 643, in build_all
    self.build(arch)
  File "/Users/user/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/user/kivy-ios/toolchain.py", line 630, in build
    self.build_arch(arch)
  File "/Users/user/kivy-ios/toolchain.py", line 678, in build_arch
    getattr(self, build)()
  File "/Users/user/kivy-ios/recipes/hostpython/__init__.py", line 68, in build_i386
    _env=build_env)
  File "/Users/user/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/usr/bin/make -C /Users/user/kivy-ios/build/hostpython/i386/Python-2.7.1 -j4 python.exe Parser/pgen'
````
I had a look at the file `recipes/hostpython/__init__.py`, because that is the one being built, and I found the following: 
````
   def build_i386(self):
        sdk_path = sh.xcrun("--sdk", "macosx", "--show-sdk-path").strip()
````
Could it be that the `macosx` is wrong?

**Comment by jasoniem9246** [comment]
Got the same error +1

**Comment by yihuang** [comment]
I figure since i386 means iphonesimulator, why `hostpython` use macosx tools to build, so i changed hostpython's build scripts as follow:

```
--- recipes/hostpython/oldinit.py	2015-10-18 11:23:40.000000000 +0800
+++ recipes/hostpython/__init__.py	2015-10-18 11:40:16.000000000 +0800
@@ -46,11 +46,11 @@
             fd.writelines(lines)
 
     def build_i386(self):
-        sdk_path = sh.xcrun("--sdk", "macosx", "--show-sdk-path").strip()
+        sdk_path = sh.xcrun("--sdk", "iphonesimulator", "--show-sdk-path").strip()
         build_env = self.ctx.env.copy()
-        build_env["CC"] = "clang -Qunused-arguments -fcolor-diagnostics"
+        build_env["CC"] = "clang -Qunused-arguments -fcolor-diagnostics -miphoneos-version-min=7.0"
         build_env["LDFLAGS"] = " ".join([
-                "-lsqlite3",
+                "--sysroot={}".format(sdk_path),
                 "-lffi",
                 "-L{}".format(join(self.ctx.dist_dir, "lib"))
                 ])
@@ -63,6 +63,7 @@
                 "--prefix={}".format(join(self.ctx.dist_dir, "hostpython")),
                 "--disable-toolbox-glue",
                 "--without-gcc",
+                "--without-sqlite3",
                 _env=build_env)
         shprint(sh.make, "-C", self.build_dir, "-j4", "python.exe", "Parser/pgen",
                 _env=build_env)
```

It fixed the above problem, but got a new one:

```
clang -Qunused-arguments -fcolor-diagnostics -miphoneos-version-min=7.0 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -lffi -L/Users/yihuang/src/kivy-ios-master/dist/lib  -o python.exe \
			Modules/python.o \
			libpython2.7.a -ldl  -framework CoreFoundation -L/Users/yihuang/src/kivy-ios-master/dist/hostpython/lib -lz                      
ld: warning: directory not found for option '-L/Users/yihuang/src/kivy-ios-master/dist/hostpython/lib'
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
Undefined symbols for architecture x86_64:
  "_sqlite3_aggregate_context", referenced from:
      __pysqlite_final_callback in libpython2.7.a(connection.o)
      __pysqlite_step_callback in libpython2.7.a(connection.o)
  "_sqlite3_bind_blob", referenced from:
...
```

The option `--without-sqlite3` doesn't remove sqlite3 dependencies.

**Comment by yihuang** [comment]
```
-- recipes/hostpython/oldinit.py	2015-10-18 11:23:40.000000000 +0800
+++ recipes/hostpython/__init__.py	2015-10-18 11:48:37.000000000 +0800
@@ -46,10 +46,11 @@
             fd.writelines(lines)
 
     def build_i386(self):
-        sdk_path = sh.xcrun("--sdk", "macosx", "--show-sdk-path").strip()
+        sdk_path = sh.xcrun("--sdk", "iphonesimulator", "--show-sdk-path").strip()
         build_env = self.ctx.env.copy()
-        build_env["CC"] = "clang -Qunused-arguments -fcolor-diagnostics"
+        build_env["CC"] = "clang -Qunused-arguments -fcolor-diagnostics -miphoneos-version-min=7.0"
         build_env["LDFLAGS"] = " ".join([
+                "--sysroot={}".format(sdk_path),
                 "-lsqlite3",
                 "-lffi",
                 "-L{}".format(join(self.ctx.dist_dir, "lib"))
```

It turns out don't need to remove sqlite3 dependency, so above patch can make `./toolchain.py build host python` run successfully.

**Comment by yihuang** [comment]
Though I've managed to make hostpython build successfully, i still has problem to build kivy:

```
ranlib libpython2.7.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/yihuang/src/kivy-ios-master/dist/lib -lsqlite3 -miphoneos-version-min=7.0 -undefined dynamic_lookup  -o python.exe \
			Modules/python.o \
			libpython2.7.a -ldl  -framework CoreFoundation -L/python/lib -lz                     
ld: warning: directory not found for option '-L/python/lib'
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
make: *** [sharedmods] Error 1
Traceback (most recent call last):
  File "./toolchain.py", line 1224, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1040, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1064, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 933, in build_recipes
    recipe.execute()
  File "/Users/yihuang/src/kivy-ios-master/toolchain.py", line 556, in execute
    self.build_all()
  File "/Users/yihuang/src/kivy-ios-master/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/yihuang/src/kivy-ios-master/toolchain.py", line 643, in build_all
    self.build(arch)
  File "/Users/yihuang/src/kivy-ios-master/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/yihuang/src/kivy-ios-master/toolchain.py", line 630, in build
    self.build_arch(arch)
  File "/Users/yihuang/src/kivy-ios-master/recipes/python/__init__.py", line 62, in build_arch
    "HOSTPGEN={}".format(self.ctx.hostpgen))
  File "/Users/yihuang/src/kivy-ios-master/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/usr/bin/make -j4 CROSS_COMPILE_TARGET=yes HOSTPYTHON=/Users/yihuang/src/kivy-ios-master/dist/hostpython/bin/python HOSTPGEN=/Users/yihuang/src/kivy-ios-master/dist/hostpython/bin/pgen'

  STDOUT:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -fno-strict-aliasing -arch i386 -pipe -no-cpp-precomp --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -O3 -miphoneos-version-min=7.0 -I/Users/yihuang/src/kivy-ios-master/dist/include/i386/freetype -I/Users/yihuang/src/kivy-ios-master/dist/include/i386/libffi -I/Users/yihuang/src/kivy-ios-master/dist/include/common/sdl2 -I/Users/yihuang/src/kivy-ios-master/dist/include/common/sdl2_image -I/Users/yihuang/src/kivy-ios-master/dist/include/common/sdl2_mixer -I/Users/yihuang/src/kivy-ios-master/dist/include/common/sdl2_ttf -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I... (153961 more, please see e.stdout)

  STDERR:
```

**Comment by erccarls** [comment]
Anyone make progress on this yet?  Or a workaround?

**Comment by jadeblaquiere** [comment]
Workaround: download and install Xcode 6.4 in addition to Xcode 7... use Xcode 6.4 to compile kivy. There is a helpful article at : http://iosdevelopertips.com/xcode/install-multiple-versions-of-xcode.html

In the meantime it seems that Xcode v7 has become much more selective about linking. From what I can tell the build process compiles libffi for the simulator target and then links hostpython for osx against this library. Xcode 6 tolerates this but Xcode 7 cries foul. 

I tried creating a target for hostlibffi and compiling an OS X version of libffi and then using that to link hostpython and then compiling libffi for iOS. I got as far as building the python target but I'm getting other errors I haven't tracked down yet. My changes (not final) captured at: https://github.com/jadeblaquiere/kivy-ios

**Comment by Ramalus** [comment]
Are there any further news on this? And is there anything I can do to Help?

**Comment by jadeblaquiere** [comment]
I had some time to clean this up and test on Xcode 6.4 and 7.1. Changes submitted as pull request (#165) to this repo (or you can clone : https://github.com/jadeblaquiere/kivy-ios)

**Comment by brian-merz** [comment]
@jadeblaquiere Thank you.

I will be testing out your branch today.

BackStory: We have an app in the App Store that utilizes the kivy-compiled python environment. The implementation uses some of the mechanisms of kivy to allow us FFI from C/Obj-C to Python and vice versa. We have been successfully accepted and reviewed multiple times with our implementation. With the changes in XCode 7, the submission process now rejects our package after XCode uploads it. The message we receive (via E-mail from iTunes Connect) is as follows and occurs for every .so in the lib-dynload folder:

`
Missing load commands- The executable at "/Payload/OTTO DTS.app/lib/python2.7/lib-dynload/syslog.so" does not have the necessary load commands. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider.
`

I will update with my status later.

**Comment by D-Cipher** [comment]
I'm having the same issues with XCode 7. Where can you download Xcode 6.4? It's no longer in the App Store.

**Comment by jadeblaquiere** [comment]
older versions of Xcode are available from: https://developer.apple.com/downloads/

**Comment by D-Cipher** [comment]
Found it! Thanks jadeblaquiere. Keep us updated on how goes with xcode 7.

**Comment by D-Cipher** [comment]
I m getting a similar error with Xcode 6.4 as well. I tried PR from: https://github.com/kivy/kivy-ios/pull/165, but didn't seem to work for either Xcode 7 or 6.4. You guys have any ideas?

Here is the error:
ld: warning: directory not found for option '-F/Users/tingbochen/kivy-ios/dist/frameworks'
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame

**Comment by D-Cipher** [comment]
I figured it out. Thanks all for the help. 

I posted a guide to the build detailing some of the stumbling blocks I found here:
https://goo.gl/swR2L5

**Comment by tito** [comment]
Fix in #165 has been merged, it should fix this. Thanks a lot to @jadeblaquiere and everyone who contributed here!

**Comment by MatthewGieger** [comment]
I know i'm a little late on this, but I've been running into this issues when trying to test my app on my phone or iPad. (I don't get the error when using Xcode's built in simulator. Can anyone else confirm this? 
(I'm using Xcode 7.2 and trying to run build kivy's touchtracer)

**Comment by KarimJedda** [comment]
I confirm having the same issue @MatthewGieger

**Comment by exonent** [comment]
same issue @MatthewGieger

**Comment by dzmitrykrukouski** [comment]
same issue @MatthewGieger
