### ISSUE TITLE
Failed to build 'python' (configure: error: cannot compute sizeof (uintptr_t))

### ISSUE THREAD

**Issue by 4ntoine** [kivy/kivy-ios#173]
```
checking size of size_t... 0
checking size of pid_t... 0
checking for long long support... yes
checking size of long long... 0
checking for long double support... yes
checking size of long double... 0
checking for _Bool support... yes
checking size of _Bool... 0
checking for uintptr_t... yes
checking size of uintptr_t... configure: error: in `/Users/asmirnov/Documents/dev/src/kivy-ios3/build/python/i386/Python-2.7.1':
configure: error: cannot compute sizeof (uintptr_t)
See `config.log' for more details.
Traceback (most recent call last):
  File "./toolchain.py", line 1227, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1043, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1067, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 936, in build_recipes
    recipe.execute()
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 559, in execute
    self.build_all()
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 646, in build_all
    self.build(arch)
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 633, in build
    self.build_arch(arch)
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/recipes/python/__init__.py", line 53, in build_arch
    _env=build_env)
  File "/Users/asmirnov/Documents/dev/src/kivy-ios3/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_77: 

  RAN: '/Users/asmirnov/Documents/dev/src/kivy-ios3/build/python/i386/Python-2.7.1/configure CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld CFLAGS=-arch i386 -pipe -no-cpp-precomp --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -O3 -miphoneos-version-min=6.0.0 -I/Users/asmirnov/Documents/dev/src/kivy-ios3/dist/include/i386/hostlibffi -I/Users/asmirnov/Documents/dev/src/kivy-ios3/dist/include/i386/libffi LDFLAGS=-arch i386 --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -L/Users/asmirnov/Documents/dev/src/kivy-ios3/dist/lib -lsqlite3 -miphoneos-version-min=6.0.0 -undefined dynamic_lookup --without-pymalloc --disable-toolbox-glue --host=i386-apple-darwin --prefix=/python --with-system-ffi --without-doc-strings'

  STDOUT:
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
checking for --enable-universalsdk... no
checking for --with-universal-archs... 32-bit
checking MACHDEP... darwin
checking EXTRAPLATDIR... $(PLATMACDIRS)
checking machine type as reported by uname -m... x86_64
checking for --without-gcc... no
checking for i386-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files..... (13703 more, please see e.stdout)

  STDERR:

```

**Comment by 4ntoine** [comment]
seems to be the same issue for build python for iOS arm64: https://github.com/pybee/Python-iOS-support/issues/7

**Comment by 4ntoine** [comment]
i can confirm it CAN be builT with Xcode 6.4 and CAN'T be BUILT with Xcode 7.2 using this tutorial: https://github.com/D-Cipher/My-Courses/blob/master/Various%20Guides/Kivy%20IOS%20Build%20Guide%20for%20Xcode%206.4.md

**Comment by kived** [comment]
Can you try upgrading to Xcode 7.3? I'm running 7.3 and I don't experience this problem.

**Comment by akshayaurora** [comment]
Faced the same issue with Xcode 7.x and OS X sierra. This seems to happen when there is a OS X updated version and XCode has still not been updated.
