### ISSUE TITLE
Failed build openssl

### ISSUE THREAD

**Issue by dzmitrykrukouski** [kivy/kivy-ios#198]
Hi! 

I try to build openssl
`./toolchain.py build openssl`

And then i get error.

```
Want to build ['openssl']
Loaded recipe openssl (depends of [], optional are [])
Build order is ['openssl']
Include dir added: {arch.arch}/openssl
Download openssl
Downloading http://www.openssl.org/source/openssl-1.0.2f.tar.gz
Traceback (most recent call last):
  File "./toolchain.py", line 1310, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1081, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1105, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 974, in build_recipes
    recipe.execute()
  File "/Users/vm-mac/projects/kivy-ios/toolchain.py", line 584, in execute
    self.download()
  File "/Users/vm-mac/projects/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/vm-mac/projects/kivy-ios/toolchain.py", line 613, in download
    self.download_file(self.url.format(version=self.version), fn)
  File "/Users/vm-mac/projects/kivy-ios/toolchain.py", line 414, in download_file
    urlretrieve(url, filename, report_hook)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 641, in http_error_302
    data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 667, in redirect_internal
    return self.open(newurl)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:590)
```

**Python 2.7.10
Mac OS X 10.11.1**

`python -c 'import ssl; print(ssl.OPENSSL_VERSION)'`
**OpenSSL 0.9.8zg 14 July 2015**
##

**Comment by melnichevv** [comment]
Hm, very interesting

**Comment by mrhdias** [comment]
fast workaround for the problem:
```
cd kivy-ios-master
wget http://www.openssl.org/source/openssl-1.0.2f.tar.gz
mv openssl-1.0.2f.tar.gz .cache/openssl-openssl-1.0.2f.tar.gz
./toolchain.py build openssl
```

**Comment by dzmitrykrukouski** [comment]
@mrhdias thanks for response.
I know, that i can do it, but i think this is the bug :)
Because all other distributions are compiled well.

**Comment by kollivier** [comment]
It's not an issue with the recipe itself, it's an issue with the OpenSSL version that the system Python is compiled against on OS X. Unfortunately Python will either need to start bundling their own OpenSSL build, like they do for Windows, or somehow switch the ssl library to use native OS X APIs. :(

**Comment by Zen-CODE** [comment]
@kollivier. Thanks
Lets close this issue accordingly. It's not really a kivy issues and that is a very old version with known security vulnerabilities.

@dzmitrykrukouski. Please re-open if upgrading the installed openssl version does not fix it.
