### ISSUE TITLE
Build error: No such file or directory: Python\Python-ast.py

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/kivy-ios#201]
When doing a clean checkout and running "./toolchain.py build kivy', I get the following outout:

Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Users/camy/kivy/kivy-ios/kivy-ios/dist/hostlibffi/usr/local/include -DNDEBUG -g  -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE -o Objects/unicodectype.o Objects/unicodectype.c
./Parser/asdl_c.py -c ./Python ./Parser/Python.asdl
Traceback (most recent call last):
  File "./Parser/asdl_c.py", line 1220, in <module>
    main(args[0])
  File "./Parser/asdl_c.py", line 1182, in main
    f = open(p, "wb")
IOError: [Errno 2] No such file or directory: './Python/Python-ast.c'
make: *** [Python/Python-ast.c] Error 1
Traceback (most recent call last):
  File "./toolchain.py", line 1310, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1081, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1105, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 974, in build_recipes
    recipe.execute()
  File "/Users/camy/kivy/kivy-ios/kivy-ios/toolchain.py", line 586, in execute
    self.build_all()
  File "/Users/camy/kivy/kivy-ios/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/camy/kivy/kivy-ios/kivy-ios/toolchain.py", line 698, in build_all
    self.install()
  File "/Users/camy/kivy/kivy-ios/kivy-ios/recipes/hostpython/__init__.py", line 81, in install
    _env=build_env)
  File "/Users/camy/kivy/kivy-ios/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/usr/bin/make -C /Users/camy/kivy/kivy-ios/kivy-ios/build/hostpython/x86_64/Python-2.7.1 bininstall inclinstall'

  STDOUT:
Makefile:1392: warning: overriding commands for target `Modules/posixmodule.o'
Makefile:1284: warning: ignoring old commands for target `Modules/posixmodule.o'
Makefile:1393: warning: overriding commands for target `Modules/posixmodule.so'
Makefile:1285: warning: ignoring old commands for target `Modules/posixmodule.so'
Makefile:1394: warning: overriding commands for target `Modules/errnomodule.o'
Makefile:1286: warning: ignoring old commands for target `Modules/errnomodule.o'
Makefile:1395: warning: overriding commands for target `Modules/errnomodule.so'
Makefile:1287: warning: ignoring old commands for target `Modules/errnomodule.so'
Makefile:1396: warning: overriding commands for target `Modules/pwdmodule.o'
Makefile:1288: warning: ignor... (18917 more, please see e.stdout)

  STDERR:

**Comment by lilouch** [comment]
Same issue for me !

**Comment by orling** [comment]
Zen-CODE's awesome patch fixes the issue! https://github.com/kivy/kivy-ios/commit/24b3ded9164b89855a207ba78b8299a61a41ed49
