### ISSUE TITLE
Using Cython with Kivy-iOS

### ISSUE THREAD

**Issue by mbrockman1** [kivy/kivy-ios#241]
I am trying to use Cython in my Kivy-iOS app. My current method is using pyximport.install('clock.pyx'). This works fine on my local machine however, I get the error below when I try to run the same code on my iPhone simulator.

`2017-02-15 11:44:47.399 timing[6789:4913845] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2017-02-15 11:44:47.399 timing[6789:4913845] PythonHome is: /Users/michael/Library/Developer/CoreSimulator/Devices/860ADC0E-43FD-4602-8C24-671E29FB8CC7/data/Containers/Bundle/Application/8CC52FB8-423D-40D4-9E24-0B82801FA469/timing.app
2017-02-15 11:44:47.402 timing[6789:4913845] Initializing python
2017-02-15 11:44:47.447 timing[6789:4913845] Running main.pyo: /Users/michael/Library/Developer/CoreSimulator/Devices/860ADC0E-43FD-4602-8C24-671E29FB8CC7/data/Containers/Bundle/Application/8CC52FB8-423D-40D4-9E24-0B82801FA469/timing.app/YourApp/main.pyo
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.1 (r271:86832, Feb 14 2017, 14:03:25)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
[INFO              ] [Factory     ] 179 symbols loaded
failed to import Cython: dynamic module does not define init function (initScanning)
 Traceback (most recent call last):
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/main.py", line 1, in <module>
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/smile/common.py", line 14, in <module>
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/smile/experiment.py", line 26, in <module>
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/smile/state.py", line 23, in <module>
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/_applibs/pyximport/pyximport.py", line 435, in load_module
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/_applibs/pyximport/pyximport.py", line 227, in load_module
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/_applibs/pyximport/pyximport.py", line 209, in load_module
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/_applibs/pyximport/pyximport.py", line 186, in build_module
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/_applibs/pyximport/pyxbuild.py", line 100, in pyx_to_dll
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/dist/root/python/lib/python2.7/distutils/dist.py", line 953, in run_commands
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/dist/root/python/lib/python2.7/distutils/dist.py", line 972, in run_command
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/_applibs/Cython/Distutils/build_ext.py", line 164, in run
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/dist/root/python/lib/python2.7/distutils/command/build_ext.py", line 340, in run
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/_applibs/Cython/Distutils/build_ext.py", line 171, in build_extensions
   File "/Users/michael/virtualenv/kivy-ios/timing/.buildozer/ios/platform/kivy-ios/timing-ios/YourApp/_applibs/Cython/Distutils/build_ext.py", line 190, in cython_sources
 ImportError: Building module smile.clock failed: ['DistutilsPlatformError: Cython does not appear to be installed\n']
2017-02-15 11:44:47.696 timing[6789:4913845] Application quit abnormally!
2017-02-15 11:44:47.706 timing[6789:4913845] Leaving`

I have looked at other sites that have had luck with using Cython in their iOS apps such as, http://shadowmint.blogspot.com/2013/10/kivy-cython-extensions-and-ios.html?view=timeslide, however his kivy-ios fork is 4+ years old and no longer works. Has anyone had success with using Cython and Kivy-iOS. I would love to know the methodology behind it.

**Comment by Zen-CODE** [comment]
This is not an area I have much expertise/knowledge in, but I saw this:

   def cythonize_file(self, filename):
       if filename.startswith(self.build_dir):
           filename = filename[len(self.build_dir) + 1:]
       print("Cython {}".format(filename))
       cmd = sh.Command("/usr/local/bin/cython")
       shprint(cmd, filename)

from this pr: https://github.com/kivy/kivy-ios/pull/242/files

If that does not help, I would look at how the native kivy cython parts are compiled (e.g. the files in kivy.graphics). Launch "./toolchain.py build kivy" with a debugger and step through it until you get to the relevant parts.. It is definitely compiling these part successfully, it's just a matter of finding out how.

If you do find out, please post here and I'd be happy to document that for others...:-)

**Comment by hottwaj** [comment]
Hey @mbrockman1 I think you need to do this a bit differently...  

Your current approach (using "pyximport") would normally involve compiling your cython file whilst your kivy app is already running.  This will be difficult/impossible to get to work on iOS & android because none of the compiling tools you need (gcc, system headers, python headers etc) are going to be installed on the mobile device.  Cython will also not be installed on the mobile device.

Instead you need to do something like this.

1. Put your cython files into a separate python package that can be installed with e.g. pip.  You can find examples of basic setup.py files for packages with cython components here: http://cython.readthedocs.io/en/latest/src/reference/compilation.html  Check out e.g. the kivy audiostream package for a slightly more involved example.

2. Once you've installed your package, test it out on your local machine.  Instead of running "pyximport.install('clock.pyx')" in your code you will just "import mypackage.clock" because your .pyx file has already been compiled by the package installation process

3. Once you're happy with the package, write a "recipe" for kivy-ios that will build your package.  Have a look at existing recipes that do this e.g. audiostream pyjnius and strip them down to the basics that you need. Recipe docs are here: https://python-for-android.readthedocs.io/en/latest/recipes/

4. Compile your package for ios using kivy-ios, then test etc

Finally, I seem to remember that there might be an issue with identically named cython packages across a kivy android/iOS distribution, and I think "clock.pyx" is already used within the Kivy library - so you might want to use a different filename just in case.

Hope that helps!

**Comment by tito** [comment]
Closing this issue. Yes, pyximport require you to have a local cython + compiler available on the target. So it's likely not something you can have on iOS. Just follow the instructions from @hottwaj :)
