### ISSUE TITLE
Error when building kivy

### ISSUE THREAD

**Issue by Mr-Binary** [kivy/kivy-ios#252]
The command is `./toolchain.py build kivy`

The output is:
```bash
Reduce python
Remove files unlikely to be used
Create a python27.zip
Download ios
Extract ios
Extract ios for i386
Extract ios for x86_64
Extract ios for armv7
Extract ios for arm64
Build_all ios
Build ios for i386, x86_64, armv7, arm64 (filtered)
Build ios
Prebuild ios for i386
Build ios for i386
Cythonize ios.pyx
('-- cythonize', ['/Users/albertgao/codes/python/ios_kivy/kivy-ios/tools/cythonize.py', 'ios.pyx'])
('cythonize:', 'ios.pyx')
Traceback (most recent call last):
  File "/Users/albertgao/.pyenv/versions/2.7.12/bin/cython", line 7, in <module>
    from Cython.Compiler.Main import setuptools_main
  File "/Users/albertgao/.pyenv/versions/2.7.12/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 28, in <module>
    from .Scanning import PyrexScanner, FileSourceDescriptor
ImportError: dlopen(/Users/albertgao/.pyenv/versions/2.7.12/lib/python2.7/site-packages/Cython/Compiler/Scanning.so, 2): Symbol not found: _PyUnicodeUCS2_Compare
  Referenced from: /Users/albertgao/.pyenv/versions/2.7.12/lib/python2.7/site-packages/Cython/Compiler/Scanning.so
  Expected in: flat namespace
 in /Users/albertgao/.pyenv/versions/2.7.12/lib/python2.7/site-packages/Cython/Compiler/Scanning.so
('no need to rewrite', 'ios.pyx')
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
running build_ext
building 'ios' extension
creating build
creating build/temp.macosx-10.12-x86_64-2.7
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -arch i386 -pipe -no-cpp-precomp --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -O3 -miphoneos-version-min=6.0.0 -I/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/include/i386/freetype -I/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/include/i386/hostlibffi -I/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/include/i386/libffi -I/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/include/common/sdl2 -I/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/include/common/sdl2_image -I/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/include/common/sdl2_mixer -I/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/include/common/sdl2_ttf -g -I/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/hostpython/include/python2.7 -c ios.c -o build/temp.macosx-10.12-x86_64-2.7/ios.o
clang: error: no such file or directory: 'ios.c'
clang: error: no input files
error: command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang' failed with exit status 1
Traceback (most recent call last):
  File "./toolchain.py", line 1318, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1088, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1112, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 980, in build_recipes
    recipe.execute()
  File "/Users/albertgao/codes/python/ios_kivy/kivy-ios/toolchain.py", line 590, in execute
    self.build_all()
  File "/Users/albertgao/codes/python/ios_kivy/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/albertgao/codes/python/ios_kivy/kivy-ios/toolchain.py", line 679, in build_all
    self.build(arch)
  File "/Users/albertgao/codes/python/ios_kivy/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/albertgao/codes/python/ios_kivy/kivy-ios/toolchain.py", line 666, in build
    self.build_arch(arch)
  File "/Users/albertgao/codes/python/ios_kivy/kivy-ios/toolchain.py", line 938, in build_arch
    _env=build_env)
  File "/Users/albertgao/codes/python/ios_kivy/kivy-ios/toolchain.py", line 39, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/hostpython/bin/python setup.py build_ext -g'

  STDOUT:
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
running build_ext
building 'ios' extension
creating build
creating build/temp.macosx-10.12-x86_64-2.7
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -arch i386 -pipe -no-cpp-precomp --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -O3 -miphoneos-version-min=6.0.0 -I/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/include/i386/freetype -I/Users/albertgao/codes/python/ios_kivy/kivy-ios/dist/include/i386/hostlibffi -I/Users/albertgao/codes/python/ios_kivy/kivy-ios... (696 more, please see e.stdout)

  STDERR:

albert:kivy-ios albertgao$
```

How to fix this please? I use python 2.7.12

I tried modify the first line of `toolchain.py` to `#!/Users/albertgao/.pyenv/versions/2.7.2/bin/python2.7`. Doesn't work. I use `pyenv` to manage my python versions.

**Comment by Mr-Binary** [comment]
Re-open the shell, and it works now...
For someone who use `pyenv`: Modify the first line of `toolchain.py` to point to the real location, then re-open the shell. Should work.
