### ISSUE TITLE
Kivy-ios build failed

### ISSUE THREAD

**Issue by adibub** [kivy/kivy-ios#283]
macOS High Sierra 10.13.4
python 2.7.10
clang Apple LLVM version 9.1.0 
xcode 9.3
cython 0.27.3

Downloading https://www.mirrorservice.org/sites/sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
Traceback (most recent call last):
  File "./toolchain.py", line 1365, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1114, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1155, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 1005, in build_recipes
    recipe.execute()
  File "/Users/mac/kivy-ios/toolchain.py", line 613, in execute
    self.download()
  File "/Users/mac/kivy-ios/toolchain.py", line 56, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/mac/kivy-ios/toolchain.py", line 642, in download
    self.download_file(self.url.format(version=self.version), fn)
  File "/Users/mac/kivy-ios/toolchain.py", line 434, in download_file
    urlretrieve(url, filename, report_hook)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)

socket error? Never got this one before?

**Comment by adibub** [comment]
Changing the first line in toolchain.py to usr/bin/python fixed this!
