### ISSUE TITLE
Fix error - sh.CommandNotFound: python2

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy-ios#309]
Please fix!

Run command:

```pyhton
./toolchain.py build python3 openssl kivy
```
Gettind an error:

```pyhton
...

Build_all libffi
Build libffi for x86_64, armv7, arm64 (filtered)
Build libffi
Prebuild libffi for x86_64
Apply patch fix-win32-unreferenced-symbol.patch
Build libffi for x86_64
Traceback (most recent call last):
  File "./toolchain.py", line 1475, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1218, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1259, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 1097, in build_recipes
    recipe.execute()
  File "/Users/macbookair/Opt/kivy-ios/toolchain.py", line 694, in execute
    self.build_all()
  File "/Users/macbookair/Opt/kivy-ios/toolchain.py", line 63, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/macbookair/Opt/kivy-ios/toolchain.py", line 789, in build_all
    self.build(arch)
  File "/Users/macbookair/Opt/kivy-ios/toolchain.py", line 63, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/macbookair/Opt/kivy-ios/toolchain.py", line 776, in build
    self.build_arch(arch)
  File "/Users/macbookair/Opt/kivy-ios/recipes/libffi/__init__.py", line 34, in build_arch
    shprint(sh.python2, "_generate-darwin-source-and-headers.py", "--only-ios")
  File "./tools/external/sh.py", line 2301, in __getattr__
    return self.__env[name]
  File "./tools/external/sh.py", line 2232, in __getitem__
    return Command._create(k, **self.baked_args)
  File "./tools/external/sh.py", line 776, in _create
    raise CommandNotFound(program)
sh.CommandNotFound: python2
```

Same error with another command - `./toolchain.py build python2 openssl kivy`
I installed Python 2.7 and Python 3.7

**Comment by injan33r** [comment]
I received the same error running:
`./toolchain.py build kivy`

The workaround for me was to specially install python2 via Homebrew
`brew install python2`

Note: I'm using anaconda for most of my python packages. I did install the Homebrew packages that were specifically mentioned in the instructions via Homebrew.
