### ISSUE TITLE
name 'ulng' is not defined

### ISSUE THREAD

**Issue by jefcolbi** [kivy/kivy-ios#313]
Hi after compiling a project for IOS i got this error

```
018-11-16 14:20:51.981930-0500 taskcheck[95444:1504020] [framework] CUIThemeStore: No theme registered with id=0
2018-11-16 14:20:52.718503-0500 taskcheck[95444:1504020] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2018-11-16 14:20:52.719814-0500 taskcheck[95444:1504020] Initializing python
/Users/Eckhardt/Library/Developer/CoreSimulator/Devices/B912277E-4A57-4E17-844C-49A34376E056/data/Containers/Bundle/Application/5F21AACA-F1AA-4C6B-9D4C-9D0317E16DA4/taskcheck.app/taskcheck:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
2018-11-16 14:20:54.055918-0500 taskcheck[95444:1504020] Running main.py: /Users/Eckhardt/Library/Developer/CoreSimulator/Devices/B912277E-4A57-4E17-844C-49A34376E056/data/Containers/Bundle/Application/5F21AACA-F1AA-4C6B-9D4C-9D0317E16DA4/taskcheck.app/YourApp/main.pyc
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (default, Nov 16 2018, 06:27:35) 
[Clang 10.0.0 (clang-1000.11.45.5)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 APPLE-17.0.37'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple Software Renderer'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/Users/Eckhardt/Project/kivy-ios/taskcheck-ios/YourApp/main.py", line 99, in <module>
   File "/Users/Eckhardt/Library/Developer/CoreSimulator/Devices/B912277E-4A57-4E17-844C-49A34376E056/data/Containers/Bundle/Application/5F21AACA-F1AA-4C6B-9D4C-9D0317E16DA4/taskcheck.app/lib/python3.7/site-packages/kivy/app.py", line 800, in run
     root = self.build()
   File "/Users/Eckhardt/Project/kivy-ios/taskcheck-ios/YourApp/main.py", line 94, in build
   File "/Users/Eckhardt/Project/kivy-ios/taskcheck-ios/YourApp/main.py", line 32, in __init__
   File "/Users/Eckhardt/Project/kivy-ios/taskcheck-ios/YourApp/main.py", line 56, in open_default
   File "kivy/_event.pyx", line 188, in kivy._event.EventDispatcher.__cinit__
   File "kivy/properties.pyx", line 438, in kivy.properties.Property.link
   File "kivy/properties.pyx", line 612, in kivy.properties.NumericProperty.init_storage
   File "kivy/properties.pyx", line 409, in kivy.properties.Property.init_storage
   File "kivy/properties.pyx", line 635, in kivy.properties.NumericProperty.convert
   File "kivy/properties.pyx", line 643, in kivy.properties.NumericProperty.parse_str
   File "kivy/properties.pyx", line 650, in kivy.properties.NumericProperty.parse_list
   File "kivy/properties.pyx", line 296, in kivy.properties.dpi2px
   File "/Users/Eckhardt/Library/Developer/CoreSimulator/Devices/B912277E-4A57-4E17-844C-49A34376E056/data/Containers/Bundle/Application/5F21AACA-F1AA-4C6B-9D4C-9D0317E16DA4/taskcheck.app/lib/python3.7/site-packages/kivy/utils.py", line 496, in __get__
     retval = self.func(inst)
   File "/Users/Eckhardt/Library/Developer/CoreSimulator/Devices/B912277E-4A57-4E17-844C-49A34376E056/data/Containers/Bundle/Application/5F21AACA-F1AA-4C6B-9D4C-9D0317E16DA4/taskcheck.app/lib/python3.7/site-packages/kivy/metrics.py", line 169, in dpi
     import ios
   File "ios.pyx", line 210, in init ios
   File "/Users/Eckhardt/Library/Developer/CoreSimulator/Devices/B912277E-4A57-4E17-844C-49A34376E056/data/Containers/Bundle/Application/5F21AACA-F1AA-4C6B-9D4C-9D0317E16DA4/taskcheck.app/lib/python3.7/site-packages/pyobjus/__init__.py", line 2, in <module>
     from .pyobjus import *
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
   File "<string>", line 39, in load_module
   File "/Users/Eckhardt/Project/kivy-ios/dist/root/python3/lib/python3.7/imp.py", line 342, in load_dynamic
   File "pyobjus/pyobjus_types.pxi", line 10, in init pyobjus.pyobjus
 NameError: name 'ulng' is not defined
2018-11-16 14:20:58.414022-0500 taskcheck[95444:1504020] Application quit abnormally!
2018-11-16 14:20:58.480358-0500 taskcheck[95444:1504020] Leaving
```

OS: MacOS 10.14 mojave
XCode: 10.1

**Comment by cruor99** [comment]
I ran into this as well, and ended up doing this to fix it:
https://github.com/cruor99/pyobjus/commit/6d15cf4901f7c7034e4647d451e6a23b14a75a4a

It seems like PLATFORM is not being set properly, but I am not experienced enough to know where exactly that would be set.

**Comment by jefcolbi** [comment]
> I ran into this as well, and ended up doing this to fix it:
> [cruor99/pyobjus@6d15cf4](https://github.com/cruor99/pyobjus/commit/6d15cf4901f7c7034e4647d451e6a23b14a75a4a)
> 
> It seems like PLATFORM is not being set properly, but I am not experienced enough to know where exactly that would be set.
> 
> Should probably also specify I built through buildozer.

where did you apply this fix ?? i done the same fix myself but when creating a new project the same error persist.

Your app is working now ?

**Comment by cruor99** [comment]
I cloned my own kivy-ios and changed the recipe url to point to my pyobjus fork. If you look at the commit, you can see exactly the file and line I applied it to. You also need to specify your ios.kivy_ios_dir in buildozer.spec.
It's only a temporary workaround mind you, but is probably an easy fix once someone more knowledgable get around to it!

**Comment by jefcolbi** [comment]
when doing like you say i got a python error:
zipfile.BadZipFile: File is not a zip file

in the recipe i set the url to "https://github.com/cruor99/pyobjus/archive.master.zip"

**Comment by jefcolbi** [comment]
it is the same of course i just changed {version} to master but even with {version} i have a badzipfile

**Comment by tito** [comment]
I don't understand the issue, i don't reproduce the compilation issue.
Check yourself: in kivy-ios directory: `find build/pyobjus|grep config.pxi|xargs cat`
Or in the main.py: `import pyobjus; print(pyobjus.dev_platform)`

**Comment by cruor99** [comment]
You're correct, it does appear: DEV PLATFORM: b'ios'
I wonder, could it be related to having python3 being the default python interpreter in my interpreter?
I saw you had a commit that mentioned something about forcing the use of the system python2 setup.

**Comment by HirotsuguMINOWA** [comment]
I met same the problem and solved by revised as below.

1. `./toolchain.py build pyobjus` was ran, then the source was cached to `.cache` 
2. at `.cache/pyobjus-master/pyobjus/pyobjus_types.pxi`

```L5(source)
elif PLATFORM == b'ios':
```
is changed to below
```L5(fixed)
elif PLATFORM == b'ios' or PLATFORM=='ios':
```
solved. the my app was ran on ios emu.

**Comment by bsnresearcher** [comment]
I met same the problem and solved as below procedure.

1. `./toolchain.py build pyobjus` was ran, then the source file(.zip) was cached to `.cache` 
2. unpacked the `pyobjus-master.zip`
3. rewrite
at `.cache/pyobjus-master/pyobjus/pyobjus_types.pxi`
```L5(source)
elif PLATFORM == b'ios':
```
is changed to below
```L5(fixed)
elif PLATFORM == b'ios' or PLATFORM=='ios':
```
4. re-packed to .zip
5. re-process from the phase `./toolchain.py build pyobjus` and `./toolchain.py update [target ios project`
solved. the my app was ran on ios emu.

**Comment by itsdaveit** [comment]
I just ran into the same issue with just the touchtracer app and used the workaround from @jefcolbi for a quick, working solution.

@tito just to make sure, that you got this right: The app builds fine but crashes on execution on the Emulator.
