### ISSUE TITLE
After adding the third branch, Python gives an error - ld: symbol(s) not found for architecture i386

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy-ios#316]
Successfully built dependencies and recipes using the command **./toolchain.py build python3 kivy**
Created a project in XCode, open and try to run it:

![2018-11-20 17 49 25](https://user-images.githubusercontent.com/16930280/48781263-be10a900-ecec-11e8-9aea-4774f5f850a0.png)

**Get the error** - ld: symbol(s) not found for architecture i386:

![2018-11-20 17 53 16](https://user-images.githubusercontent.com/16930280/48781485-2a8ba800-eced-11e8-9792-2870029dd123.png)

**XCode** version - 9.4

**Comment by tito** [comment]
Ensure the build only for active arch is selected, we don't build i386 anymore

**Comment by tamano123** [comment]
Hello,

I  i am newbie here (ios) and i have the same error as "HeaTTheatR ", how could i "Ensure the build only for active arch is selected"
Thank you

**Comment by jefcolbi** [comment]
> Hello,
> 
> I am newbie here (ios) and i have the same error as "HeaTTheatR ", how could i "Ensure the build only for active arch is selected"
> Thank you
> 
> Xcode version 10.1

Double click on your project name, on the previous picture 'helloword',
then click on the build settings tab
then you will see something Build only architecture choose 'yes'

you are done.

**Comment by HeaTTheatR** [comment]
@jefcolbi, yes it works! It is necessary to do as shown in the screenshot!

![2018-11-22 18 25 26](https://user-images.githubusercontent.com/16930280/48911592-32ca1b80-ee84-11e8-8047-f7d2daf04d07.png)

The emulator starts, the application starts and causes an error **NameError: name 'ulng' is not defined**

![2018-11-22 18 29 41](https://user-images.githubusercontent.com/16930280/48911710-92282b80-ee84-11e8-9bc8-b0c743b32c5a.png)

```python
2018-11-22 18:24:06.191849+0300 helloworld[18771:2230753] +[CATransaction synchronize] called within transaction
2018-11-22 18:24:06.880238+0300 helloworld[18771:2230753] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2018-11-22 18:24:06.881386+0300 helloworld[18771:2230753] Initializing python
/Users/macbookair/Library/Developer/CoreSimulator/Devices/D9C61C40-B88D-4625-9F43-BFD652A5C504/data/Containers/Bundle/Application/D4C76B41-D377-4E97-9ED5-87BF4A431822/helloworld.app/helloworld:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
2018-11-22 18:24:07.209960+0300 helloworld[18771:2230753] Running main.py: /Users/macbookair/Library/Developer/CoreSimulator/Devices/D9C61C40-B88D-4625-9F43-BFD652A5C504/data/Containers/Bundle/Application/D4C76B41-D377-4E97-9ED5-87BF4A431822/helloworld.app/YourApp/main.pyc
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (default, Nov 16 2018, 15:09:36) 
[Clang 9.1.0 (clang-902.0.39.2)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "/Users/macbookair/Opt/kivy-ios/helloworld-ios/YourApp/main.py", line 13, in <module>
   File "/Users/macbookair/Library/Developer/CoreSimulator/Devices/D9C61C40-B88D-4625-9F43-BFD652A5C504/data/Containers/Bundle/Application/D4C76B41-D377-4E97-9ED5-87BF4A431822/helloworld.app/lib/python3.7/site-packages/kivy/app.py", line 800, in run
     root = self.build()
   File "/Users/macbookair/Opt/kivy-ios/helloworld-ios/YourApp/main.py", line 10, in build
   File "kivy/_event.pyx", line 188, in kivy._event.EventDispatcher.__cinit__
   File "kivy/properties.pyx", line 438, in kivy.properties.Property.link
   File "kivy/properties.pyx", line 612, in kivy.properties.NumericProperty.init_storage
   File "kivy/properties.pyx", line 409, in kivy.properties.Property.init_storage
   File "kivy/properties.pyx", line 635, in kivy.properties.NumericProperty.convert
   File "kivy/properties.pyx", line 643, in kivy.properties.NumericProperty.parse_str
   File "kivy/properties.pyx", line 650, in kivy.properties.NumericProperty.parse_list
   File "kivy/properties.pyx", line 296, in kivy.properties.dpi2px
   File "/Users/macbookair/Library/Developer/CoreSimulator/Devices/D9C61C40-B88D-4625-9F43-BFD652A5C504/data/Containers/Bundle/Application/D4C76B41-D377-4E97-9ED5-87BF4A431822/helloworld.app/lib/python3.7/site-packages/kivy/utils.py", line 496, in __get__
     retval = self.func(inst)
   File "/Users/macbookair/Library/Developer/CoreSimulator/Devices/D9C61C40-B88D-4625-9F43-BFD652A5C504/data/Containers/Bundle/Application/D4C76B41-D377-4E97-9ED5-87BF4A431822/helloworld.app/lib/python3.7/site-packages/kivy/metrics.py", line 169, in dpi
     import ios
   File "ios.pyx", line 210, in init ios
   File "/Users/macbookair/Library/Developer/CoreSimulator/Devices/D9C61C40-B88D-4625-9F43-BFD652A5C504/data/Containers/Bundle/Application/D4C76B41-D377-4E97-9ED5-87BF4A431822/helloworld.app/lib/python3.7/site-packages/pyobjus/__init__.py", line 2, in <module>
     from .pyobjus import *
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
   File "<string>", line 39, in load_module
   File "/Users/macbookair/Opt/kivy-ios/dist/root/python3/lib/python3.7/imp.py", line 342, in load_dynamic
   File "pyobjus/pyobjus_types.pxi", line 10, in init pyobjus.pyobjus
 NameError: name 'ulng' is not defined
2018-11-22 18:24:08.036760+0300 helloworld[18771:2230753] Application quit abnormally!
2018-11-22 18:24:08.061214+0300 helloworld[18771:2230753] Leaving
```

**Comment by tito** [comment]
@HeaTTheatR the second part of your issue got fixed in pyobjus, you need to clear the cache and rebuild. It also had been reported before.

**Comment by HeaTTheatR** [comment]
@tito, If I remove the kivy-ios and collect it again, will the problem be solved?

**Comment by HeaTTheatR** [comment]
@tito, what cache do you mean where it is located?

**Comment by tito** [comment]
@HeaTTheatR kivy-ios/.cache/pyobjus*

**Comment by HeaTTheatR** [comment]
@tito, rebuilt kivy-ios - problem solved, thanks!
