### ISSUE TITLE
toolchain.py build numpy fails

### ISSUE THREAD

**Issue by Chao-Jen** [kivy/kivy-ios#327]
Not sure if anyone also got the same issue. After git cloning the latest dev version,   toolchain.py build numpy fails with the following error:

Traceback (most recent call last):
  File "./toolchain.py", line 1482, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1218, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1259, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 1097, in build_recipes
    recipe.execute()
  File "/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/toolchain.py", line 694, in execute
    self.build_all()
  File "/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/toolchain.py", line 63, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/toolchain.py", line 789, in build_all
    self.build(arch)
  File "/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/toolchain.py", line 63, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/toolchain.py", line 776, in build
    self.build_arch(arch)
  File "/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/recipes/numpy/__init__.py", line 35, in build_arch
    super(NumpyRecipe, self).build_arch(arch)
  File "/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/toolchain.py", line 1051, in build_arch
    _env=build_env)
  File "/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/toolchain.py", line 46, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1:

  RAN: '/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/dist/hostpython3/bin/python setup.py build_ext -g'

  STDOUT:
Running from numpy source directory.
/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/dist/hostpython3/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
non-existing path in 'numpy/distutils': 'site.cfg'
non-existing path in 'numpy/f2py': 'docs'
non-existing path in 'numpy/f2py': 'f2py.1'
F2PY Version 2
blas_opt_info:
blas_mkl_info:
  libraries mkl,vml,guide not found in ['/Users/enoch/tmp/build_kivy-ios_20181230/kivy-ios/dist/hostpython3/lib', '/usr/local/lib', '/usr/lib']
  NOT AVAILABLE

openblas_info:
  FOUND:
    libraries = ['openblas']
    library_dirs = ['/usr/local/lib']
    language = f77

  FOUND:
    libraries = ['openblas']
    library_dirs = ['/usr/local/lib']
   ... (960922 more, please see e.stdout)

  STDERR:

**Comment by Chao-Jen** [comment]
Does anyone manage to build numpy with hostpython3?

**Comment by KazukiOhta** [comment]
I have the same problem.
The whole output with the error message is attached to this comment.
[myWholeOutput.txt](https://github.com/kivy/kivy-ios/files/2896942/myWholeOutput.txt)

**Comment by KazukiOhta** [comment]
P. S.
My environment:
MacBook Pro 2018
macOS 10.14.3
python3.7.2

**Comment by KazukiOhta** [comment]
I found that my numpy installed with pip3 was version 1.16.1. However, when I run the `./toolchain.py recipes`, its numpy version was 1.9.1.
I think this is the reason why our `./toolchain.py build numpy` failed.

**Comment by drake666** [comment]
I've got the exact same problem, with
python 3.7.2
macOS 10.13.6
MacBook Pro Mid 1010

I think its a gcc problem.
