### ISSUE TITLE
./toolchain.py build python3 fails on '/usr/bin/make -j4'

### ISSUE THREAD

**Issue by ssolari** [kivy/kivy-ios#329]
Mac OS Mojave 10.14
Xcode Version 10.1 (10B61)
cython: 0.28.1

I had an old version kivy-ios that I had compiled and seemed to be working.   I was trying to deal with some recipes and deleted the kivy-ios directory then re-cloned it to try to get a reproducible process.    Since then I get a compliation error when trying to build python3.  ```./toolchain.py build python3 kivy```

This seems to be a similar error as in another issue #267.  I'm not sure if it might be related.

## Error

```
...
/tmp/tmpb4_8_hyf -arch x86_64 --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -L/build_kivy/kivy-ios/dist/lib -lsqlite3 -miphoneos-version-min=7.0 -undefined dynamic_lookup   -o Programs/_testembed Programs/_testembed.o libpython3.7m.a -ldl  -lssl                -lssl                 -lz                              -lm  
ld: warning: ld: warning: -undefined dynamic_lookup is deprecated on iOS Simulator
-undefined dynamic_lookup is deprecated on iOS Simulator
_PYTHON_PROJECT_BASE=/build_kivy/kivy-ios/build/python3/x86_64/Python-3.7.1 _PYTHON_HOST_PLATFORM=ios-x86_64 PYTHONPATH=./Lib _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_m_ios_darwin python3.7 -S -m sysconfig --generate-posix-vars ;\
	if test $? -ne 0 ; then \
		echo "generate-posix-vars failed" ; \
		rm -f ./pybuilddir.txt ; \
		exit 1 ; \
	fi
/bin/sh: python3.7: command not found
generate-posix-vars failed
make: *** [pybuilddir.txt] Error 1
Traceback (most recent call last):
  File "./toolchain.py", line 1482, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1218, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1259, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 1097, in build_recipes
    recipe.execute()
  File "/build_kivy/kivy-ios/toolchain.py", line 694, in execute
    self.build_all()
  File "/build_kivy/kivy-ios/toolchain.py", line 63, in _cache_execution
    f(self, *args, **kwargs)
  File "/build_kivy/kivy-ios/toolchain.py", line 789, in build_all
    self.build(arch)
  File "/build_kivy/kivy-ios/toolchain.py", line 63, in _cache_execution
    f(self, *args, **kwargs)
  File "/build_kivy/kivy-ios/toolchain.py", line 776, in build
    self.build_arch(arch)
  File "/build_kivy/kivy-ios/recipes/python3/__init__.py", line 92, in build_arch
    shprint(sh.make, self.ctx.concurrent_make)
  File "/build_kivy/kivy-ios/toolchain.py", line 46, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_2: 

  RAN: '/usr/bin/make -j4'

  STDOUT:
Makefile:1865: warning: overriding commands for target `Modules/_math.o'
Makefile:605: warning: ignoring old commands for target `Modules/_math.o'
/tmp/tmpb4_8_hyf -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=7.0 -I/build_kivy/kivy-ios/dist/include/x86_64/freetype -I/build_kivy/kivy-ios/dist/include/x86_64/ffi -I/build_kivy/kivy-ios/dist/include/x86_64/openssl -I/build_kivy/kivy-ios/dist/include/common/sdl2 -I/build_kivy/kivy-ios/dist/include/common/sdl2_image -I/build_kivy/kivy-ios/dist/include/common/sdl2_mixer -I/build_kivy/kivy-ios/dist/include/common/sdl2_ttf -I/build_kivy/kivy-ios/dist/include/x86_64   -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-fiel... (166065 more, please see e.stdout)

  STDERR:
```

**Comment by ssolari** [comment]
For someone who finds this and maybe hit something similar.    My solution was to delete and re-clone kivy-ios, reinstall all the brew packages, and use cython 0.29.1 (instead of 0.28.1) with python3.7.1.   Everything compiled.
