### ISSUE TITLE
cmunk build failed - cymunk/cymunk.c not found

### ISSUE THREAD

**Issue by maho** [kivy/kivy-ios#350]
Build failed, log attached. Any hint what am I doing wrong? 

```sh
(kivy-ios) maho@mac ~/workspace-p/kivy-ios $ ./toolchain.py build cymunk
./toolchain.py:72: DeprecationWarning: ChromeDownloader style of invoking requests is deprecated. Use newer urlopen functions/methods
  urlretrieve = ChromeDownloader().retrieve
Building with 8 processes, where supported
Want to build ['cymunk']
Loaded recipe cymunk (depends of ['hostpython'], optional are [])
Loaded recipe hostpython (depends of ['hostpython3'], optional are [])
Loaded recipe hostpython3 (depends of [], optional are ['openssl'])
Build order is ['openssl', 'hostpython3', 'hostpython', 'cymunk']
Recipe order is ['openssl', 'hostpython3', 'cymunk']
Include dir added: {arch.arch}/openssl
Global: hostpython located at /Users/maho/workspace-p/kivy-ios/dist/hostpython3/bin/python
Global: hostpgen located at /Users/maho/workspace-p/kivy-ios/dist/hostpython3/bin/pgen
# (ignored) Download openssl
# (ignored) Extract openssl
# (ignored) Build_all openssl
# (ignored) Download hostpython3
# (ignored) Extract hostpython3
# (ignored) Build_all hostpython3
# (ignored) Download cymunk
# (ignored) Extract cymunk
Build_all cymunk
Build cymunk for x86_64, arm64 (filtered)
# (ignored) Build cymunk
# (ignored) Build cymunk
Install include files for cymunk
# (ignored) Install_include cymunk
Install frameworks for cymunk
# (ignored) Install_frameworks cymunk
Install sources for cymunk
# (ignored) Install_sources cymunk
Install cymunk
CC and CXX will not use ccache
Using distutils
running build_ext
building 'cymunk.cymunk' extension
/tmp/tmppoj6yjoi -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/maho/workspace-p/kivy-ios/dist/include/x86_64/openssl -I/Users/maho/workspace-p/kivy-ios/dist/include/x86_64 -I/Users/maho/workspace-p/kivy-ios/build/cymunk/x86_64/cymunk-master/cymunk/Chipmunk-Physics/include -I/Users/maho/workspace-p/kivy-ios/build/cymunk/x86_64/cymunk-master/cymunk/Chipmunk-Physics/include/chipmunk -I/Users/maho/workspace-p/kivy-ios/dist/hostpython3/include/python3.7m -c cymunk/cymunk.c -o build/temp.macosx-10.13-x86_64-3.7/cymunk/cymunk.o -std=c99 -ffast-math -fPIC -DCHIPMUNK_FFI
clang: error: no such file or directory: 'cymunk/cymunk.c'
clang: error: no input files
error: command '/tmp/tmppoj6yjoi' failed with exit status 1
Traceback (most recent call last):
  File "./toolchain.py", line 1486, in <module>
    ToolchainCL()
  File "./toolchain.py", line 1221, in __init__
    getattr(self, args.command)()
  File "./toolchain.py", line 1262, in build
    build_recipes(args.recipe, ctx)
  File "./toolchain.py", line 1099, in build_recipes
    recipe.execute()
  File "/Users/maho/workspace-p/kivy-ios/toolchain.py", line 673, in execute
    self.build_all()
  File "/Users/maho/workspace-p/kivy-ios/toolchain.py", line 62, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/maho/workspace-p/kivy-ios/toolchain.py", line 806, in build_all
    self.install()
  File "/Users/maho/workspace-p/kivy-ios/recipes/cymunk/__init__.py", line 51, in install
    _env=build_env)
  File "/Users/maho/workspace-p/kivy-ios/toolchain.py", line 46, in shprint
    for line in command(*args, **kwargs):
  File "./tools/external/sh.py", line 565, in next
    self.wait()
  File "./tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "./tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1:

  RAN: '/Users/maho/workspace-p/kivy-ios/dist/hostpython3/bin/python /Users/maho/workspace-p/kivy-ios/build/cymunk/x86_64/cymunk-master/setup.py build_ext install'

  STDOUT:
Using distutils
running build_ext
building 'cymunk.cymunk' extension
/tmp/tmppoj6yjoi -DNDEBUG -g -fwrapv -O3 -Wall -O3 -miphoneos-version-min=8.0 -I/Users/maho/workspace-p/kivy-ios/dist/include/x86_64/openssl -I/Users/maho/workspace-p/kivy-ios/dist/include/x86_64 -I/Users/maho/workspace-p/kivy-ios/build/cymunk/x86_64/cymunk-master/cymunk/Chipmunk-Physics/include -I/Users/maho/workspace-p/kivy-ios/build/cymunk/x86_64/cymunk-master/cymunk/Chipmunk-Physics/include/chipmunk -I/Users/maho/workspace-p/kivy-ios/dist/hostpython3/include/python3.7m -c cymunk/cymunk.c -o build/temp.macosx-10.13-x86_64-3.7/cymunk/cymunk.o -std=c99 -ffast-math -fPIC -DCHIPMUNK_FFI
clang: error: no such file or directory: 'cymunk/cymunk.c'
clang: error: no input files
... (60 more, please see e.stdout)

  STDERR:

(kivy-ios) maho@mac ~/workspace-p/kivy-ios $
```

**Comment by mahomahomaho** [comment]
I have modified recipe, and it builds. But doesn't work. 
My modification are here: https://github.com/kivy/kivy-ios/compare/master...mahomahomaho:cymunk-py3?expand=1

And runtime error is following:

```
2019-01-29 18:08:37.649149+0100 alcan[45151:1023639] [framework] CUIThemeStore: No theme registered with id=0
2019-01-29 18:08:37.747323+0100 alcan[45151:1023639] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2019-01-29 18:08:37.747461+0100 alcan[45151:1023639] Initializing python
/Users/maho/Library/Developer/CoreSimulator/Devices/4CBC3D3F-CEEC-463D-8568-CD4B38A9761A/data/Containers/Bundle/Application/FD6829A6-57F8-4833-A160-958ECE8A7F09/alcan.app/alcan:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
2019-01-29 18:08:37.863120+0100 alcan[45151:1023639] Running main.py: /Users/maho/Library/Developer/CoreSimulator/Devices/4CBC3D3F-CEEC-463D-8568-CD4B38A9761A/data/Containers/Bundle/Application/FD6829A6-57F8-4833-A160-958ECE8A7F09/alcan.app/YourApp/main.pyc
Traceback (most recent call last):
  File "<string>", line 39, in load_module
  File "/Users/maho/workspace-p/kivy-ios/dist/root/python3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dynamic module does not define module export function (PyInit_cymunk_cymunk)
Traceback (most recent call last):
  File "<string>", line 39, in load_module
  File "/Users/maho/workspace-p/kivy-ios/dist/root/python3/lib/python3.7/imp.py", line 342, in load_dynamic
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dynamic module does not define module export function (PyInit_cymunk_cymunk)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maho/workspace-p/kivy-ios/alcan-ios/YourApp/main.py", line 4, in <module>
  File "/Users/maho/Library/Developer/CoreSimulator/Devices/4CBC3D3F-CEEC-463D-8568-CD4B38A9761A/data/Containers/Bundle/Application/FD6829A6-57F8-4833-A160-958ECE8A7F09/alcan.app/lib/python3.7/site-packages/cymunk/__init__.py", line 1, in <module>
    from .cymunk import *
  File "<string>", line 43, in load_module
  File "/Users/maho/workspace-p/kivy-ios/dist/root/python3/lib/python3.7/imp.py", line 342, in load_dynamic
ImportError: dynamic module does not define module export function (PyInit_cymunk)
2019-01-29 18:08:37.875595+0100 alcan[45151:1023639] Application quit abnormally!
2019-01-29 18:08:37.877774+0100 alcan[45151:1023639] Leaving
```

**Comment by mahomahomaho** [comment]
```
(kivy-ios) maho@mac ~/workspace-p/kivy-ios $ nm build/kivy/arm64/kivy-1.10.1/build/lib.macosx-10.13-x86_64-3.7/kivy/_clock.cpython
-37m-darwin.so.o | grep PyInit
0000000000000000 T _PyInit_kivy__clock
(kivy-ios) maho@mac ~/workspace-p/kivy-ios $
```

**Comment by mahomahomaho** [comment]
oh, I think I did it (however, not tested in game yet, but can be imported)

**Comment by Zen-CODE** [comment]
The issue appears resolved? Please re-open if not.
