### ISSUE TITLE
app locks up after popup keyboard appears

### ISSUE THREAD

**Issue by brentpicasso** [kivy/kivy-ios#366]
kivy-ios, python 2.7, kivy 1.10.1

When a keyboard pops up in our app (e.g. a text input) the app goes into an endless loop with these errors repeating in an endless loop:

Our app does not do this on Windows or Android, only iOS.  However, we made a simple helloworld test app and this problem does not reproduce. 

Any suggestions on what we can do to narrow it down? 

==========

[CRITICAL] [CrashHandler] Caught exception in Kivy loop: cannot convert float NaN to integer
[CRITICAL] [Traceback (most recent call last)]
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
    self._mainloop()
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
    EventLoop.idle()
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/base.py", line 337, in idle
    Clock.tick()
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
    self._process_events()
  File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/animation.py", line 346, in _update
    setattr(widget, key, value)
  File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
  File "kivy/properties.pyx", line 524, in kivy.properties.Property.set
  File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch
  File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 898, in <lambda>
    self.bind(_kheight=lambda *args: self.update_viewport())
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1434, in update_viewport
    glViewport(x, y, w, _h)
  File "kivy/graphics/opengl.pyx", line 1548, in kivy.graphics.opengl.glViewport
ValueError: cannot convert float NaN to integer

[CRITICAL] [CrashHandler] Caught exception in Kivy loop: cannot convert float NaN to integer
[CRITICAL] [Traceback (most recent call last)]
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
    self._mainloop()
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
    EventLoop.idle()
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/base.py", line 337, in idle
    Clock.tick()
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
    self._process_events()
  File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/animation.py", line 346, in _update
    setattr(widget, key, value)
  File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
  File "kivy/properties.pyx", line 524, in kivy.properties.Property.set
  File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch
  File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 898, in <lambda>
    self.bind(_kheight=lambda *args: self.update_viewport())
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1434, in update_viewport
    glViewport(x, y, w, _h)
  File "kivy/graphics/opengl.pyx", line 1548, in kivy.graphics.opengl.glViewport
ValueError: cannot convert float NaN to integer

[CRITICAL] [CrashHandler] Caught exception in Kivy loop: cannot convert float NaN to integer
[CRITICAL] [Traceback (most recent call last)]
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
    self._mainloop()
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
    EventLoop.idle()
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/base.py", line 337, in idle
    Clock.tick()
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
    self._process_events()
  File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
  File "/var/containers/Bundle/Application/E44ED6C9-BB1C-4787-8B9C-ADC6A1BC85A7/racecaptureapp.app/lib/python2.7/site-packages/kivy/animation.py", line 346, in _update
    setattr(widget, key, value)
  File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__
  File "kivy/properties.pyx", line 524, in kivy.properties.Property.set

**Comment by brentpicasso** [comment]
Found repro steps, closing and logging better issue.
