### ISSUE TITLE
Any valid Window.softinput_mode value causes iOS app to crash when keyboard pops up

### ISSUE THREAD

**Issue by brentpicasso** [kivy/kivy-ios#367]
When setting any valid softinput_mode, the app crashes.  repro script and stack track below:

* Python 2.7, XCode 10

Happens with any valid value:  ‘pan’, ‘resize’, ‘below_target’

<pre>
import kivy
kivy.require('1.10.1') # replace with your current kivy version !
from kivy.app import App
from kivy.uix.textinput import TextInput
from kivy.core.window import Window

class MyApp(App):
    def build(self):
        Window.softinput_mode = 'below_target'
        return TextInput(text='Hello world')

if __name__ == '__main__':
    MyApp().run()
</pre>

<pre>
2019-03-13 07:31:50.352677-0700 kivy_hellotext[420:85142] [DYMTLInitPlatform] platform initialization successful

2019-03-13 07:31:50.663015-0700 kivy_hellotext[420:85038] Could not load IOSurface for time string. Rendering locally instead.

2019-03-13 07:31:50.757276-0700 kivy_hellotext[420:85038] [framework] CUIThemeStore: No theme registered with id=0

2019-03-13 07:31:50.877317-0700 kivy_hellotext[420:85038] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown

2019-03-13 07:31:50.877437-0700 kivy_hellotext[420:85038] PythonHome is: /var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app

2019-03-13 07:31:50.879578-0700 kivy_hellotext[420:85038] Initializing python

2019-03-13 07:31:51.034390-0700 kivy_hellotext[420:85038] Running main.py: /var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/YourApp/main.pyo

[INFO   ] [Kivy        ] v1.10.1

[INFO   ] [Python      ] v2.7.1 (r271:86832, Nov 30 2018, 12:13:19) 

[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

[INFO   ] [Factory     ] 194 symbols loaded

[INFO   ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil, img_gif ignored)

[INFO   ] [Text        ] Provider: sdl2

[INFO   ] [Window      ] Provider: sdl2

[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system

[INFO   ] [GL          ] Backend used <sdl2>

[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0 Apple A7 GPU - 130.1>

[INFO   ] [GL          ] OpenGL vendor <Apple Inc.>

[INFO   ] [GL          ] OpenGL renderer <Apple A7 GPU>

[INFO   ] [GL          ] OpenGL parsed version: 2, 0

[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>

[INFO   ] [GL          ] Texture max size <4096>

[INFO   ] [GL          ] Texture max units <8>

[INFO   ] [Window      ] auto add sdl2 input provider

[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked

Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found

Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found

[INFO   ] [GL          ] NPOT texture support is available

[INFO   ] [Base        ] Start application main loop

2019-03-13 07:33:21.756268-0700 kivy_hellotext[420:85038] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles

2019-03-13 07:33:21.758021-0700 kivy_hellotext[420:85038] [MC] Reading from public effective user settings.

2019-03-13 07:33:22.482374-0700 kivy_hellotext[420:85038] [Common] _BSMachError: port 8103; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"

[INFO   ] [Clipboard   ] Provider: sdl2

[INFO   ] [Base        ] Leaving application in progress...

 Traceback (most recent call last):

   File "/Users/macmini/git-projects/kivy-ios/kivy_hellotext-ios/YourApp/main.py", line 17, in <module>

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/app.py", line 826, in run

     runTouchApp()

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/base.py", line 502, in runTouchApp

     EventLoop.window.mainloop()

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop

     self._mainloop()

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop

     EventLoop.idle()

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/base.py", line 337, in idle

     Clock.tick()

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick

     self._process_events()

   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events

   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events

   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events

   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/animation.py", line 346, in _update

     setattr(widget, key, value)

   File "kivy/properties.pyx", line 483, in kivy.properties.Property.__set__

   File "kivy/properties.pyx", line 524, in kivy.properties.Property.set

   File "kivy/properties.pyx", line 579, in kivy.properties.Property.dispatch

   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch

   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 898, in <lambda>

     self.bind(_kheight=lambda *args: self.update_viewport())

   File "/var/containers/Bundle/Application/E0B8A8A3-80D7-4474-B124-7F8D89A261BF/kivy_hellotext.app/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1434, in update_viewport

     glViewport(x, y, w, _h)

   File "kivy/graphics/opengl.pyx", line 1548, in kivy.graphics.opengl.glViewport

 ValueError: cannot convert float NaN to integer

2019-03-13 07:33:22.655023-0700 kivy_hellotext[420:85038] Application quit abnormally!

2019-03-13 07:33:22.725459-0700 kivy_hellotext[420:85038] Leaving
</pre>

**Comment by brentpicasso** [comment]
Cross referenced this issue: 

https://github.com/kivy/kivy/issues/4129

**Comment by Dirk-Sandberg** [comment]
Happens for me too. Just found out that softinput_mode existed and am super excited to play with it once this bug is fixed!

**Comment by brentpicasso** [comment]
Strongly recommend this get prioritized as critical bug. 

Rationale:
* For just about any input fields to be in view with the soft keyboard, you must use the softinput_mode - otherwise the input fields are covered up.
* Any non-trivial app will have input fields for users
* iOS is a critical platform to support, for obvious reasons

Could this ben prioritized for Kivy 1.10.2? 

Thank you!

**Comment by Dirk-Sandberg** [comment]
Ping @tito @tshirtman any ideas on this one?

**Comment by tshirtman** [comment]
i don't have an ios device, and never have touched kivy-ios, myself, could you build a with a kivy version logging the values of `w`,  `h_`, `self.system_size` and `self.size` before the `glViewport` call? (in method `update_viewport` of `kivy/core/window/__init__.py`).

**Comment by Dirk-Sandberg** [comment]
I printed out the contents of the variables being sent to the glViewport() function:
`'x,y,w,_h being sent to glViewport() ', 0, 0, 750, 1334`

**Comment by brentpicasso** [comment]
@tshirtman We have a spare ipad we can send you if that might help the cause!

**Comment by brentpicasso** [comment]
Bump on this issue. @tshirtman  any thoughts on our offer to send you iOS devices? We are happy to help fund the project with test equipment. :)

**Comment by misl6** [comment]
@brentpicasso , can you please test PR https://github.com/kivy/kivy-ios/pull/370 ? (There's a chance that could solve your issue)

**Comment by brentpicasso** [comment]
Thanks @misl6 . Was this PR specifically to address this issue? I don't see any information in #370 regarding the purpose of the PR.

**Comment by misl6** [comment]
@brentpicasso , the PR updates a lot of important things (like `SDL` and `kivy`), so isn't specifically addressing your issue, but could fix it (at least the crash). Feel free to ping me on discord.

**Comment by hackalog** [comment]
I plan to take a look at this soon, @brentpicasso

**Comment by brentpicasso** [comment]
@hackalog  thank you, I won't be able to test immediately - looking forward to test results.

**Comment by Dirk-Sandberg** [comment]
By the way, this seems to be working just fine if building kivy-ios with Python3 instead of Python2.

**Comment by Zen-CODE** [comment]
I can confirm this seems to be working with the latest Python3.8 version. Please try the latest version and re-open if you still experience issues.
