### ISSUE TITLE
TLSV1_ALERT_UNKNOWN_CA error when connecting to server from iphone

### ISSUE THREAD

**Issue by s1113950** [kivy/kivy-ios#376]
I have set up a server and am using letsencrypt to enable https and installed my app on both Android and iOS. When I connect to the server from Android it works fine, but when connecting from iOS I get this error:
```
Traceback (most recent call last):
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/hubs/poll.py", line 111, in wait
    listener.cb(fileno)
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/wsgi.py", line 818, in process_request
    proto.__init__(conn_state, self)
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/wsgi.py", line 419, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/wsgi.py", line 402, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/green/ssl.py", line 241, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/green/ssl.py", line 256, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/green/ssl.py", line 176, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/server/.venv3/lib/python3.6/site-packages/eventlet/green/ssl.py", line 150, in _call_trampolining
    return func(*a, **kw)
  File "/usr/local/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2305)
```
Is there some cert I need to include as part of the build to get it to connect to my server over https? Or is it something on my end unrelated to the iOS app?

**Comment by s1113950** [comment]
Closing, my bad. Totally an issue with my setup...

**Comment by s1113950** [comment]
Actually reopening; I fixed my certs but it still is busted.

**Comment by s1113950** [comment]
The error on my app in the simulator is this:
```
line 1117, in do_handshake
     self._sslobj.do_handshake()
 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)
```
which I discovered could be due to the websocket-client library I use: 
https://github.com/slackapi/python-slackclient/issues/334

In 0.48.0 of the websocket library they removed the CA bundle. I'm using 0.58.0 of the library.

**Comment by s1113950** [comment]
Can confirm a downgrade fixed things for me. This is an issue with websocket-client and not kivy so closing again, sorry for the spam
