### ISSUE TITLE
Can't build a recipe for validate_email

### ISSUE THREAD

**Issue by tanabi** [kivy/kivy-ios#380]
Hey there;

I am trying to make a recipe for this package:

https://github.com/syrusakbary/validate_email

But when I try to build it, I get this:

```
mountaingoat:kivy-ios sconley$ python3 toolchain.py build validate_email
toolchain.py:93: DeprecationWarning: ChromeDownloader style of invoking requests is deprecated. Use newer urlopen functions/methods
  urlretrieve = ChromeDownloader().retrieve
[INFO    ] Building with 4 processes, where supported
[INFO    ] Want to build ['validate_email']
[INFO    ] Loaded recipe validate_email (depends of ['hostpython'], optional are [])
[INFO    ] Loaded recipe hostpython (depends of ['hostpython3'], optional are [])
[INFO    ] Loaded recipe hostpython3 (depends of [], optional are ['openssl'])
[INFO    ] Build order is ['openssl', 'hostpython3', 'hostpython', 'validate_email']
[INFO    ] Recipe order is ['openssl', 'hostpython3', 'validate_email']
[INFO    ] Include dir added: {arch.arch}/openssl
[INFO    ] Global: hostpython located at /Users/sconley/work/kivy-ios/dist/hostpython3/bin/python
[INFO    ] Global: hostpgen located at /Users/sconley/work/kivy-ios/dist/hostpython3/bin/pgen
[DEBUG   ] Cached result: Download openssl. Ignoring
[DEBUG   ] Cached result: Extract openssl. Ignoring
[DEBUG   ] Cached result: Build_all openssl. Ignoring
[DEBUG   ] Cached result: Download hostpython3. Ignoring
[DEBUG   ] Cached result: Extract hostpython3. Ignoring
[DEBUG   ] Cached result: Build_all hostpython3. Ignoring
[INFO    ] Download validate_email
[INFO    ] Downloading https://github.com/syrusakbary/validate_email/archive/master.zip
/Users/sconley/work/kivy-ios/.cache/validate_email-master.zip
[DEBUG   ] New State: validate_email.download at 2019-07-29 23:00:03.951449
[INFO    ] Extract validate_email
[INFO    ] Extract validate_email for x86_64
[INFO    ] Extract /Users/sconley/work/kivy-ios/.cache/validate_email-master.zip into /Users/sconley/work/kivy-ios/build/validate_email/x86_64
[INFO    ] Running Shell: /usr/bin/unzip ('-d', '/Users/sconley/work/kivy-ios/build/validate_email/x86_64', '/Users/sconley/work/kivy-ios/.cache/validate_email-master.zip') {'_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[DEBUG   ] Archive:  /Users/sconley/work/kivy-ios/.cache/validate_email-master.zip
[DEBUG   ] eaf2668a84b6fb40d9138056b63bc74c6d718d95
[DEBUG   ]    creating: /Users/sconley/work/kivy-ios/build/validate_email/x86_64/validate_email-master/
[DEBUG   ]  extracting: /Users/sconley/work/kivy-ios/build/validate_email/x86_64/validate_email-master/.gitignore
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/x86_64/validate_email-master/AUTHORS
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/x86_64/validate_email-master/INSTALL.txt
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/x86_64/validate_email-master/LICENSE
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/x86_64/validate_email-master/MANIFEST.in
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/x86_64/validate_email-master/README.rst
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/x86_64/validate_email-master/setup.py
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/x86_64/validate_email-master/vagrant_setup.md
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/x86_64/validate_email-master/validate_email.py
[INFO    ] Extract validate_email for arm64
[INFO    ] Extract /Users/sconley/work/kivy-ios/.cache/validate_email-master.zip into /Users/sconley/work/kivy-ios/build/validate_email/arm64
[INFO    ] Running Shell: /usr/bin/unzip ('-d', '/Users/sconley/work/kivy-ios/build/validate_email/arm64', '/Users/sconley/work/kivy-ios/.cache/validate_email-master.zip') {'_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[DEBUG   ] Archive:  /Users/sconley/work/kivy-ios/.cache/validate_email-master.zip
[DEBUG   ] eaf2668a84b6fb40d9138056b63bc74c6d718d95
[DEBUG   ]    creating: /Users/sconley/work/kivy-ios/build/validate_email/arm64/validate_email-master/
[DEBUG   ]  extracting: /Users/sconley/work/kivy-ios/build/validate_email/arm64/validate_email-master/.gitignore
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/arm64/validate_email-master/AUTHORS
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/arm64/validate_email-master/INSTALL.txt
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/arm64/validate_email-master/LICENSE
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/arm64/validate_email-master/MANIFEST.in
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/arm64/validate_email-master/README.rst
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/arm64/validate_email-master/setup.py
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/arm64/validate_email-master/vagrant_setup.md
[DEBUG   ]   inflating: /Users/sconley/work/kivy-ios/build/validate_email/arm64/validate_email-master/validate_email.py
[DEBUG   ] New State: validate_email.extract at 2019-07-29 23:00:04.011489
[INFO    ] Build_all validate_email
[INFO    ] Build validate_email for x86_64, arm64 (filtered)
[INFO    ] Build validate_email
[INFO    ] Prebuild validate_email for x86_64
[DEBUG   ] Invoking prebuild_x86_64
[INFO    ] Build validate_email for x86_64
[DEBUG   ] Invoking build_x86_64
[INFO    ] Postbuild validate_email for x86_64
[DEBUG   ] Invoking postbuild_x86_64
[DEBUG   ] New State: validate_email.build.x86_64 at 2019-07-29 23:00:04.014415
[INFO    ] Build validate_email
[INFO    ] Prebuild validate_email for arm64
[DEBUG   ] Invoking prebuild_arm64
[INFO    ] Build validate_email for arm64
[DEBUG   ] Invoking build_arm64
[INFO    ] Postbuild validate_email for arm64
[DEBUG   ] Invoking postbuild_arm64
[DEBUG   ] New State: validate_email.build.arm64 at 2019-07-29 23:00:04.017177
[INFO    ] Install include files for validate_email
[INFO    ] Install_include validate_email
[DEBUG   ] New State: validate_email.install_include at 2019-07-29 23:00:04.019309
[INFO    ] Install frameworks for validate_email
[INFO    ] Install_frameworks validate_email
[DEBUG   ] New State: validate_email.install_frameworks at 2019-07-29 23:00:04.021267
[INFO    ] Install sources for validate_email
[INFO    ] Install_sources validate_email
[DEBUG   ] New State: validate_email.install_sources at 2019-07-29 23:00:04.023830
[INFO    ] Install validate_email
[INFO    ] CC and CXX will not use ccache
[INFO    ] Running Shell: /usr/bin/sed ('-i', '', 's/setuptools/distutils.core/g', './setup.py') {'_env': {'CC': '/var/folders/y9/xxww37fn2pz0wsgyfqdt584h0000gn/T/tmpi_qyw0hs', 'CXX': '/var/folders/y9/xxww37fn2pz0wsgyfqdt584h0000gn/T/tmp3x8s2wty', 'AR': '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar', 'LD': '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld', 'OTHER_CFLAGS': '-I/Users/sconley/work/kivy-ios/dist/include/x86_64/openssl -I/Users/sconley/work/kivy-ios/dist/include/x86_64', 'OTHER_LDFLAGS': '-L/Users/sconley/work/kivy-ios/dist/lib', 'CFLAGS': '-O3 -miphoneos-version-min=8.0 -I/Users/sconley/work/kivy-ios/dist/include/x86_64/openssl -I/Users/sconley/work/kivy-ios/dist/include/x86_64', 'LDFLAGS': '-arch x86_64 --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -L/Users/sconley/work/kivy-ios/dist/lib -lsqlite3 -miphoneos-version-min=8.0', 'PYTHONPATH': '/Users/sconley/work/kivy-ios/dist/root/python/lib/python2.7/site-packages'}, '_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[INFO    ] Running Shell: /Users/sconley/work/kivy-ios/dist/hostpython3/bin/python ('setup.py', 'install', '--prefix', '/Users/sconley/work/kivy-ios/dist/root/python') {'_env': {'CC': '/var/folders/y9/xxww37fn2pz0wsgyfqdt584h0000gn/T/tmpi_qyw0hs', 'CXX': '/var/folders/y9/xxww37fn2pz0wsgyfqdt584h0000gn/T/tmp3x8s2wty', 'AR': '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar', 'LD': '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld', 'OTHER_CFLAGS': '-I/Users/sconley/work/kivy-ios/dist/include/x86_64/openssl -I/Users/sconley/work/kivy-ios/dist/include/x86_64', 'OTHER_LDFLAGS': '-L/Users/sconley/work/kivy-ios/dist/lib', 'CFLAGS': '-O3 -miphoneos-version-min=8.0 -I/Users/sconley/work/kivy-ios/dist/include/x86_64/openssl -I/Users/sconley/work/kivy-ios/dist/include/x86_64', 'LDFLAGS': '-arch x86_64 --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -L/Users/sconley/work/kivy-ios/dist/lib -lsqlite3 -miphoneos-version-min=8.0', 'PYTHONPATH': '/Users/sconley/work/kivy-ios/dist/root/python/lib/python2.7/site-packages'}, '_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[DEBUG   ] Traceback (most recent call last):
[DEBUG   ]   File "setup.py", line 1, in <module>
[DEBUG   ]     from distutils.core import setup, find_packages
[DEBUG   ] ImportError: cannot import name 'find_packages' from 'distutils.core' (/Users/sconley/work/kivy-ios/dist/hostpython3/lib/python3.7/distutils/core.py)
Traceback (most recent call last):
  File "toolchain.py", line 1570, in <module>
    ToolchainCL()
  File "toolchain.py", line 1285, in __init__
    getattr(self, args.command)()
  File "toolchain.py", line 1326, in build
    build_recipes(args.recipe, ctx)
  File "toolchain.py", line 1162, in build_recipes
    recipe.execute()
  File "/Users/sconley/work/kivy-ios/toolchain.py", line 729, in execute
    self.build_all()
  File "/Users/sconley/work/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/sconley/work/kivy-ios/toolchain.py", line 862, in build_all
    self.install()
  File "/Users/sconley/work/kivy-ios/recipes/validate_email/__init__.py", line 21, in install
    shprint(hostpython, "setup.py", "install", "--prefix", dest_dir, _env=build_env)
  File "/Users/sconley/work/kivy-ios/toolchain.py", line 67, in shprint
    for line in cmd:
  File "tools/external/sh.py", line 565, in next
    self.wait()
  File "tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1:

  RAN: '/Users/sconley/work/kivy-ios/dist/hostpython3/bin/python setup.py install --prefix /Users/sconley/work/kivy-ios/dist/root/python'

  STDOUT:
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from distutils.core import setup, find_packages
ImportError: cannot import name 'find_packages' from 'distutils.core' (/Users/sconley/work/kivy-ios/dist/hostpython3/lib/python3.7/distutils/core.py)


  STDERR:
```

My recipe is simple:

```
# pure-python package, this can be removed when we'll support any python package
from toolchain import PythonRecipe, shprint
from os.path import join
import sh, os

class ValidateEmailRecipe(PythonRecipe):
    version = "master"
    url = "https://github.com/syrusakbary/validate_email/archive/{version}.zip"
    depends = ['hostpython']

    def install(self):
        arch = list(self.filtered_archs)[0]
        build_dir = self.get_build_dir(arch.arch)
        os.chdir(build_dir)
        hostpython = sh.Command(self.ctx.hostpython)
        build_env = arch.get_env()
        dest_dir = join(self.ctx.dist_dir, "root", "python")
        build_env['PYTHONPATH'] = join(dest_dir, 'lib', 'python2.7', 'site-packages')
        cmd = sh.Command("sed")
        shprint(cmd, "-i", "", "s/setuptools/distutils.core/g", "./setup.py", _env=build_env)
        shprint(hostpython, "setup.py", "install", "--prefix", dest_dir, _env=build_env)
mountaingoat:validate_email sconley$ more __init__.py
# pure-python package, this can be removed when we'll support any python package
from toolchain import PythonRecipe, shprint
from os.path import join
import sh, os

class ValidateEmailRecipe(PythonRecipe):
    version = "master"
    url = "https://github.com/syrusakbary/validate_email/archive/{version}.zip"
    depends = ['hostpython']

    def install(self):
        arch = list(self.filtered_archs)[0]
        build_dir = self.get_build_dir(arch.arch)
        os.chdir(build_dir)
        hostpython = sh.Command(self.ctx.hostpython)
        build_env = arch.get_env()
        dest_dir = join(self.ctx.dist_dir, "root", "python")
        build_env['PYTHONPATH'] = join(dest_dir, 'lib', 'python2.7', 'site-packages')
        cmd = sh.Command("sed")
        shprint(cmd, "-i", "", "s/setuptools/distutils.core/g", "./setup.py", _env=build_env)
        shprint(hostpython, "setup.py", "install", "--prefix", dest_dir, _env=build_env)

recipe = ValidateEmailRecipe()
```

It looks like setuptools (which has find_package) is part of hostpython ... so I'm not sure how to go about fixing this?

**Comment by tito** [comment]
I think that you should depends of "host_setuptools" (we should install setuptools by default imo).
Then don't sed to distutils.core, it doesn't exist.

```
$ python3
Python 3.7.4 (default, Jul 16 2019, 07:12:58) 
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils.core import find_package
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'find_package' from 'distutils.core' (/usr/lib/python3.7/distutils/core.py)
```

**Comment by Zen-CODE** [comment]
For reference, this is the same error that I am getting when trying to build the markupsafe recipe for flask for python3. Removing sed command does nothing: it's the main call to the hostpython "python setup.py install" that causes the failure...

https://gist.github.com/Zen-CODE/3c0cc439973b44d805aae4331516d4e7

**Comment by Zen-CODE** [comment]
Feel free to reopen with fresh logs if the problem persists.
