### ISSUE TITLE
toolchain.py build python3 kivy fails [newbie]

### ISSUE THREAD

**Issue by RobertoD91** [kivy/kivy-ios#418]
Hi, i have this issues with macos 10.15.2, xcode 11.3, python 3.7.6 and 2.7.17 (homebrew version)

Any suggestion?

```
MYUSER@MYHOSTNAME:~/Desktop/git/kivy-ios$ python3 toolchain.py build python3 kivy
toolchain.py:93: DeprecationWarning: ChromeDownloader style of invoking requests is deprecated. Use newer urlopen functions/methods
  urlretrieve = ChromeDownloader().retrieve
[INFO    ] Building with 4 processes, where supported
[INFO    ] Want to build ['python3', 'kivy']
[INFO    ] Loaded recipe python3 (depends of ['hostpython3', 'libffi', 'openssl'], optional are [])
[INFO    ] Loaded recipe kivy (depends of ['sdl2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'ios', 'pyobjus', 'python'], optional are [])
[INFO    ] Loaded recipe hostpython3 (depends of [], optional are ['openssl'])
[INFO    ] Loaded recipe libffi (depends of [], optional are [])
[INFO    ] Loaded recipe openssl (depends of [], optional are [])
[INFO    ] Loaded recipe sdl2 (depends of [], optional are [])
[INFO    ] Loaded recipe sdl2_image (depends of ['sdl2'], optional are [])
[INFO    ] Loaded recipe sdl2_mixer (depends of ['sdl2'], optional are [])
[INFO    ] Loaded recipe sdl2_ttf (depends of ['sdl2', 'freetype'], optional are [])
[INFO    ] Loaded recipe ios (depends of ['python'], optional are [])
[INFO    ] Loaded recipe pyobjus (depends of ['python'], optional are [])
[INFO    ] Loaded recipe python (depends of ['python3'], optional are [])
[INFO    ] Loaded recipe freetype (depends of [], optional are [])
[INFO    ] Build order is ['freetype', 'libffi', 'openssl', 'sdl2', 'hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'python', 'ios', 'pyobjus', 'kivy']
[INFO    ] Recipe order is ['freetype', 'libffi', 'openssl', 'sdl2', 'hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'ios', 'pyobjus', 'kivy']
[INFO    ] Include dir added: {arch.arch}/freetype
[INFO    ] Include dir added: {arch.arch}/ffi
[INFO    ] Include dir added: {arch.arch}/openssl
[INFO    ] Include dir added: common/sdl2
[INFO    ] Global: hostpython located at /Users/MYUSER/Desktop/git/kivy-ios/dist/hostpython3/bin/python
[INFO    ] Global: hostpgen located at /Users/MYUSER/Desktop/git/kivy-ios/dist/hostpython3/bin/pgen
[INFO    ] Include dir added: common/sdl2_image
[INFO    ] Include dir added: common/sdl2_mixer
[INFO    ] Include dir added: common/sdl2_ttf
[DEBUG   ] Cached result: Download freetype. Ignoring
[DEBUG   ] Cached result: Extract freetype. Ignoring
[DEBUG   ] Cached result: Build_all freetype. Ignoring
[DEBUG   ] Cached result: Download libffi. Ignoring
[DEBUG   ] Cached result: Extract libffi. Ignoring
[DEBUG   ] Cached result: Build_all libffi. Ignoring
[DEBUG   ] Cached result: Download openssl. Ignoring
[DEBUG   ] Cached result: Extract openssl. Ignoring
[DEBUG   ] Cached result: Build_all openssl. Ignoring
[DEBUG   ] Cached result: Download sdl2. Ignoring
[DEBUG   ] Cached result: Extract sdl2. Ignoring
[DEBUG   ] Cached result: Build_all sdl2. Ignoring
[DEBUG   ] Cached result: Download hostpython3. Ignoring
[DEBUG   ] Cached result: Extract hostpython3. Ignoring
[DEBUG   ] Cached result: Build_all hostpython3. Ignoring
[DEBUG   ] Cached result: Download sdl2_image. Ignoring
[DEBUG   ] Cached result: Extract sdl2_image. Ignoring
[DEBUG   ] Cached result: Build_all sdl2_image. Ignoring
[DEBUG   ] Cached result: Download sdl2_mixer. Ignoring
[DEBUG   ] Cached result: Extract sdl2_mixer. Ignoring
[DEBUG   ] Cached result: Build_all sdl2_mixer. Ignoring
[DEBUG   ] Cached result: Download sdl2_ttf. Ignoring
[DEBUG   ] Cached result: Extract sdl2_ttf. Ignoring
[DEBUG   ] Cached result: Build_all sdl2_ttf. Ignoring
[DEBUG   ] Cached result: Download python3. Ignoring
[DEBUG   ] Cached result: Extract python3. Ignoring
[DEBUG   ] Cached result: Build_all python3. Ignoring
[DEBUG   ] Cached result: Download ios. Ignoring
[DEBUG   ] Cached result: Extract ios. Ignoring
[INFO    ] Build_all ios
[INFO    ] Build ios for x86_64, arm64 (filtered)
[INFO    ] Build ios
[WARNING ] ios build for x86_64 has been incomplete
[WARNING ] Warning: deleting the build and restarting.
[INFO    ] Prebuild ios for x86_64
[DEBUG   ] Invoking prebuild_x86_64
[INFO    ] Build ios for x86_64
[INFO    ] CC and CXX will not use ccache
[INFO    ] Cythonize ios.pyx
[INFO    ] Running Shell: /Users/MYUSER/Desktop/git/kivy-ios/tools/cythonize.py ('ios.pyx',) {'_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[DEBUG   ] ('-- cythonize', ['/Users/MYUSER/Desktop/git/kivy-ios/tools/cythonize.py', 'ios.pyx'])
[DEBUG   ] ('cythonize:', 'ios.pyx')
[DEBUG   ] Traceback (most recent call last):
[DEBUG   ]   File "/Users/MYUSER/Desktop/git/kivy-ios/tools/cythonize.py", line 55, in <module>
[DEBUG   ]     do(fn)
[DEBUG   ]   File "/Users/MYUSER/Desktop/git/kivy-ios/tools/cythonize.py", line 30, in do
[DEBUG   ]     subprocess.Popen([cython, fn], env=os.environ).communicate()
[DEBUG   ]   File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
[DEBUG   ]     errread, errwrite)
[DEBUG   ]   File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
[DEBUG   ]     raise child_exception
[DEBUG   ] OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "toolchain.py", line 1568, in <module>
    ToolchainCL()
  File "toolchain.py", line 1281, in __init__
    getattr(self, args.command)()
  File "toolchain.py", line 1322, in build
    build_recipes(args.recipe, ctx)
  File "toolchain.py", line 1158, in build_recipes
    recipe.execute()
  File "/Users/MYUSER/Desktop/git/kivy-ios/toolchain.py", line 729, in execute
    self.build_all()
  File "/Users/MYUSER/Desktop/git/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/MYUSER/Desktop/git/kivy-ios/toolchain.py", line 837, in build_all
    self.build(arch)
  File "/Users/MYUSER/Desktop/git/kivy-ios/toolchain.py", line 84, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/MYUSER/Desktop/git/kivy-ios/toolchain.py", line 811, in build
    self.build_arch(arch)
  File "/Users/MYUSER/Desktop/git/kivy-ios/toolchain.py", line 1110, in build_arch
    self.cythonize_build()
  File "/Users/MYUSER/Desktop/git/kivy-ios/toolchain.py", line 1082, in cythonize_build
    self.cythonize_file(join(root, filename))
  File "/Users/MYUSER/Desktop/git/kivy-ios/toolchain.py", line 1074, in cythonize_file
    shprint(cmd, filename)
  File "/Users/MYUSER/Desktop/git/kivy-ios/toolchain.py", line 67, in shprint
    for line in cmd:
  File "tools/external/sh.py", line 565, in next
    self.wait()
  File "tools/external/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "tools/external/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/Users/MYUSER/Desktop/git/kivy-ios/tools/cythonize.py ios.pyx'

  STDOUT:
('-- cythonize', ['/Users/MYUSER/Desktop/git/kivy-ios/tools/cythonize.py', 'ios.pyx'])
('cythonize:', 'ios.pyx')
Traceback (most recent call last):
  File "/Users/MYUSER/Desktop/git/kivy-ios/tools/cythonize.py", line 55, in <module>
    do(fn)
  File "/Users/MYUSER/Desktop/git/kivy-ios/tools/cythonize.py", line 30, in do
    subprocess.Popen([cython, fn], env=os.environ).communicate()
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such fi... (16 more, please see e.stdout)

  STDERR:

MYUSER@MYHOSTNAME:~/Desktop/git/kivy-ios$ 
```

**Comment by RobertoD91** [comment]
tested also with xcode 10.3, no change

**Comment by RobertoD91** [comment]
Wrong version of Cython, as written in the documentation, a specific version must be installed

```pip install Cython==0.29.10```

**Comment by fire17** [comment]
OMG THIS SAVED ME PLEASE UPDATE THE README TO STATE 29.10 INSTEAD OF 28.1 THANK YOU!!!!!!!!!!
