### ISSUE TITLE
unable to download sdl2 in fresh build -- their HTTPS is broken

### ISSUE THREAD

**Issue by s1113950** [kivy/kivy-ios#502]
**Versions**

* Python : 3.7.7
* MacOS version : Catalina 10.15.3
* XCode Version : 2373
* Cython version : 0.29.17

**Describe the bug**
Unable to download sdl2 because "This site can't provide a secure connection"; their https setup is broken. I went to https://hg.libsdl.org/ in Chrome and got the familiar error:
```
This site can’t provide a secure connection
hg.libsdl.org sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

**To Reproduce**
```
python3 -m venv venv
. venv/bin/activate
pip install kivy-ios Cython==0.29.17
toolchain build python3 kivy
```

**Expected behavior**
Able to build an app from scratch.
I suppose we could wait for their site to get fixed but it would be even better if there was a way to get sdl2 without hitting that site.

**Logs**
```
[INFO    ] Install openssl
[DEBUG   ] New State: openssl.install at 2020-05-18 03:37:29.509176
[DEBUG   ] New State: openssl.build_all at 2020-05-18 03:37:29.510241
[INFO    ] Download sdl2
[INFO    ] Downloading https://hg.libsdl.org/SDL/archive/7cc4fc886d9e.tar.gz
[WARNING ] Download failed. Retrying in 1 second...
[WARNING ] Download failed. Retrying in 1 second...
[WARNING ] Download failed. Retrying in 1 second...
[WARNING ] Download failed. Retrying in 1 second...
[ERROR   ] Max download attempts reached: 5
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1758, in open
    return getattr(self, name)(url)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1967, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1916, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1422, in connect
    server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)
```

**Comment by AndreMiras** [comment]
You must be missing some root certs at system level, because I get correct SSL cert here.
Debug it by checking the cert:
![image](https://user-images.githubusercontent.com/24973/82184234-99988b80-98e7-11ea-8021-1340a0491594.png)

**Comment by s1113950** [comment]
Possibly! I checked https://hg.libsdl.org/ and that website works now though so I'll close this ticket.
