### ISSUE TITLE
Have pil in my spec file, did "from PIL import Image" on my py file, and still get the error:

### ISSUE THREAD

**Issue by darapich007** [kivy/kivy-ios#511]
Have pil in my spec file, did "from PIL import Image" on my py file, and still get the error:
(buildozer 0.33 with Python3)

Traceback (most recent call last):
    File "/home/suporte/Desktop/Mobile/Vistorias/.buildozer/android/app/main.py", line 84, in <module>
    File "/home/suporte/Desktop/Mobile/Vistorias/.buildozer/android/platform/build/dists/frvistorias/private/lib/python2.7/site-packages/PIL/Image.py", line 56, in <module>
ImportError: dlopen failed: "/data/data/ind.frtech.car.frvistorias/files/app/lib/python2.7/site-packages/PIL/_imaging.so" is 64-bit instead of 32-bit

@inclement that's the reason I need pillow so badly hahaha

_Originally posted by @dfrison01 in https://github.com/kivy/python-for-android/issues/1816#issuecomment-318183890_

**Comment by Zen-CODE** [comment]
Python 2 is no longer supported. Please retry with Python 3 and recreate the issue if the problem persists. Thanks.
