### ISSUE TITLE
toolchain build failed - getting error

### ISSUE THREAD

**Issue by gargsaar** [kivy/kivy-ios#515]
Hi, getting the below error on running toolchain build python3 kivy.

```
(sg-venv-kivy) sarthakgarg@Sarthaks-MacBook-Pro AgeTest_V2 % sudo toolchain build python3 kivy
Password:
[INFO    ] Building with 8 processes, where supported
[INFO    ] Want to build ['python3', 'kivy']
[INFO    ] Loaded recipe python3 (depends of ['hostpython3', 'libffi', 'openssl'], optional are [])
[INFO    ] Loaded recipe kivy (depends of ['sdl2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'ios', 'pyobjus', 'python', 'host_setuptools3'], optional are [])
[INFO    ] Loaded recipe hostpython3 (depends of ['hostlibffi', 'hostopenssl'], optional are [])
[INFO    ] Loaded recipe libffi (depends of [], optional are [])
[INFO    ] Loaded recipe openssl (depends of [], optional are [])
[INFO    ] Loaded recipe sdl2 (depends of [], optional are [])
[INFO    ] Loaded recipe sdl2_image (depends of ['sdl2'], optional are [])
[INFO    ] Loaded recipe sdl2_mixer (depends of ['sdl2'], optional are [])
[INFO    ] Loaded recipe sdl2_ttf (depends of ['sdl2', 'freetype'], optional are [])
[INFO    ] Loaded recipe ios (depends of ['python'], optional are [])
[INFO    ] Loaded recipe pyobjus (depends of ['python'], optional are [])
[INFO    ] Loaded recipe python (depends of ['python3'], optional are [])
[INFO    ] Loaded recipe host_setuptools3 (depends of ['openssl', 'hostpython3'], optional are [])
[INFO    ] Loaded recipe hostlibffi (depends of [], optional are [])
[INFO    ] Loaded recipe hostopenssl (depends of [], optional are [])
[INFO    ] Loaded recipe freetype (depends of [], optional are [])
[INFO    ] Build order is ['freetype', 'hostlibffi', 'hostopenssl', 'libffi', 'openssl', 'sdl2', 'hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'host_setuptools3', 'python3', 'python', 'ios', 'pyobjus', 'kivy']
[INFO    ] Recipe order is ['freetype', 'hostlibffi', 'hostopenssl', 'libffi', 'openssl', 'sdl2', 'hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'host_setuptools3', 'python3', 'ios', 'pyobjus', 'kivy']
[INFO    ] Include dir added: {arch.arch}/freetype
[INFO    ] Include dir added: {arch.arch}/hostlibffi
[INFO    ] Include dir added: {arch.arch}/ffi
[INFO    ] Include dir added: {arch.arch}/openssl
[INFO    ] Include dir added: common/sdl2
[INFO    ] Global: hostpython located at /Users/sarthakgarg/Desktop/Repo/PYTHON/Kivy_Projects/DEPLOY/AgeTest_V2/dist/hostpython3/bin/python
[INFO    ] Global: hostpgen located at /Users/sarthakgarg/Desktop/Repo/PYTHON/Kivy_Projects/DEPLOY/AgeTest_V2/dist/hostpython3/bin/pgen
................
[DEBUG   ] Invoking postbuild_x86_64
[DEBUG   ] New State: hostopenssl.build.x86_64 at 2020-06-12 12:57:26.073300
[INFO    ] Install include files for hostopenssl
[INFO    ] Install_include hostopenssl
[DEBUG   ] New State: hostopenssl.install_include at 2020-06-12 12:57:26.074491
[INFO    ] Install frameworks for hostopenssl
[INFO    ] Install_frameworks hostopenssl
[DEBUG   ] New State: hostopenssl.install_frameworks at 2020-06-12 12:57:26.075926
[INFO    ] Install sources for hostopenssl
[INFO    ] Install_sources hostopenssl
[DEBUG   ] New State: hostopenssl.install_sources at 2020-06-12 12:57:26.077370
[INFO    ] Install python deps for hostopenssl
[INFO    ] Install_python_deps hostopenssl
[DEBUG   ] New State: hostopenssl.install_python_deps at 2020-06-12 12:57:26.078542
[INFO    ] Install hostopenssl
[DEBUG   ] New State: hostopenssl.build_all at 2020-06-12 12:57:26.267822
[INFO    ] Download libffi
[INFO    ] Downloading https://www.mirrorservice.org/sites/sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
Traceback (most recent call last):
  File "/Users/sarthakgarg/sg-venv/sg-venv-kivy/bin/toolchain", line 8, in <module>
    sys.exit(main())
  File "/Users/sarthakgarg/sg-venv/sg-venv-kivy/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 1497, in main
    ToolchainCL()
  File "/Users/sarthakgarg/sg-venv/sg-venv-kivy/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 1270, in __init__
    getattr(self, args.command)()
  File "/Users/sarthakgarg/sg-venv/sg-venv-kivy/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 1323, in build
    build_recipes(args.recipe, ctx)
  File "/Users/sarthakgarg/sg-venv/sg-venv-kivy/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 1121, in build_recipes
    recipe.execute()
  File "/Users/sarthakgarg/sg-venv/sg-venv-kivy/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 698, in execute
    self.download()
  File "/Users/sarthakgarg/sg-venv/sg-venv-kivy/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 85, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/sarthakgarg/sg-venv/sg-venv-kivy/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 733, in download
    self.download_file(self.url.format(version=self.version), fn)
  File "/Users/sarthakgarg/sg-venv/sg-venv-kivy/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 474, in download_file
    urlretrieve(url, filename, report_hook)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1819, in retrieve
    block = fp.read(bs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
ValueError: read of closed file
(sg-venv-kivy) sarthakgarg@Sarthaks-MacBook-Pro AgeTest_V2 % 
```

**Comment by AndreMiras** [comment]
This is because the libffi download is down or invalid, maybe try with another version or fix the link and make a PR.
```
curl https://www.mirrorservice.org/sites/sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
<!DOCTYPE html>
<html>
 <head>
  <title>The UK Mirror Service - Unavailable</title>
<script type="text/javascript">var _gaq = _gaq || []; _gaq.push(['_setAccount', 'UA-2248758-1']); _gaq.push(['_setDomainName', 'mirrorservice.org']); _gaq.push(['_trackPageview']); (function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })();</script><link rel="stylesheet" type="text/css" media="screen" href="/style.css"> </head>
 <body>

<div id="header">
<a href="/"><img src="/ukms-kent1.png" alt="UK Mirror Service"></a>
</div>

<div id="content">

<div id="content_left">
 <h1>Service unavailable</h1>
 <p>You're seeing this message because our service is currently unavailable from the Internet. This is likely due to a problem beyond our immediate control, but we will still be doing everything we can to restore the service. If the problem persists or you need further information please <a href="mailto:help@mirrorservice.org">contact us</a> so we that can look in to it.</p>
 <p>Our Twitter feed on the right may give more current information.</p>
</div>

<div id="content_right">
<a class="twitter-timeline" href="https://twitter.com/UKMirrorService" data-widget-id="486509614817488897">Tweets by @UKMirrorService</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

</div>

<div class="clear"></div>

<div id="footer">
        <div id="footer_left">
                <a href="http://www.cs.kent.ac.uk/" onClick="javascript:urchinTracker('/outgoing/kent/cs/bottom');"><img src="/CompLab-thin.jpg" alt="University of Kent Computing"></a>
        </div>
        <div id="footer_right">
                <p>Comments or Questions: <a href="mailto:help@mirrorservice.org">help@mirrorservice.org</a></p>
                <a href="https://twitter.com/UKMirrorService" class="twitter-follow-button" data-show-count="false">Follow @UKMirrorService</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                <p style="font-size: xx-small">Bishnet</p>
        </div>
</div>

 </body>
</html>
```

**Comment by AndreMiras** [comment]
Give that one a try: https://github.com/kivy/kivy-ios/pull/516
