### ISSUE TITLE
"Toolchain pip install" not installing a pure python package (kivymd)

### ISSUE THREAD

**Issue by RustyRyan98** [kivy/kivy-ios#519]
Im trying to compile an app that using kivymd which is a pure python package but everytime i run the "python3 toolchain.py pip install kivymd" i get an error when its collecting the package for kivy . ive been strugging with this for a while. i would appreciate if anyone could assist me. Thank you. 

Below is my error

```
(venv) temitayoadefemi@Temitayos-MacBook-Air kivy-ios % python3 toolchain.py pip install kivymd
[INFO    ] Include dir added: {arch.arch}/freetype
[INFO    ] Include dir added: {arch.arch}/hostlibffi
[INFO    ] Global: hostpython located at /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/python
[INFO    ] Global: hostpgen located at /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/pgen
[INFO    ] Include dir added: {arch.arch}/ffi
[INFO    ] Include dir added: {arch.arch}/openssl
[INFO    ] Include dir added: common/sdl2
[INFO    ] Include dir added: common/sdl2_image
[INFO    ] Include dir added: common/sdl2_mixer
[INFO    ] Include dir added: common/sdl2_ttf
[ERROR   ] Executing pip with: ['install', '--isolated', '--ignore-installed', '--prefix', '/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3', 'kivymd']
[INFO    ] Running Shell: /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/pip3 ('install', '--isolated', '--ignore-installed', '--prefix', '/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3', 'kivymd') {'_env': {'CC': '/bin/false', 'CXX': '/bin/false', 'PYTHONPATH': '/Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3/lib/python3.8/site-packages', 'PYTHONOPTIMIZE': '2'}, '_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[DEBUG   ] Collecting kivymd
[DEBUG   ]   Using cached https://files.pythonhosted.org/packages/c4/4e/f33085dab6420009fefc214cb3f8fc88ecd9d9e766976aa14f93b033a53a/kivymd-0.104.1-py3-none-any.whl
[DEBUG   ] Collecting pillow (from kivymd)
[DEBUG   ]   Using cached https://files.pythonhosted.org/packages/20/20/a0f9f20469aae7017a578fdc4c55ea18f7c8911d2d10668687f95748442b/Pillow-7.1.2-cp38-cp38-macosx_10_10_x86_64.whl
[DEBUG   ] Collecting kivy (from kivymd)
[DEBUG   ]   Using cached https://files.pythonhosted.org/packages/1b/4d/3f8a720f561dc1eabe036c0d87c6ce9d02823275391265538e606f45e37a/Kivy-1.11.1.tar.gz
[DEBUG   ]     ERROR: Command errored out with exit status 1:
[DEBUG   ]      command: /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-o1eeqd3p/kivy/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-o1eeqd3p/kivy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
[DEBUG   ]          cwd: /private/tmp/pip-install-o1eeqd3p/kivy/
[DEBUG   ]     Complete output (119 lines):
[DEBUG   ]     fatal: not a git repository (or any of the parent directories): .git
[DEBUG   ]      Traceback (most recent call last):
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
[DEBUG   ]          yield saved
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
[DEBUG   ]          yield
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
[DEBUG   ]          _execfile(setup_script, ns)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
[DEBUG   ]          exec(code, globals, locals)
[DEBUG   ]        File "/tmp/easy_install-dj4i18zv/Cython-0.29.10/setup.py", line 193, in <module>
[DEBUG   ]          # now check if environ is changing the default values
[DEBUG   ]        File "/tmp/easy_install-dj4i18zv/Cython-0.29.10/setup.py", line 113, in compile_cython_modules
[DEBUG   ]          return ""
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/os.py", line 675, in __getitem__
[DEBUG   ]          raise KeyError(key) from None
[DEBUG   ]      KeyError: 'PATH'
[DEBUG   ]     
[DEBUG   ]      During handling of the above exception, another exception occurred:
[DEBUG   ]     
[DEBUG   ]      Traceback (most recent call last):
[DEBUG   ]        File "<string>", line 1, in <module>
[DEBUG   ]        File "/private/tmp/pip-install-o1eeqd3p/kivy/setup.py", line 1073, in <module>
[DEBUG   ]          setup(
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
[DEBUG   ]          _install_setup_requires(attrs)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
[DEBUG   ]          dist.fetch_build_eggs(dist.setup_requires)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
[DEBUG   ]          resolved_dists = pkg_resources.working_set.resolve(
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
[DEBUG   ]          dist = best[req.key] = env.best_match(
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
[DEBUG   ]          return self.obtain(req, installer)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
[DEBUG   ]          return installer(requirement)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
[DEBUG   ]          return cmd.easy_install(req)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
[DEBUG   ]          return self.install_item(spec, dist.location, tmpdir, deps)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
[DEBUG   ]          dists = self.install_eggs(spec, download, tmpdir)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
[DEBUG   ]          return self.build_and_install(setup_script, setup_base)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
[DEBUG   ]          self.run_setup(setup_script, setup_base, args)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
[DEBUG   ]          run_setup(setup_script, args)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
[DEBUG   ]          raise
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/contextlib.py", line 131, in __exit__
[DEBUG   ]          self.gen.throw(type, value, traceback)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
[DEBUG   ]          yield
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/contextlib.py", line 131, in __exit__
[DEBUG   ]          self.gen.throw(type, value, traceback)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
[DEBUG   ]          saved_exc.resume()
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
[DEBUG   ]          six.reraise(type, exc, self._tb)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
[DEBUG   ]          raise value.with_traceback(tb)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
[DEBUG   ]          yield saved
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
[DEBUG   ]          yield
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
[DEBUG   ]          _execfile(setup_script, ns)
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
[DEBUG   ]          exec(code, globals, locals)
[DEBUG   ]        File "/tmp/easy_install-dj4i18zv/Cython-0.29.10/setup.py", line 193, in <module>
[DEBUG   ]          # now check if environ is changing the default values
[DEBUG   ]        File "/tmp/easy_install-dj4i18zv/Cython-0.29.10/setup.py", line 113, in compile_cython_modules
[DEBUG   ]          return ""
[DEBUG   ]        File "/Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/lib/python3.8/os.py", line 675, in __getitem__
[DEBUG   ]          raise KeyError(key) from None
[DEBUG   ]      KeyError: 'PATH'
[DEBUG   ]     Using setuptools
[DEBUG   ]     User distribution detected, avoid portable command.
[DEBUG   ]     Using this graphics system: OpenGL ES 2
[DEBUG   ]     OSX framework used, force to x86_64 only
[DEBUG   ]     OSX ARCHFLAGS are: -arch x86_64
[DEBUG   ]     GStreamer framework not found, fallback on pkg-config
[DEBUG   ]     WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)
[DEBUG   ]     
[DEBUG   ]     b"Package 'gobject-2.0' requires 'libffi >= 3.0.0' but version of libffi is 2.1\n"
[DEBUG   ]     
[DEBUG   ]     Missing framework /Library/Frameworks/SDL2.framework
[DEBUG   ]     Missing framework /Library/Frameworks/SDL2_ttf.framework
[DEBUG   ]     Missing framework /Library/Frameworks/SDL2_image.framework
[DEBUG   ]     Missing framework /Library/Frameworks/SDL2_mixer.framework
[DEBUG   ]     SDL2 frameworks not found, fallback on pkg-config
[DEBUG   ]     SDL2 found via pkg-config
[DEBUG   ]     Xcode detected at b'/Applications/Xcode.app/Contents/Developer', and using OS X10.15 sdk
[DEBUG   ]     WARNING: A problem occurred while running pkg-config --libs --cflags pangoft2 (code 1)
[DEBUG   ]     
[DEBUG   ]     b"Package pangoft2 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `pangoft2.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'pangoft2' found\n"
[DEBUG   ]     
[DEBUG   ]     ERROR: Dependency for context.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for compiler.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for fbo.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for instructions.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for opengl.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for shader.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for texture.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for vbo.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for vertex.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for cgl.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
[DEBUG   ]     ERROR: Dependency for svg.pyx not resolved: config.pxi
[DEBUG   ]     ----------------------------------------
[DEBUG   ] ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[DEBUG   ] WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
[DEBUG   ] You should consider upgrading via the 'pip install --upgrade pip' command.
Exception in thread background thread for pid 7707:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/temitayoadefemi/Desktop/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 1662, in wrap
    fn(*args, **kwargs)
  File "/Users/temitayoadefemi/Desktop/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 2606, in background_thread
    handle_exit_code(exit_code)
  File "/Users/temitayoadefemi/Desktop/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 2304, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/temitayoadefemi/Desktop/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/pip3 install --isolated --ignore-installed --prefix /Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3 kivymd

  STDOUT:
Collecting kivymd
  Using cached https://files.pythonhosted.org/packages/c4/4e/f33085dab6420009fefc214cb3f8fc88ecd9d9e766976aa14f93b033a53a/kivymd-0.104.1-py3-none-any.whl
Collecting pillow (from kivymd)
  Using cached https://files.pythonhosted.org/packages/20/20/a0f9f20469aae7017a578fdc4c55ea18f7c8911d2d10668687f95748442b/Pillow-7.1.2-cp38-cp38-macosx_10_10_x86_64.whl
Collecting kivy (from kivymd)
  Using cached https://files.pythonhosted.org/packages/1b/4d/3f8a720f561dc1eabe036c0d87c6ce9d02823275391265538e606f45e37a/Kivy-1.11.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private... (9649 more, please see e.stdout)

  STDERR:


Traceback (most recent call last):
  File "toolchain.py", line 3, in <module>
    main()
  File "/Users/temitayoadefemi/Desktop/kivy-ios/kivy_ios/toolchain.py", line 1521, in main
    ToolchainCL()
  File "/Users/temitayoadefemi/Desktop/kivy-ios/kivy_ios/toolchain.py", line 1286, in __init__
    getattr(self, args.command)()
  File "/Users/temitayoadefemi/Desktop/kivy-ios/kivy_ios/toolchain.py", line 1480, in pip
    _pip(sys.argv[2:])
  File "/Users/temitayoadefemi/Desktop/kivy-ios/kivy_ios/toolchain.py", line 1181, in _pip
    shprint(pip_cmd, *args, _env=pip_env)
  File "/Users/temitayoadefemi/Desktop/kivy-ios/kivy_ios/toolchain.py", line 67, in shprint
    for line in cmd:
  File "/Users/temitayoadefemi/Desktop/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 925, in next
    self.wait()
  File "/Users/temitayoadefemi/Desktop/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 849, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/temitayoadefemi/Desktop/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/pip3 install --isolated --ignore-installed --prefix /Users/temitayoadefemi/Desktop/kivy-ios/dist/root/python3 kivymd

  STDOUT:
Collecting kivymd
  Using cached https://files.pythonhosted.org/packages/c4/4e/f33085dab6420009fefc214cb3f8fc88ecd9d9e766976aa14f93b033a53a/kivymd-0.104.1-py3-none-any.whl
Collecting pillow (from kivymd)
  Using cached https://files.pythonhosted.org/packages/20/20/a0f9f20469aae7017a578fdc4c55ea18f7c8911d2d10668687f95748442b/Pillow-7.1.2-cp38-cp38-macosx_10_10_x86_64.whl
Collecting kivy (from kivymd)
  Using cached https://files.pythonhosted.org/packages/1b/4d/3f8a720f561dc1eabe036c0d87c6ce9d02823275391265538e606f45e37a/Kivy-1.11.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/temitayoadefemi/Desktop/kivy-ios/dist/hostpython3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private... (9649 more, please see e.stdout)

  STDERR:

(venv) temitayoadefemi@Temitayos-MacBook-Air kivy-ios % 

```

**Comment by Zen-CODE** [comment]
KivyMD is not a pure python package. It depends on Kivy, which then has C/Cython dependencies. KivyMD is a separate and independent project, so not directly supported by Kivy-IOS. Strictly speaking, you should raise this issue on the KivyMD bug tracker, not here.

That being said, we want to help. What I would recommend is, instead of installing it and listing it as a dependency, clone the repo and include the source code in a "kivymd" subfolder, so it appears as a simple module. That should work? 

I'm going to close this ticket, but please feel free to continue the discussion here are re-open the ticket if you feel it necessary. It would be nice to confirm that you got it working and may light the way for others...

**Comment by misl6** [comment]
Sorry for commenting on an already closed issue.

@RustyRyan98 , PR #521 should have partially fixed your issue. I've encountered something similar this morning while doing some tests on a kivy_garden package.

Can you please retry to build your app by doing these steps (by using the #521 PR)?
- `toolchain build python3 kivy pillow`
- `toolchain pip install kivymd`

**Comment by RustyRyan98** [comment]
Thank you but it is still the same issue. i used to the two commands consecutively

**Comment by Zen-CODE** [comment]
@RustyRyan98 Please can you post the latest logs? They should contain python3.8 and not 3.7?

**Comment by Zen-CODE** [comment]
@Julian-Code14  Without telling us anything about the OS, the steps you followed etc, this is not useful. I suggest you ask on the forums or discord as no one will see this on a closed, stale ticker. Thanks
