### ISSUE TITLE
Pillow recipe is broken

### ISSUE THREAD

**Issue by RustyRyan98** [kivy/kivy-ios#540]
Im successfully running my on my IOS Simulator but when i try to run it on my phone i get this error 

```

Got dlopen error on Foundation: dlopen(/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found
Got fallback dlopen error on Foundation: dlopen(/Groups/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation, 1): image not found
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/setuptools-40.9.0-py3.8.egg/pkg_resources/__init__.py", line 1210, in get_cache_path
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/setuptools-40.9.0-py3.8.egg/pkg_resources/__init__.py", line 3172, in _bypass_ensure_directory
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/setuptools-40.9.0-py3.8.egg/pkg_resources/__init__.py", line 3172, in _bypass_ensure_directory
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/setuptools-40.9.0-py3.8.egg/pkg_resources/__init__.py", line 3172, in _bypass_ensure_directory
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/setuptools-40.9.0-py3.8.egg/pkg_resources/__init__.py", line 3174, in _bypass_ensure_directory
 PermissionError: [Errno 1] Operation not permitted: '/private/var/mobile/Containers/Data/Application/7FA91DAE-D80E-47B0-9830-755A50C1357B/.cache'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/temitayoadefemi/Desktop/kivy-ios/merri-ios/YourApp/main.py", line 47, in <module>
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
   File "<frozen zipimport>", line 259, in load_module
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/Pillow-6.1.0-py3.8-macosx-10.15-x86_64.egg/PIL/Image.py", line 95, in <module>
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
   File "<frozen zipimport>", line 259, in load_module
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/Pillow-6.1.0-py3.8-macosx-10.15-x86_64.egg/PIL/_imaging.py", line 7, in <module>
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/Pillow-6.1.0-py3.8-macosx-10.15-x86_64.egg/PIL/_imaging.py", line 4, in __bootstrap__
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/setuptools-40.9.0-py3.8.egg/pkg_resources/__init__.py", line 1144, in resource_filename
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/setuptools-40.9.0-py3.8.egg/pkg_resources/__init__.py", line 1734, in get_resource_filename
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/setuptools-40.9.0-py3.8.egg/pkg_resources/__init__.py", line 1763, in _extract_resource
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/setuptools-40.9.0-py3.8.egg/pkg_resources/__init__.py", line 1212, in get_cache_path
   File "/private/var/containers/Bundle/Application/FDB7E8AB-ED7B-434A-B47A-46460138B09E/merri.app/lib/python3.8/site-packages/setuptools-40.9.0-py3.8.egg/pkg_resources/__init__.py", line 1192, in extraction_error
 pkg_resources.ExtractionError: Can't extract file(s) to egg cache
 
 The following error occurred while trying to extract file(s)
 to the Python egg cache:
 
   [Errno 1] Operation not permitted: '/private/var/mobile/Containers/Data/Application/7FA91DAE-D80E-47B0-9830-755A50C1357B/.cache'
 
 The Python egg cache directory is currently set to:
 
   /private/var/mobile/Containers/Data/Application/7FA91DAE-D80E-47B0-9830-755A50C1357B/.cache/Python-Eggs
 
 Perhaps your account does not have write access to this directory?
 You can change the cache directory by setting the PYTHON_EGG_CACHE
 environment variable to point to an accessible directory.
 
2020-08-08 23:55:48.141157+0100 merri[3193:672567] Application quit abnormally!
2020-08-08 23:55:48.169612+0100 merri[3193:672567] Leaving

```

Please i would appreciate assistance

**Comment by Zen-CODE** [comment]
That a permissions error more that a pillow issue? Have you given your application all the access it requires via the `Settings` on your device?

**Comment by Zen-CODE** [comment]
It also occurs to me that this might be a version issue? What version of iOS is on your phone vs. running on the simulator? Please post back with your findings...

**Comment by Zen-CODE** [comment]
This does not seem like a pillow issue, more like a permissions setting in XCode. Closing the issue due to lack of feedback.

 @RustyRyan98. Please feel free to re-open this issue if you have fresh information. Thanks.

**Comment by Cheaterman** [comment]
Hehehe, as much as you're right @Zen-CODE, it would be very useful indeed to provide a solution :-) I'm facing the same issue right now and I'm fairly clueless with the whole Apple ecosystem, no idea how/where to edit app permissions... can't seem to find it in project/build target settings. Interestingly, the path (similar to the above) includes `/private` and some `/Application/an-uuid4`, so I expected these files to belong to the application and be writable by it? :confused:

**Comment by Blaygor** [comment]
Hey, I fixed this Python egg issue for Pillow using this code:
 Put this up the top of your main.py, before importing kivy:

```
import os
xyz = os.path.join('~', 'Documents', 'your_directory')
os.environ['PYTHON_EGG_CACHE'] = os.path.expanduser(xyz)
```
