### ISSUE TITLE
Kivy App gives “Singular Matrix” error after build

### ISSUE THREAD

**Issue by frank-roesler** [kivy/kivy-ios#548]
**Versions**

* Python : 3.8
* MacOS version : 10.15.6
* XCode Version : 11.6
* Cython version : 0.29.21

**Describe the bug**
I've encountered a strange issue with my self-written Kivy app, that I haven't found anywhere online so far.
The issue is as follows. My code involves matrix inversion with numpy.linalg and works absolutely fine when I run it on my computer. But as soon as I build the app with the toolchain and run it either on a simulated iPhone in XCode, or on my personal phone, I get a `LinAlgError("Singular matrix") numpy.linalg.LinAlgError: Singular matrix` error, even though the matrix in question is absolutely benign, has no extremely large entries and its determinant is not particularly large or small.  
Even computing the determinant of a simple 2x2 matrix with numpy.linalg gives completely false results after build.  
If instead of using `numpy.linalg.det(A)` I compute the determinant by hand (`A[0,0]*A[1,1] - A[0,1]*A[1,0]`), the results I get are correct. The same is true for matrix inversion. 

**To Reproduce**
```
toolchain build kivy
toolchain build python3
toolchain build numpy
```

Here is a minimal working example of an app that reproduces the error:
```
import numpy as np
from kivy.app import App
from kivy.uix.widget import Widget

np.random.seed(42)


class Test(Widget):
    A = 10*np.random.rand(2,2)
    b = 10*np.random.rand(2,1)
    print('A =',A)
    print('b =',b)
    print('A[0,0]*A[1,1] - A[0,1]*A[1,0] =', A[0,0]*A[1,1] - A[0,1]*A[1,0])
    print('-'*50)
    print('det(A) =',np.linalg.det(A))
    print('inv(A) =',np.linalg.inv(A))
    print('inv(A)*b =',np.linalg.solve(A,b))


class TestApp(App):
    def build(self):
        return Test()


if __name__ == '__main__':
    TestApp().run()
```
Running this code in PyCharm simply gives the output
```
A = [[3.74540119 9.50714306]
 [7.31993942 5.98658484]]
b = [[1.5601864]
 [1.5599452]]
A[0,0]*A[1,1] - A[0,1]*A[1,0] = -47.16954928653505
--------------------------------------------------
det(A) = -47.16954928653505
inv(A) = [[-0.1269163   0.20155255]
 [ 0.15518358 -0.07940295]]
inv(A)*b = [[0.11639785]
 [0.11825106]]
```
However, building the app with `toolchain create...` and running it in XCode produces the following.
```
A = [[3.74540119 9.50714306]
 [7.31993942 5.98658484]]
b = [[1.5601864]
 [1.5599452]]
A[0,0]*A[1,1] - A[0,1]*A[1,0] = -47.16954928653505
--------------------------------------------------
 /Users/frankroesler/Library/Developer/CoreSimulator/Devices/F17C9E34-4D4D-444D-B196-FF41594223A2/data/Containers/Bundle/Application/CBF306FA-3D5B-47EA-8B3B-B35381B47BB4/test.app/lib/python3.8/site-packages/numpy/linalg/linalg.py:2093: RuntimeWarning: overflow encountered in det
   r = _umath_linalg.det(a, signature=signature)
det(A) = -inf
 Traceback (most recent call last):
   File "/Users/frankroesler/Kivy_test/test-ios/YourApp/main.py", line 8, in <module>
   File "/Users/frankroesler/Kivy_test/test-ios/YourApp/main.py", line 16, in Test
   File "/Users/frankroesler/Library/Developer/CoreSimulator/Devices/F17C9E34-4D4D-444D-B196-FF41594223A2/data/Containers/Bundle/Application/CBF306FA-3D5B-47EA-8B3B-B35381B47BB4/test.app/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 551, in inv
     ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
   File "/Users/frankroesler/Library/Developer/CoreSimulator/Devices/F17C9E34-4D4D-444D-B196-FF41594223A2/data/Containers/Bundle/Application/CBF306FA-3D5B-47EA-8B3B-B35381B47BB4/test.app/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_singular
     raise LinAlgError("Singular matrix")
 numpy.linalg.LinAlgError: Singular matrix
2020-08-31 13:30:24.667516+0100 test[82053:4261734] Application quit abnormally!
2020-08-31 13:30:24.691212+0100 test[82053:4261734] Leaving
```

**Expected behavior**
I expect that after building the app, the commands `numpy.linalg.det(A)` and `A[0,0]*A[1,1] - A[0,1]*A[1,0]` should yield the same result for any 2x2 matrix A.

**Comment by frank-roesler** [comment]
Here is a minimal working example that reproduces the error:
```
import numpy as np
from kivy.app import App
from kivy.uix.widget import Widget


class Test(Widget):
    A = 10*np.random.rand(2,2)
    b = 10*np.random.rand(2,1)
    print(A)
    print(b)
    print('-'*50)
    print('det(A) =',np.linalg.det(A))
    print('inv(A) =',np.linalg.inv(A))
    print('inv(A)*b =',np.linalg.solve(A,b))


class TestApp(App):
    def build(self):
        return Test()


if __name__ == '__main__':
    TestApp().run()
```

**Comment by Zen-CODE** [comment]
Which exact version of `numpy` are you using locally? The kivy-ios version is currently 1.16.4. I suspect this is version issue. Please could you try deploying 1.16.4 locally and see if that produces the same error?

Thanks

**Comment by Zen-CODE** [comment]
@frank-roesler Any feedback on the above?

**Comment by misl6** [comment]
Closing due to inactivity, feel free to re-open if it still needed.
