### ISSUE TITLE
Patching error on IOS

### ISSUE THREAD

**Issue by garantor** [kivy/kivy-ios#550]
python 3.7.3
macOS Catalina 10:15:3
xcode: 11.7

each time i run buildozer ios debug i get this error, or maybe am doing it the wrong way.

I attached some part of the log here

```[DEBUG   ] x Python-3.7.3/Python/dynload_win.c
[DEBUG   ] x Python-3.7.3/Python/errors.c
[DEBUG   ] x Python-3.7.3/Python/dynamic_annotations.c
[DEBUG   ] x Python-3.7.3/Python/clinic/
[DEBUG   ] x Python-3.7.3/Python/clinic/_warnings.c.h
[DEBUG   ] x Python-3.7.3/Python/clinic/bltinmodule.c.h
[DEBUG   ] x Python-3.7.3/Python/clinic/sysmodule.c.h
[DEBUG   ] x Python-3.7.3/Python/clinic/context.c.h
[DEBUG   ] x Python-3.7.3/Python/clinic/traceback.c.h
[DEBUG   ] x Python-3.7.3/Python/clinic/marshal.c.h
[DEBUG   ] x Python-3.7.3/Python/clinic/import.c.h
[DEBUG   ] x Python-3.7.3/Python/formatter_unicode.c
[DEBUG   ] x Python-3.7.3/Python/bltinmodule.c
[DEBUG   ] x Python-3.7.3/Python/pyctype.c
[DEBUG   ] x Python-3.7.3/Python/symtable.c
[DEBUG   ] x Python-3.7.3/Python/traceback.c
[DEBUG   ] x Python-3.7.3/Python/dynload_dl.c
[DEBUG   ] x Python-3.7.3/Python/opcode_targets.h
[DEBUG   ] x Python-3.7.3/Python/getcompiler.c
[DEBUG   ] x Python-3.7.3/Python/marshal.c
[DEBUG   ] x Python-3.7.3/Python/frozen.c
[DEBUG   ] x Python-3.7.3/Python/bootstrap_hash.c
[DEBUG   ] x Python-3.7.3/Python/mystrtoul.c
[DEBUG   ] x Python-3.7.3/Python/pystrcmp.c
[DEBUG   ] x Python-3.7.3/Python/peephole.c
[DEBUG   ] x Python-3.7.3/Python/thread.c
[DEBUG   ] x Python-3.7.3/Python/pyfpe.c
[DEBUG   ] x Python-3.7.3/Python/graminit.c
[DEBUG   ] x Python-3.7.3/Python/context.c
[DEBUG   ] x Python-3.7.3/Python/ast_opt.c
[DEBUG   ] x Python-3.7.3/Python/fileutils.c
[DEBUG   ] x Python-3.7.3/Python/pyhash.c
[DEBUG   ] x Python-3.7.3/Python/thread_pthread.h
[DEBUG   ] x Python-3.7.3/Python/dup2.c
[DEBUG   ] x Python-3.7.3/Python/ceval_gil.h
[DEBUG   ] x Python-3.7.3/Python/ast.c
[DEBUG   ] x Python-3.7.3/Python/_warnings.c
[DEBUG   ] x Python-3.7.3/Python/compile.c
[DEBUG   ] x Python-3.7.3/Python/mysnprintf.c
[DEBUG   ] x Python-3.7.3/Python/makeopcodetargets.py
[DEBUG   ] x Python-3.7.3/Programs/
[DEBUG   ] x Python-3.7.3/Programs/_testembed.c
[DEBUG   ] x Python-3.7.3/Programs/README
[DEBUG   ] x Python-3.7.3/Programs/python.c
[DEBUG   ] x Python-3.7.3/Programs/_freeze_importlib.c
[DEBUG   ] x Python-3.7.3/Objects/
[DEBUG   ] x Python-3.7.3/Objects/dictobject.c
[DEBUG   ] x Python-3.7.3/Objects/dict-common.h
[DEBUG   ] x Python-3.7.3/Objects/exceptions.c
[DEBUG   ] x Python-3.7.3/Objects/funcobject.c
[DEBUG   ] x Python-3.7.3/Objects/capsule.c
[DEBUG   ] x Python-3.7.3/Objects/unicodetype_db.h
[DEBUG   ] x Python-3.7.3/Objects/boolobject.c
[DEBUG   ] x Python-3.7.3/Objects/fileobject.c
[DEBUG   ] x Python-3.7.3/Objects/longobject.c
[DEBUG   ] x Python-3.7.3/Objects/odictobject.c
[DEBUG   ] x Python-3.7.3/Objects/setobject.c
[DEBUG   ] x Python-3.7.3/Objects/weakrefobject.c
[DEBUG   ] x Python-3.7.3/Objects/memoryobject.c
[DEBUG   ] x Python-3.7.3/Objects/descrobject.c
[DEBUG   ] x Python-3.7.3/Objects/frameobject.c
[DEBUG   ] x Python-3.7.3/Objects/cellobject.c
[DEBUG   ] x Python-3.7.3/Objects/codeobject.c
[DEBUG   ] x Python-3.7.3/Objects/sliceobject.c
[DEBUG   ] x Python-3.7.3/Objects/classobject.c
[DEBUG   ] x Python-3.7.3/Objects/moduleobject.c
[DEBUG   ] x Python-3.7.3/Objects/enumobject.c
[DEBUG   ] x Python-3.7.3/Objects/rangeobject.c
[DEBUG   ] x Python-3.7.3/Objects/complexobject.c
[DEBUG   ] x Python-3.7.3/Objects/README
[DEBUG   ] x Python-3.7.3/Objects/iterobject.c
[DEBUG   ] x Python-3.7.3/Objects/call.c
[DEBUG   ] x Python-3.7.3/Objects/bytesobject.c
[DEBUG   ] x Python-3.7.3/Objects/unicodectype.c
[DEBUG   ] x Python-3.7.3/Objects/genobject.c
[DEBUG   ] x Python-3.7.3/Objects/stringlib/
[DEBUG   ] x Python-3.7.3/Objects/stringlib/ctype.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/count.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/eq.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/partition.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/unicodedefs.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/stringdefs.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/fastsearch.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/join.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/ucs2lib.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/find_max_char.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/unicode_format.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/ucs4lib.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/transmogrify.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/ucs1lib.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/replace.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/asciilib.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/localeutil.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/codecs.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/README.txt
[DEBUG   ] x Python-3.7.3/Objects/stringlib/undef.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/find.h
[DEBUG   ] x Python-3.7.3/Objects/stringlib/split.h
[DEBUG   ] x Python-3.7.3/Objects/unicodeobject.c
[DEBUG   ] x Python-3.7.3/Objects/listsort.txt
[DEBUG   ] x Python-3.7.3/Objects/accu.c
[DEBUG   ] x Python-3.7.3/Objects/structseq.c
[DEBUG   ] x Python-3.7.3/Objects/namespaceobject.c
[DEBUG   ] x Python-3.7.3/Objects/typeslots.py
[DEBUG   ] x Python-3.7.3/Objects/floatobject.c
[DEBUG   ] x Python-3.7.3/Objects/clinic/
[DEBUG   ] x Python-3.7.3/Objects/clinic/descrobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/unicodeobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/typeobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/listobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/complexobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/bytearrayobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/enumobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/bytesobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/floatobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/funcobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/longobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/dictobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/structseq.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/tupleobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/moduleobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/clinic/odictobject.c.h
[DEBUG   ] x Python-3.7.3/Objects/bytearrayobject.c
[DEBUG   ] x Python-3.7.3/Objects/typeobject.c
[DEBUG   ] x Python-3.7.3/Objects/lnotab_notes.txt
[DEBUG   ] x Python-3.7.3/Objects/methodobject.c
[DEBUG   ] x Python-3.7.3/Objects/tupleobject.c
[DEBUG   ] x Python-3.7.3/Objects/obmalloc.c
[DEBUG   ] x Python-3.7.3/Objects/object.c
[DEBUG   ] x Python-3.7.3/Objects/abstract.c
[DEBUG   ] x Python-3.7.3/Objects/listobject.c
[DEBUG   ] x Python-3.7.3/Objects/bytes_methods.c
[DEBUG   ] x Python-3.7.3/Objects/dictnotes.txt
[DEBUG   ] x Python-3.7.3/Objects/typeslots.inc
[INFO    ] Prebuild hostpython3 for x86_64
[INFO    ] Apply patch pyconfig_detection.patch
Traceback (most recent call last):
  File "toolchain.py", line 3, in <module>
    main()
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/toolchain.py", line 1511, in main
    ToolchainCL()
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/toolchain.py", line 1276, in __init__
    getattr(self, args.command)()
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/toolchain.py", line 1337, in build
    build_recipes(args.recipe, ctx)
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/toolchain.py", line 1127, in build_recipes
    recipe.execute()
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/toolchain.py", line 699, in execute
    self.build_all()
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/toolchain.py", line 73, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/toolchain.py", line 793, in build_all
    self.build(arch)
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/toolchain.py", line 73, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/toolchain.py", line 778, in build
    self.prebuild_arch(arch)
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/recipes/hostpython3/__init__.py", line 39, in prebuild_arch
    self.apply_patch("pyconfig_detection.patch")
  File "/Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/toolchain.py", line 545, in apply_patch
    sh.patch("-t", "-d", target_dir, "-p1", "-i", filename)
  File "/Users/afolabi/.local/share/virtualenvs/new_ios-rRJ0wE3V/lib/python3.7/site-packages/sh.py", line 1516, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/Users/afolabi/.local/share/virtualenvs/new_ios-rRJ0wE3V/lib/python3.7/site-packages/sh.py", line 780, in __init__
    self.wait()
  File "/Users/afolabi/.local/share/virtualenvs/new_ios-rRJ0wE3V/lib/python3.7/site-packages/sh.py", line 837, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/afolabi/.local/share/virtualenvs/new_ios-rRJ0wE3V/lib/python3.7/site-packages/sh.py", line 861, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/patch -t -d /Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/build/hostpython3/x86_64/Python-3.7.3 -p1 -i /Users/afolabi/new_ios/.buildozer/ios/platform/kivy-ios/kivy_ios/recipes/hostpython3/pyconfig_detection.patch

  STDOUT:
patching file Lib/site.py
Hunk #1 FAILED at 458.
Hunk #2 succeeded at 492 (offset 6 lines).
1 out of 2 hunks FAILED -- saving rejects to file Lib/site.py.rej


  STDERR:

# Command failed: /Users/afolabi/.local/share/virtualenvs/new_ios-rRJ0wE3V/bin/python toolchain.py build hostpython3==3.7.3 python3==3.7.3 kivy==ede9bd1b806619dda022ab438964ce1b48645521 itsdangerous pycrypto werkzeug jinja2 markupsafe
# ENVIRONMENT:
#     PATH = '/Users/afolabi/.local/share/virtualenvs/new_ios-rRJ0wE3V/bin:/usr/local/Cellar/pipenv/2020.8.13/libexec/tools:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin'
#     TERM_PROGRAM = 'Apple_Terminal'
#     SHELL = '/bin/zsh'
#     TERM = 'xterm-256color'
#     TMPDIR = '/var/folders/1g/vnbs5z515g92lw_sjmk3rv_c0000gn/T/'
#     TERM_PROGRAM_VERSION = '433'
#     TERM_SESSION_ID = '71C2C38D-72B0-431D-9704-8F53A8446FAC'
#     USER = 'afolabi'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.3PRCiGV2Hu/Listeners'
#     LaunchInstanceID = 'E4380160-7C72-40E7-AD0E-F681AA2F1E0C'
#     PWD = '/Users/afolabi/new_ios'
#     LANG = 'en_US.UTF-8'
#     XPC_FLAGS = '0x0'
#     XPC_SERVICE_NAME = '0'
#     SHLVL = '2'
#     HOME = '/Users/afolabi'
#     LOGNAME = 'afolabi'
#     SECURITYSESSIONID = '186a6'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x0:0x0'
#     PIP_DISABLE_PIP_VERSION_CHECK = '1'
#     PYTHONDONTWRITEBYTECODE = '1'
#     PIP_PYTHON_PATH = '/usr/local/Cellar/pipenv/2020.8.13/libexec/bin/python3.8'
#     PIPENV_ACTIVE = '1'
#     OLDPWD = '/Users/afolabi/new_ios'
#     VIRTUAL_ENV = '/Users/afolabi/.local/share/virtualenvs/new_ios-rRJ0wE3V'
#     PS1 = '(new_ios) %n@%m %1~ %# '
#     LC_ALL = 'en_US.UTF-8'
#     LC_CTYPE = 'en_US.UTF-8'
#     _ = '/Users/afolabi/.local/share/virtualenvs/new_ios-rRJ0wE3V/bin/buildozer'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2```

**Comment by Zen-CODE** [comment]
Hi. Please may I ask you to post this issue on the buildozer repo, as it appears to be a buildozer issue.

https://github.com/kivy/buildozer

Thanks
