### ISSUE TITLE
Installation error at downloading openssl-1.1.1f.tar.gz

### ISSUE THREAD

**Issue by lucifermorn** [kivy/kivy-ios#551]
**Versions**

* Python :3.8.5
* MacOS version :Catalina
* XCode Version :11.7
* Cython version :

**The bug**
I followed all the instructions on Kivy-ios Github, but I don't get it all running. I've tried all sorts of Python versions, all kinds of virtual environments, and re-installations, but the installations always stops at the same point, at: Downloading http://www.openssl.org/source/openssl-1.1.1f.tar.gz

When I pull the tar in Safari I do get a download.

I do the following steps:
- python3 -m venv venv
- . venv/bin/activate
- pip3 install kivy-ios
- installing dependencies through Home-brew
- toolchain build python3 kivy

**Logs**
```
[DEBUG   ] Signing Identity:     "-"
[DEBUG   ] 
[DEBUG   ]     /usr/bin/codesign --force --sign - /Users/lucifer/dist/hostlibffi/usr/local/lib/libffi.a
[DEBUG   ] 
[DEBUG   ] RegisterExecutionPolicyException /Users/lucifer/dist/hostlibffi/usr/local/lib/libffi.a (in target 'libffi-Mac' from project 'libffi')
[DEBUG   ]     cd /Users/lucifer/build/hostlibffi/x86_64/libffi-3.2.1
[DEBUG   ]     builtin-RegisterExecutionPolicyException /Users/lucifer/dist/hostlibffi/usr/local/lib/libffi.a
[DEBUG   ] note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'libffi-Mac' from project 'libffi')
[DEBUG   ] 
[DEBUG   ] ** INSTALL SUCCEEDED **
[DEBUG   ] 
[DEBUG   ] 
[INFO    ] Postbuild hostlibffi for x86_64
[DEBUG   ] New State: hostlibffi.build.x86_64 at 2020-09-14 22:07:04.517476
[DEBUG   ] New State: hostlibffi.build_all at 2020-09-14 22:07:04.518221
[INFO    ] Download hostopenssl
[INFO    ] Downloading http://www.openssl.org/source/openssl-1.1.1f.tar.gz
[WARNING ] Download failed. Retrying in 1 second...
[WARNING ] Download failed. Retrying in 1 second...
[WARNING ] Download failed. Retrying in 1 second...
[WARNING ] Download failed. Retrying in 1 second...
[ERROR   ] Max download attempts reached: 5
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1790, in open
    return getattr(self, name)(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1999, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1948, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1790, in open
    return getattr(self, name)(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1968, in open_http
    return self._open_generic_http(http.client.HTTPConnection, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1962, in _open_generic_http
    return self.http_error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1980, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 2203, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 2167, in http_error_302
    result = self.redirect_internal(url, fp, errcode, errmsg,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 2199, in redirect_internal
    return self.open(newurl)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1796, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1790, in open
    return getattr(self, name)(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1999, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1948, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucifer/venv/bin/toolchain", line 8, in <module>
    sys.exit(main())
  File "/Users/lucifer/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1497, in main
    ToolchainCL()
  File "/Users/lucifer/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1270, in __init__
    getattr(self, args.command)()
  File "/Users/lucifer/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1323, in build
    build_recipes(args.recipe, ctx)
  File "/Users/lucifer/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1121, in build_recipes
    recipe.execute()
  File "/Users/lucifer/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 698, in execute
    self.download()
  File "/Users/lucifer/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 85, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/lucifer/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 733, in download
    self.download_file(self.url.format(version=self.version), fn)
  File "/Users/lucifer/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 474, in download_file
    urlretrieve(url, filename, report_hook)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1824, in retrieve
    fp = self.open(url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1796, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1790, in open
    return getattr(self, name)(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1968, in open_http
    return self._open_generic_http(http.client.HTTPConnection, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1962, in _open_generic_http
    return self.http_error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1980, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 2203, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 2167, in http_error_302
    result = self.redirect_internal(url, fp, errcode, errmsg,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 2199, in redirect_internal
    return self.open(newurl)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1796, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1790, in open
    return getattr(self, name)(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1999, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1948, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno socket error] [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
```

**Logs**
```
// REPLACE ME: Paste the build output containing the error
```

**Screenshots**

**Additional context**

**Comment by Zen-CODE** [comment]
Please follow the suggestions here and podt back your results? Thanks
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

**Comment by lucifermorn** [comment]
Thank you very much. This seems to be the problem.
After I did 
```pip install --upgrade certifi```
the toolchain build kivy ran successfully.
the second solution
```Install Certicates.command```
wasn't necessary for me.
Maybe add this to the Installation & requirements in README.md?
