### ISSUE TITLE
Problem building toolchain: hostpython3

### ISSUE THREAD

**Issue by jacob-strauss** [kivy/kivy-ios#565]
**Versions**

- Python : 3.7.7
- MacOS version : Big Sur 11.0.1 (though I got the same error with Catalina)
- XCode version : 12.02
- Cython version: 0.29.17

**Describe the bug**

Kivy-ios does not build correctly on my laptop. When I attempt to build the toolchain I get the following error:

```
[DEBUG   ] /Users/jacobstrauss/Documents/Python/kivy-ios/build/hostpython3/x86_64/Python-3.8.2/Modules/posixmodule.c:9197:15: error: 
[DEBUG   ]       implicit declaration of function 'sendfile' is invalid in C99
[DEBUG   ]       [-Werror,-Wimplicit-function-declaration]
[DEBUG   ]         ret = sendfile(in, out, offset, &sbytes, &sf, flags);
```

**To Reproduce**

Following the instructions on https://github.com/kivy/kivy-ios/  I created a virtual environment, installed kivy-ios, installed Cython version 0.29.17 and then built the toolchain. About half way through the build I get the error shown in the logs.

**Expected behavior**

Following the above steps I have built the toolchain many times before, and even have a few apps on my tablet that I made using kivy-ios. When I look in the build folder there are a bunch of folders missing, including: kivy-ios and python3 (amongst others).

**Logs**

```
Exception in thread background thread for pid 71014:
Traceback (most recent call last):
  File "/Users/jacobstrauss/.pyenv/versions/3.7.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/jacobstrauss/.pyenv/versions/3.7.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 1637, in wrap
    fn(*rgs, **kwargs)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 2561, in background_thread
    handle_exit_code(exit_code)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 2265, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make -C /Users/jacobstrauss/Documents/Python/kivy-ios/build/hostpython3/x86_64/Python-3.8.2/native-build -j4

  STDOUT:
clang -Qunused-arguments -fcolor-diagnostics -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -arch x86_64 -mmacosx-version-min=10.12 -I/Users/jacobstrauss/Documents/Python/kivy-ios/dist/hostlibffi/usr/local/include --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -arch x86_64 -mmacosx-version-min=10.12 -I/Users/jacobstrauss/Documents/Python/kivy-ios/dist/hostlibffi/usr/local/include  -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration  -I/User... (132713 more, please see e.stdout)

  STDERR:


Traceback (most recent call last):
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/bin/toolchain", line 10, in <module>
    sys.exit(main())
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 1497, in main
    ToolchainCL()
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 1270, in __init__
    getattr(self, args.command)()
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 1323, in build
    build_recipes(args.recipe, ctx)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 1121, in build_recipes
    recipe.execute()
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 700, in execute
    self.build_all()
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 85, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 794, in build_all
    self.build(arch)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 85, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 781, in build
    self.build_arch(arch)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 833, in build_arch
    getattr(self, build)()
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/recipes/hostpython3/__init__.py", line 72, in build_x86_64
    _env=build_env)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/kivy_ios/toolchain.py", line 67, in shprint
    for line in cmd:
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 911, in next
    self.wait()
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 841, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/jacobstrauss/Documents/Python/kivy-ios/venv/lib/python3.7/site-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make -C /Users/jacobstrauss/Documents/Python/kivy-ios/build/hostpython3/x86_64/Python-3.8.2/native-build -j4

  STDOUT:
clang -Qunused-arguments -fcolor-diagnostics -c -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -arch x86_64 -mmacosx-version-min=10.12 -I/Users/jacobstrauss/Documents/Python/kivy-ios/dist/hostlibffi/usr/local/include --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -arch x86_64 -mmacosx-version-min=10.12 -I/Users/jacobstrauss/Documents/Python/kivy-ios/dist/hostlibffi/usr/local/include  -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration  -I/User... (132713 more, please see e.stdout)

  STDERR:
```

**Additional context**

I got this error attempting to solve a different issue related to kivy-ios: https://github.com/kivy/kivy-ios/issues/564. I first removed all my Xcode files and then reinstalled Xcode. I ran into the issue after reinstalling Xcode.

Thanks for taking the time to read this!

**Comment by jacob-strauss** [comment]
I was able to fix this issue by downgrading back to Catalina, downgrading to Xcode 11.7 and reinstalling brew. I am still unable to build to my iPad (running iOS 14.2). Xcode throws up around 800 errors saying "undefined symbol," however, the problem I mentioned above is resolved.

**Comment by ajalbawab** [comment]
I got this same error, trying your Fix

**Comment by jda5** [comment]
@ajalbawab 

Install Xcode 12.2, not 11.7! The issue was with BigSur

**Comment by ajalbawab** [comment]
That was the fix. I'm able to deploy Kivy on iPad running 14.2, Python 3.8.. or 9?, and Catalina. @jda5 Thanks a ton for this, spent a good day or too looking up the issue.
