### ISSUE TITLE
Toolchain build python3 not working (due to hostopenssl not being built)

### ISSUE THREAD

**Issue by n-march** [kivy/kivy-ios#584]
I've been trying to compile my App but haven't been able to ```toolchain build python3```. I've noticed that the build order of the recipe is:
```
[INFO    ] Build order is ['hostlibffi', 'hostopenssl', 'libffi', 'openssl', 'hostpython3', 'python3']
```
I seem to be able to build hostlibffi ok (see ```toolchain status``` output log below) but run into the following issue when trying to build ```hostopenssl``` (see Logs below).

Some of the main things I've tried thus far (after a few hours of research and trying to understand what's going on):

- Trying to address the following error: ``` RAN: /usr/bin/make -j4 build_libs```: Made the [changes](https://github.com/kivy/kivy-ios/issues/434#issuecomment-611298656) suggested in #434 (however changed it to openssl-1.1.1h, which is the one I have installed)
- Trying to address the following error: ```ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd' for architecture x86_64``` I downloaded the new CommandLineTools (but couldn't install the Big Sur update because of the lack of space in my disk) as I realised that the ```xcode-select --install``` wasn't actually installing the latest version

Nothing has worked. Any guidance on what could have gone wrong is very much appreciated.

Thanks!

**Versions**

* Python : Python 3.6.10 
* Conda: 4.7.12
* MacOS version : Catalina 10.15.7 
* XCode Version : 10.3
* Cython version : 0.29.21
* OpenSSL version: 1.1.1h
* Kivy-ios (from pip list): 1.1.2

**Expected behavior**
Successfully build python3 recipe

**Logs**

```toolchain status```:
```
audiostream  - Not built
click        - Not built
curly        - Not built
cymunk       - Not built
distribute   - Not built
ffmpeg       - Build OK (built at 2021-01-06 08:01:41.434319)
ffpyplayer   - Not built
flask        - Not built
freetype     - Not built
host_setuptools - Not built
host_setuptools3 - Not built
hostlibffi   - Build OK (built at 2021-01-07 07:54:31.788992)
hostopenssl  - Not built
hostpython3  - Not built
ios          - Not built
itsdangerous - Not built
jinja2       - Not built
kivent_core  - Not built
kivy         - Not built
libcurl      - Not built
libffi       - Not built
libjpeg      - Not built
libpng       - Not built
libzbar      - Not built
markupsafe   - Not built
netifaces    - Not built
numpy        - Not built
openssl      - Build OK (built at 2021-01-06 08:04:11.004083)
photolibrary - Not built
pil          - Not built
pillow       - Not built
pkgresources - Not built
plyer        - Not built
pycrypto     - Not built
pykka        - Not built
pyobjus      - Not built
python3      - Not built
pyyaml       - Not built
sdl2         - Not built
sdl2_image   - Not built
sdl2_mixer   - Not built
sdl2_ttf     - Not built
werkzeug     - Not built
zbarlight    - Not built
```

```toolchain build  hostopenssl``` (same error if I try ```toolchain build python3```):
```
[INFO    ] Building with 4 processes, where supported
[INFO    ] Want to build ['hostopenssl']
[INFO    ] Loaded recipe hostopenssl (depends of [], optional are [])
[INFO    ] Build order is ['hostopenssl']
[INFO    ] Recipe order is ['hostopenssl']
[DEBUG   ] Cached result: Download hostopenssl. Ignoring
[DEBUG   ] Cached result: Extract hostopenssl. Ignoring
[INFO    ] Build_all hostopenssl
[INFO    ] Build hostopenssl for x86_64 (filtered)
[INFO    ] Build hostopenssl
[WARNING ] hostopenssl build for x86_64 has been incomplete
[WARNING ] Warning: deleting the build and restarting.
[INFO    ] Extract /Users/nico/PycharmProjects/EVAppPack2/.cache/hostopenssl-openssl-1.1.1f.tar.gz into /Users/nico/PycharmProjects/EVAppPack2/build/hostopenssl/x86_64
[INFO    ] Running Shell: /usr/bin/tar ('-C', '/Users/nico/PycharmProjects/EVAppPack2/build/hostopenssl/x86_64', '-xv', '-z', '-f', '/Users/nico/PycharmProjects/EVAppPack2/.cache/hostopenssl-openssl-1.1.1f.tar.gz') {'_iter': True, '_out_bufsize': 1, '_err_to_out': True}

[...]

[DEBUG   ] ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd' for architecture x86_64
[DEBUG   ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[DEBUG   ] make[1]: *** [libcrypto.dylib] Error 1
[DEBUG   ] make: *** [build_libs] Error 2
Exception in thread background thread for pid 94527:
Traceback (most recent call last):
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/sh.py", line 1662, in wrap
    fn(*args, **kwargs)
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/sh.py", line 2606, in background_thread
    handle_exit_code(exit_code)
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/sh.py", line 2304, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make -j4 build_libs

  STDOUT:
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _build_libs
cc  -I. -Iinclude -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DA... (434625 more, please see e.stdout)

  STDERR:


Traceback (most recent call last):
  File "/Users/nico/opt/anaconda3/envs/EVMap/bin/toolchain", line 8, in <module>
    sys.exit(main())
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 1497, in main
    ToolchainCL()
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 1270, in __init__
    getattr(self, args.command)()
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 1323, in build
    build_recipes(args.recipe, ctx)
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 1121, in build_recipes
    recipe.execute()
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 700, in execute
    self.build_all()
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 85, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 794, in build_all
    self.build(arch)
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 85, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 781, in build
    self.build_arch(arch)
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 833, in build_arch
    getattr(self, build)()
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/recipes/hostopenssl/__init__.py", line 26, in build_x86_64
    shprint(sh.make, self.ctx.concurrent_make, "build_libs")
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/kivy_ios/toolchain.py", line 67, in shprint
    for line in cmd:
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/sh.py", line 925, in next
    self.wait()
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/sh.py", line 849, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/nico/opt/anaconda3/envs/EVMap/lib/python3.6/site-packages/sh.py", line 877, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make -j4 build_libs

  STDOUT:
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _build_libs
cc  -I. -Iinclude -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DA... (434625 more, please see e.stdout)

  STDERR:

```

**Comment by n-march** [comment]
Ok, weird solution to this problem... 

In the previous version of Kivy-ios I was running I was unable to build ffmpeg and pyrebase4 and decided to start a build from scratch yet again (build issue for me since August'20). Long story short I figured out that the ```xcode-select --install``` wasn't doing anything and decided to download and manual install a different updated version without updating Xcode. 

I was just trying to downgrade the version of Command Line Tools (CLT) I'm running and to do so and I merely changed the name of the CLT folder I have in the ```Library/Developer``` folder. By chance I run, ```toolchain build hostopenssl``` to check something in the output error message and it happened to work.

I was able to also ```toolchain build python3```.

I'm still not sure what fixed this issue but, for any future sailors reading this, in my case it was probably an issue with the version of Command Line Tools I have installed...
