### ISSUE TITLE
kivy-ios: install grpc ==> FileNotFoundError: [Errno 2] No such file or directory: '/bin/false

### ISSUE THREAD

**Issue by mawaki** [kivy/kivy-ios#625]
I am trying to install grpcio for kivy-ios on macos, but I am receiving the error 
"FileNotFoundError: [Errno 2] No such file or directory: '/bin/false'"

false does not exist in the /bin directory, but in /usr/bin directory. I do not know how to make the command look at this directory instead (check the "running shell" line in the log below and you will see:
 _env: {'CC': '/bin/false', 'CXX': '/bin/false'

I have tried many changes, but I am still getting similar errors.

Can you please assist me.

the command run is: 
```
toolchain pip install grpcio
```

```
[INFO    ] Include dir added: {arch.arch}/freetype
[INFO    ] Include dir added: {arch.arch}/hostlibffi
[INFO    ] Global: hostpython located at /Users/user/Desktop/app_android/dist/hostpython3/bin/python
[INFO    ] Global: hostpgen located at /Users/user/Desktop/app_android/dist/hostpython3/bin/pgen
[INFO    ] Include dir added: {arch.arch}/ffi
[INFO    ] Include dir added: {arch.arch}/openssl
[INFO    ] Include dir added: common/sdl2
[INFO    ] Include dir added: common/sdl2_image
[INFO    ] Include dir added: common/sdl2_mixer
[INFO    ] Include dir added: common/sdl2_ttf
[ERROR   ] Executing pip with: ['install', '--isolated', '--prefix', '/Users/user/Desktop/app_android/dist/root/python3', 'grpcio']
[INFO    ] Running Shell: /Users/user/Desktop/app_android/dist/hostpython3/bin/pip3 ('install', '--isolated', '--prefix', '/Users/user/Desktop/app_android/dist/root/python3', 'grpcio') {'_env': {'CC': '/bin/false', 'CXX': '/bin/false', 'PYTHONPATH': '/Users/user/Desktop/app_android/dist/root/python3/lib/python3.8/site-packages', 'PYTHONOPTIMIZE': '2'}, '_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[DEBUG   ] Collecting grpcio
[DEBUG   ]   Using cached https://files.pythonhosted.org/packages/07/ea/398472e896f529d23fb58e33f01298dfc554a341d58f87c1ea5ad817208e/grpcio-1.39.0.tar.gz
[DEBUG   ]     ERROR: Command errored out with exit status 1:
[DEBUG   ]      command: /Users/user/Desktop/app_android/dist/hostpython3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-dlln9pfd/grpcio/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-dlln9pfd/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
[DEBUG   ]          cwd: /private/tmp/pip-install-dlln9pfd/grpcio/
[DEBUG   ]     Complete output (11 lines):
[DEBUG   ]     Traceback (most recent call last):
[DEBUG   ]       File "<string>", line 1, in <module>
[DEBUG   ]       File "/private/tmp/pip-install-dlln9pfd/grpcio/setup.py", line 257, in <module>
[DEBUG   ]         if check_linker_need_libatomic():
[DEBUG   ]       File "/private/tmp/pip-install-dlln9pfd/grpcio/setup.py", line 204, in check_linker_need_libatomic
[DEBUG   ]         cpp_test = subprocess.Popen([cxx, '-x', 'c++', '-std=c++11', '-'],
[DEBUG   ]       File "/Users/user/Desktop/app_android/dist/hostpython3/lib/python3.8/subprocess.py", line 854, in __init__
[DEBUG   ]         self._execute_child(args, executable, preexec_fn, close_fds,
[DEBUG   ]       File "/Users/user/Desktop/app_android/dist/hostpython3/lib/python3.8/subprocess.py", line 1702, in _execute_child
[DEBUG   ]         raise child_exception_type(errno_num, err_msg, err_filename)
[DEBUG   ]     FileNotFoundError: [Errno 2] No such file or directory: '/bin/false'
[DEBUG   ]     ----------------------------------------
[DEBUG   ] ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[DEBUG   ] WARNING: You are using pip version 19.2.3, however version 21.2.3 is available.
[DEBUG   ] You should consider upgrading via the 'pip install --upgrade pip' command.
Exception in thread background thread for pid 14027:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/user/Desktop/app_android/dist/hostpython3/bin/pip3 install --isolated --prefix /Users/user/Desktop/app_android/dist/root/python3 grpcio

  STDOUT:
Collecting grpcio
  Using cached https://files.pythonhosted.org/packages/07/ea/398472e896f529d23fb58e33f01298dfc554a341d58f87c1ea5ad817208e/grpcio-1.39.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/user/Desktop/app_android/dist/hostpython3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-dlln9pfd/grpcio/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-dlln9pfd/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
         cwd: /private/tmp/pip-install-dlln9pfd/grpcio/
    Comple... (1190 more, please see e.stdout)

  STDERR:

Traceback (most recent call last):
  File "/Users/user/Desktop/app_android/venv/bin/toolchain", line 8, in <module>
    sys.exit(main())
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1519, in main
    ToolchainCL()
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1276, in __init__
    getattr(self, args.command)()
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1478, in pip
    _pip(sys.argv[2:])
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1171, in _pip
    shprint(pip_cmd, *args, _env=pip_env)
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 55, in shprint
    for line in cmd:
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/sh.py", line 953, in next
    self.wait()
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/user/Desktop/app_android/venv/lib/python3.8/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/user/Desktop/app_android/dist/hostpython3/bin/pip3 install --isolated --prefix /Users/user/Desktop/app_android/dist/root/python3 grpcio

  STDOUT:
Collecting grpcio
  Using cached https://files.pythonhosted.org/packages/07/ea/398472e896f529d23fb58e33f01298dfc554a341d58f87c1ea5ad817208e/grpcio-1.39.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/user/Desktop/app_android/dist/hostpython3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-dlln9pfd/grpcio/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-dlln9pfd/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
         cwd: /private/tmp/pip-install-dlln9pfd/grpcio/
    Comple... (1190 more, please see e.stdout)

  STDERR:
```

THANKS!!!

**Comment by AndreMiras** [comment]
Just a few pointers to debug the issue. Unfortunately I don't have much time to dig further myself.
I would check the source code of the setup.py of that particular package around that line `grpcio/setup.py", line 204` (from stacktrace).
https://github.com/grpc/grpc/blob/v1.39.0/setup.py#L203
The CXX comes indeed from an environment variable and it has a default value, but is somehow overridden.
Next step is to see if by any chance kivy-ios is doing this override.
https://github.com/kivy/kivy-ios/blob/132eb27/kivy_ios/toolchain.py#L1166
And yeah it seems to be.
So I'm not entirely sure why we do that.
But also it seems like in macOS `false` could be located in `/usr/bin/false` instead. Could you confirm that?
I'm curious to see how it would handle it if you were linking /usr/bin/false binary to /bin/false:
```sh
sudo ln -s /usr/bin/false /bin/false 
```

**Comment by mawaki** [comment]
Thanks for helping me @AndreMiras,

I will try once I get home, and I will keep you posted!

**Comment by mawaki** [comment]
I modified CXX and CC paths in  toolchain.py, but it does not allow me to save the changes.
I tried 
```
sudo ln -s /usr/bin/false /bin/false 
```
But it says "ln: /bin/false: Operation not permitted"

**Comment by AndreMiras** [comment]
Pretty annoying, not sure why.
Then try editing the path in venv/lib/python3.8/site-packages/kivy_ios/toolchain.py so it points to `/usr/bin/false` rather than `/bin/false`

**Comment by mawaki** [comment]
Thanks for assisting me @AndreMiras,
It does not allow me to modify venv/lib/python3.8/site-packages/kivy_ios/toolchain.py.

**Comment by mawaki** [comment]
@AndreMiras I restarted my computer, and it finally allowed me to modify the toolchain.py. This error has been fixed, but I am having another error so I will open another issue. Thanks for your time and the help @AndreMiras.
