### ISSUE TITLE
Cannot find a recipe for grpcio and firebase-admin

### ISSUE THREAD

**Issue by mawaki** [kivy/kivy-ios#627]
Hello everyone,

Does anyone know a recipe for grpcio and firebase-admin on kivy-ios?

Thanks for the time consideration.

**Comment by bc31164b-cfd5-4a63-8144-875100622b2d** [comment]
```
from kivy_ios.toolchain import Recipe, shprint
import os
import sh


class GrpcioRecipe(Recipe):
    version = "master"
    url = 'https://files.pythonhosted.org/packages/37/56/700ff83b59eb69a7ddd62840666699173923020cfdf33a2860b9eba5667a/grpcio-1.40.0.tar.gz'
    depends = ["python3"]

    def install(self):
        arch = list(self.filtered_archs)[0]
        build_dir = self.get_build_dir(arch.arch)
        os.chdir(build_dir)
        hostpython = sh.Command(self.ctx.hostpython)
        build_env = arch.get_env()
        dest_dir = os.path.join(self.ctx.dist_dir, "root", "python3")
        build_env['PYTHONPATH'] = self.ctx.site_packages_dir
        shprint(hostpython, "setup.py", "install", "--prefix", dest_dir, _env=build_env)

recipe = GrpcioRecipe()
```

This succeeds at doing quite a lot of buildings, but fails at:

```
[DEBUG   ] /var/folders/bm/84nwtkcd5tqcl8fpbz42jw6c0000gn/T/tmptnwh4u43 -O3 -miphoneos-version-min=9.0 -I/Users/admin/dev/dist/include/x86_64/hostlibffi -I/Users/admin/dev/dist/include/x86_64/ffi -I/Users/admin/dev/dist/include/x86_64/openssl -I/Users/admin/dev/dist/include/x86_64 -D_WIN32_WINNT=1536 -DGRPC_XDS_USER_AGENT_NAME_SUFFIX="Python" -DGRPC_XDS_USER_AGENT_VERSION_SUFFIX="1.40.0" -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_darwin -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -Ithird_party/zlib -I/Users/admin/dev/dist/hostpython3/include/python3.9 -c third_party/zlib/zutil.c -o python_build/temp.macosx-11.6-x86_64-3.9/third_party/zlib/zutil.o -stdlib=libc++ -fvisibility=hidden -fno-wrapv -fno-exceptions -DHAVE_UNISTD_H -pthread
[DEBUG   ] creating None
[DEBUG   ] creating None/tmp
[DEBUG   ] creating None/tmp/tmpdz04aul2
[DEBUG   ] /var/folders/bm/84nwtkcd5tqcl8fpbz42jw6c0000gn/T/tmptnwh4u43 -O3 -miphoneos-version-min=9.0 -I/Users/admin/dev/dist/include/x86_64/hostlibffi -I/Users/admin/dev/dist/include/x86_64/ffi -I/Users/admin/dev/dist/include/x86_64/openssl -I/Users/admin/dev/dist/include/x86_64 -I/Users/admin/dev/dist/hostpython3/include/python3.9 -c /tmp/tmpdz04aul2/a.c -o None/tmp/tmpdz04aul2/a.o
[DEBUG   ] Traceback (most recent call last):
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
[DEBUG   ]     self.spawn(compiler_so + cc_args + [src, '-o', obj] +
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
[DEBUG   ]     _classic_spawn(self, command)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
[DEBUG   ]     spawn(cmd, dry_run=self.dry_run)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/spawn.py", line 87, in spawn
[DEBUG   ]     raise DistutilsExecError(
[DEBUG   ] distutils.errors.DistutilsExecError: command '/var/folders/bm/84nwtkcd5tqcl8fpbz42jw6c0000gn/T/tmptnwh4u43' failed with exit code 1
[DEBUG   ]
[DEBUG   ] During handling of the above exception, another exception occurred:
[DEBUG   ]
[DEBUG   ] Traceback (most recent call last):
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/commands.py", line 285, in build_extensions
[DEBUG   ]     build_ext.build_ext.build_extensions(self)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
[DEBUG   ]     self._build_extensions_serial()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
[DEBUG   ]     self.build_extension(ext)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
[DEBUG   ]     _build_ext.build_extension(self, ext)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
[DEBUG   ]     objects = self.compiler.compile(sources,
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
[DEBUG   ]     multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/multiprocessing/pool.py", line 364, in map
[DEBUG   ]     return self._map_async(func, iterable, mapstar, chunksize).get()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/multiprocessing/pool.py", line 771, in get
[DEBUG   ]     raise self._value
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
[DEBUG   ]     result = (True, func(*args, **kwds))
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
[DEBUG   ]     return list(map(*args))
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
[DEBUG   ]     self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/commands.py", line 268, in new_compile
[DEBUG   ]     return old_compile(obj, src, ext, cc_args, extra_postargs,
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/unixccompiler.py", line 120, in _compile
[DEBUG   ]     raise CompileError(msg)
[DEBUG   ] distutils.errors.CompileError: command '/var/folders/bm/84nwtkcd5tqcl8fpbz42jw6c0000gn/T/tmptnwh4u43' failed with exit code 1
[DEBUG   ]
[DEBUG   ] During handling of the above exception, another exception occurred:
[DEBUG   ]
[DEBUG   ] Traceback (most recent call last):
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/setup.py", line 524, in <module>
[DEBUG   ]     setuptools.setup(
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
[DEBUG   ]     return distutils.core.setup(**attrs)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/core.py", line 148, in setup
[DEBUG   ]     dist.run_commands()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/dist.py", line 966, in run_commands
[DEBUG   ]     self.run_command(cmd)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/dist.py", line 985, in run_command
[DEBUG   ]     cmd_obj.run()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
[DEBUG   ]     self.do_egg_install()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/site-packages/setuptools/command/install.py", line 109, in do_egg_install
[DEBUG   ]     self.run_command('bdist_egg')
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/cmd.py", line 313, in run_command
[DEBUG   ]     self.distribution.run_command(command)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/dist.py", line 985, in run_command
[DEBUG   ]     cmd_obj.run()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 174, in run
[DEBUG   ]     cmd = self.call_command('install_lib', warn_dir=0)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
[DEBUG   ]     self.run_command(cmdname)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/cmd.py", line 313, in run_command
[DEBUG   ]     self.distribution.run_command(command)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/dist.py", line 985, in run_command
[DEBUG   ]     cmd_obj.run()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
[DEBUG   ]     self.build()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/command/install_lib.py", line 107, in build
[DEBUG   ]     self.run_command('build_ext')
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/cmd.py", line 313, in run_command
[DEBUG   ]     self.distribution.run_command(command)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/dist.py", line 985, in run_command
[DEBUG   ]     cmd_obj.run()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 87, in run
[DEBUG   ]     _build_ext.run(self)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/command/build_ext.py", line 340, in run
[DEBUG   ]     self.build_extensions()
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/commands.py", line 289, in build_extensions
[DEBUG   ]     raise CommandError(
[DEBUG   ] commands.CommandError: Failed `build_ext` step:
[DEBUG   ] Traceback (most recent call last):
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
[DEBUG   ]     self.spawn(compiler_so + cc_args + [src, '-o', obj] +
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
[DEBUG   ]     _classic_spawn(self, command)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
[DEBUG   ]     spawn(cmd, dry_run=self.dry_run)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/spawn.py", line 87, in spawn
[DEBUG   ]     raise DistutilsExecError(
[DEBUG   ] distutils.errors.DistutilsExecError: command '/var/folders/bm/84nwtkcd5tqcl8fpbz42jw6c0000gn/T/tmptnwh4u43' failed with exit code 1
[DEBUG   ]
[DEBUG   ] During handling of the above exception, another exception occurred:
[DEBUG   ]
[DEBUG   ] Traceback (most recent call last):
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/commands.py", line 285, in build_extensions
[DEBUG   ]     build_ext.build_ext.build_extensions(self)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
[DEBUG   ]     self._build_extensions_serial()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
[DEBUG   ]     self.build_extension(ext)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
[DEBUG   ]     _build_ext.build_extension(self, ext)
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
[DEBUG   ]     objects = self.compiler.compile(sources,
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
[DEBUG   ]     multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/multiprocessing/pool.py", line 364, in map
[DEBUG   ]     return self._map_async(func, iterable, mapstar, chunksize).get()
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/multiprocessing/pool.py", line 771, in get
[DEBUG   ]     raise self._value
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
[DEBUG   ]     result = (True, func(*args, **kwds))
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
[DEBUG   ]     return list(map(*args))
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
[DEBUG   ]     self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
[DEBUG   ]   File "/Users/admin/dev/build/grpcio/x86_64/grpcio-1.40.0/src/python/grpcio/commands.py", line 268, in new_compile
[DEBUG   ]     return old_compile(obj, src, ext, cc_args, extra_postargs,
[DEBUG   ]   File "/Users/admin/dev/dist/hostpython3/lib/python3.9/distutils/unixccompiler.py", line 120, in _compile
[DEBUG   ]     raise CompileError(msg)
[DEBUG   ] distutils.errors.CompileError: command '/var/folders/bm/84nwtkcd5tqcl8fpbz42jw6c0000gn/T/tmptnwh4u43' failed with exit code 1
[DEBUG   ]
Exception in thread background thread for pid 2730:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/sh-1.14.2-py3.9.egg/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/sh-1.14.2-py3.9.egg/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/sh-1.14.2-py3.9.egg/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/sh-1.14.2-py3.9.egg/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /Users/admin/dev/dist/hostpython3/bin/python setup.py install --prefix /Users/admin/dev/dist/root/python3

  STDOUT:
Found cython-generated files...
running install
Checking .pth file support in /Users/admin/dev/dist/root/python3/lib/python3.9/site-packages/
/Users/admin/dev/dist/hostpython3/bin/python -E -c pass
TEST FAILED: /Users/admin/dev/dist/root/python3/lib/python3.9/site-packages/ does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Users/admin/dev/dist/root/python3/lib/python3.9/site-packages/

and your PYTHONPATH environment variable currently contains:

    '/Users/admin/dev/dist/root/pyth... (1573362 more, please see e.stdout)

  STDERR:

Traceback (most recent call last):
  File "/Users/admin/dev/venv/bin/toolchain", line 33, in <module>
    sys.exit(load_entry_point('kivy-ios==1.3.0.dev0', 'console_scripts', 'toolchain')())
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/kivy_ios-1.3.0.dev0-py3.9.egg/kivy_ios/toolchain.py", line 1536, in main
    ToolchainCL()
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/kivy_ios-1.3.0.dev0-py3.9.egg/kivy_ios/toolchain.py", line 1293, in __init__
    getattr(self, args.command)()
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/kivy_ios-1.3.0.dev0-py3.9.egg/kivy_ios/toolchain.py", line 1354, in build
    build_recipes(args.recipe, ctx)
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/kivy_ios-1.3.0.dev0-py3.9.egg/kivy_ios/toolchain.py", line 1136, in build_recipes
    recipe.execute()
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/kivy_ios-1.3.0.dev0-py3.9.egg/kivy_ios/toolchain.py", line 703, in execute
    self.build_all()
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/kivy_ios-1.3.0.dev0-py3.9.egg/kivy_ios/toolchain.py", line 73, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/kivy_ios-1.3.0.dev0-py3.9.egg/kivy_ios/toolchain.py", line 829, in build_all
    self.install()
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/kivy_ios-1.3.0.dev0-py3.9.egg/kivy_ios/recipes/grpcio/__init__.py", line 22, in install
    shprint(hostpython, "setup.py", "install", "--prefix", dest_dir, _env=build_env)
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/kivy_ios-1.3.0.dev0-py3.9.egg/kivy_ios/toolchain.py", line 55, in shprint
    for line in cmd:
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/sh-1.14.2-py3.9.egg/sh.py", line 953, in next
    self.wait()
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/sh-1.14.2-py3.9.egg/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/admin/dev/venv/lib/python3.9/site-packages/sh-1.14.2-py3.9.egg/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:
  RAN: /Users/admin/dev/dist/hostpython3/bin/python setup.py install --prefix /Users/admin/dev/dist/root/python3

  STDOUT:
Found cython-generated files...
running install
Checking .pth file support in /Users/admin/dev/dist/root/python3/lib/python3.9/site-packages/
/Users/admin/dev/dist/hostpython3/bin/python -E -c pass
TEST FAILED: /Users/admin/dev/dist/root/python3/lib/python3.9/site-packages/ does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Users/admin/dev/dist/root/python3/lib/python3.9/site-packages/

and your PYTHONPATH environment variable currently contains:

    '/Users/admin/dev/dist/root/pyth... (1573362 more, please see e.stdout)

  STDERR:
```
