### ISSUE TITLE
kivy-ios: clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by mawaki** [kivy/kivy-ios#628]
I installed kivy-ios master, and my system's python is 3.9.2. The following is the last lines of my log. I have been struggling with this for a week. May you please assist me.

The command ran is 
```
toolchain build hostpython
```

```
[DEBUG   ]                   
[DEBUG   ] ranlib -c test/libtestutil.a || echo Never mind.
[DEBUG   ] ar: creating archive libcrypto.a
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libssl.a(ssl_utst.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libssl.a(t1_trce.o) has no symbols
[DEBUG   ] ranlib -c libssl.a || echo Never mind.
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libssl.a(ssl_utst.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libssl.a(t1_trce.o) has no symbols
[DEBUG   ] ld: library not found for -lSystem
[DEBUG   ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[DEBUG   ] make[1]: *** [libcrypto.dylib] Error 1
[DEBUG   ] make[1]: *** Waiting for unfinished jobs....
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(async_null.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(async_win.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(cms_cd.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(dso_dl.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(dso_openssl.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(dso_vms.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(dso_win32.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(ebcdic.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(ecp_nistp224.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(ecp_nistp256.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(ecp_nistp521.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(ecp_nistputil.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(e_rc5.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(m_md2.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(rand_egd.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(rand_vms.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(rand_win.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(threads_none.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(threads_win.o) has no symbols
[DEBUG   ] ranlib -c libcrypto.a || echo Never mind.
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(async_null.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(async_win.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(cms_cd.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(dso_dl.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(dso_openssl.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(dso_vms.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(dso_win32.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(ebcdic.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(ecp_nistp224.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(ecp_nistp256.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(ecp_nistp521.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(ecp_nistputil.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(e_rc5.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(m_md2.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(rand_egd.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(rand_vms.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(rand_win.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(threads_none.o) has no symbols
[DEBUG   ] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcrypto.a(threads_win.o) has no symbols
[DEBUG   ] make: *** [build_libs] Error 2
Exception in thread background thread for pid 57073:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Volumes/Passport_mac/mac/Dev/Mawou_ios/venv/lib/python3.9/site-packages/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/Volumes/Passport_mac/mac/Dev/Mawou_ios/venv/lib/python3.9/site-packages/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/Volumes/Passport_mac/mac/Dev/Mawou_ios/venv/lib/python3.9/site-packages/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Volumes/Passport_mac/mac/Dev/Mawou_ios/venv/lib/python3.9/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make -j4 build_libs

  STDOUT:
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _build_libs
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -I. -Iinclude -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL... (502149 more, please see e.stdout)

  STDERR:
```

Please help.

**Comment by mawaki** [comment]
I reset my mac and reinstalled everything, and this issue disappeared.
