### ISSUE TITLE
Error when I run toolchain build Kivy python3

### ISSUE THREAD

**Issue by sltoo777** [kivy/kivy-ios#635]
`[DEBUG   ] ModuleNotFoundError: No module named '_ctypes'
Exception in thread background thread for pid 40204:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/opt/homebrew/lib/python3.9/site-packages/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/opt/homebrew/lib/python3.9/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/mahdi/dist/hostpython3/bin/python setup.py install --prefix=/Users/mahdi/dist/root/python3

  STDOUT:
Traceback (most recent call last):
  File "/Users/mahdi/build/host_setuptools3/x86_64/setuptools-54.1.2/setup.py", line 7, in <module>
    import setuptools
  File "/Users/mahdi/build/host_setuptools3/x86_64/setuptools-54.1.2/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/Users/mahdi/build/host_setuptools3/x86_64/setuptools-54.1.2/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/Users/mahdi/build/host_setuptools3/x86_64/setuptools-54.1.2/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/Users/mahdi/dist/hostpython3/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array... (48 more, please see e.stdout)

  STDERR:

[INFO    ] cd /Users/mahdi
[DEBUG   ] Setting PYTHONPATH to None
Traceback (most recent call last):
  File "/opt/homebrew/bin/toolchain", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1536, in main
    ToolchainCL()
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1293, in __init__
    getattr(self, args.command)()
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1354, in build
    build_recipes(args.recipe, ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1136, in build_recipes
    recipe.execute()
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 703, in execute
    self.build_all()
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 73, in _cache_execution
    f(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 829, in build_all
    self.install()
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 73, in _cache_execution
    f(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/recipes/host_setuptools3/__init__.py", line 20, in install
    shprint(hostpython, "setup.py", "install",
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 55, in shprint
    for line in cmd:
  File "/opt/homebrew/lib/python3.9/site-packages/sh.py", line 953, in next
    self.wait()
  File "/opt/homebrew/lib/python3.9/site-packages/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/opt/homebrew/lib/python3.9/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /Users/mahdi/dist/hostpython3/bin/python setup.py install --prefix=/Users/mahdi/dist/root/python3

  STDOUT:
Traceback (most recent call last):
  File "/Users/mahdi/build/host_setuptools3/x86_64/setuptools-54.1.2/setup.py", line 7, in <module>
    import setuptools
  File "/Users/mahdi/build/host_setuptools3/x86_64/setuptools-54.1.2/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/Users/mahdi/build/host_setuptools3/x86_64/setuptools-54.1.2/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/Users/mahdi/build/host_setuptools3/x86_64/setuptools-54.1.2/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/Users/mahdi/dist/hostpython3/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array... (48 more, please see e.stdout)

  STDERR:

`

**Comment by misl6** [comment]
Can you please complete the bug report with some additional information regarding your environment + how to reproduce ?

Is highly recommended to follow this template when reporting a potential issue:
https://raw.githubusercontent.com/kivy/kivy-ios/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by misl6** [comment]
The user opened a new issue (#640), by using the bug report template.
