### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__imaging)

### ISSUE THREAD

**Issue by faris4017** [kivy/kivy-ios#645]
Warning: Error creating LLDB target at path '/Users/fari/Library/Developer/Xcode/DerivedData/fari_test-hcgkpjszphmkvveyqeyykatbzsqc/Build/Products/Debug-iphonesimulator/fari_test.app'- using an empty LLDB target which can cause slow memory reads from remote devices.
2021-09-27 07:10:14.987699+0530 fari_test[12596:1570767] Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
2021-09-27 07:10:14.987971+0530 fari_test[12596:1570767] Initializing python
2021-09-27 07:10:15.147691+0530 fari_test[12596:1570767] Running main.py: /Users/fari/Library/Developer/CoreSimulator/Devices/AAD18F1F-3ED5-464F-B26A-153806C032C2/data/Containers/Bundle/Application/52D3BF80-6B02-4E56-A28D-591714A21483/fari_test.app/YourApp/main.pyc
[INFO   ] [Kivy        ] v2.1.0.dev0
[INFO   ] [Kivy        ] Installed at "/Users/fari/Library/Developer/CoreSimulator/Devices/AAD18F1F-3ED5-464F-B26A-153806C032C2/data/Containers/Bundle/Application/52D3BF80-6B02-4E56-A28D-591714A21483/fari_test.app/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.2 (default, Sep 27 2021, 00:23:26) 
[Clang 12.0.5 (clang-1205.0.22.11)]
[INFO   ] [Python      ] Interpreter at "/Users/fari/Library/Developer/CoreSimulator/Devices/AAD18F1F-3ED5-464F-B26A-153806C032C2/data/Containers/Bundle/Application/52D3BF80-6B02-4E56-A28D-591714A21483/fari_test.app/fari_test"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_sdl2, img_ffpyplayer, img_pil ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 APPLE-18.5.7'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple Software Renderer'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [KivyMD      ] 0.104.2, git-bc7d1f5, 2021-06-06 (installed at "/Users/fari/Library/Developer/CoreSimulator/Devices/AAD18F1F-3ED5-464F-B26A-153806C032C2/data/Containers/Bundle/Application/52D3BF80-6B02-4E56-A28D-591714A21483/fari_test.app/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "<string>", line 44, in load_module
   File "/Users/fari/Desktop/kivymd_app/kivy-ios/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
   File "<frozen importlib._bootstrap>", line 711, in _load
   File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 565, in module_from_spec
   File "<frozen importlib._bootstrap_external>", line 1108, in create_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
 ImportError: dynamic module does not define module export function (PyInit_PIL__imaging)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/fari/Desktop/kivymd_app/kivy-ios/fari_test-ios/YourApp/main.py", line 13, in <module>
   File "/Users/fari/Library/Developer/CoreSimulator/Devices/AAD18F1F-3ED5-464F-B26A-153806C032C2/data/Containers/Bundle/Application/52D3BF80-6B02-4E56-A28D-591714A21483/fari_test.app/lib/python3.9/site-packages/kivymd/uix/__init__.py", line 8, in <module>
     from kivymd.uix.behaviors import SpecificBackgroundColorBehavior
   File "/Users/fari/Library/Developer/CoreSimulator/Devices/AAD18F1F-3ED5-464F-B26A-153806C032C2/data/Containers/Bundle/Application/52D3BF80-6B02-4E56-A28D-591714A21483/fari_test.app/lib/python3.9/site-packages/kivymd/uix/behaviors/__init__.py", line 10, in <module>
     from .backgroundcolor_behavior import (
   File "/Users/fari/Library/Developer/CoreSimulator/Devices/AAD18F1F-3ED5-464F-B26A-153806C032C2/data/Containers/Bundle/Application/52D3BF80-6B02-4E56-A28D-591714A21483/fari_test.app/lib/python3.9/site-packages/kivymd/uix/behaviors/backgroundcolor_behavior.py", line 25, in <module>
     from .elevation import CommonElevationBehavior
   File "/Users/fari/Library/Developer/CoreSimulator/Devices/AAD18F1F-3ED5-464F-B26A-153806C032C2/data/Containers/Bundle/Application/52D3BF80-6B02-4E56-A28D-591714A21483/fari_test.app/lib/python3.9/site-packages/kivymd/uix/behaviors/elevation.py", line 364, in <module>
     from PIL import Image, ImageDraw, ImageFilter
   File "/Users/fari/Library/Developer/CoreSimulator/Devices/AAD18F1F-3ED5-464F-B26A-153806C032C2/data/Containers/Bundle/Application/52D3BF80-6B02-4E56-A28D-591714A21483/fari_test.app/lib/python3.9/site-packages/PIL/Image.py", line 109, in <module>
     from . import _imaging as core
   File "<string>", line 48, in load_module
   File "/Users/fari/Desktop/kivymd_app/kivy-ios/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
 ImportError: dynamic module does not define module export function (PyInit__imaging)
2021-09-27 07:10:16.694665+0530 fari_test[12596:1570767] Application quit abnormally!
2021-09-27 07:10:16.708002+0530 fari_test[12596:1570767] Leaving

**Comment by mamunabcoder** [comment]
@faris4017 Hello, I have been facing the same issues

**Comment by faris4017** [comment]
No,  same issues already opened so i closed 
we are waiting to update kivy-ios lib @kivy

**Comment by secretcoder** [comment]
@faris4017 I solved by removing the PIL and Pillow folders from the dist folder. Then I build the pillow recipe and it works only on the simulator. It does not work on the actual iPhone when I tested there, I get permissions error which I think the new Pillow recipe solves that issue. Either way another thing I noticed on the ios simulators is that no kivymd icons show up.
