### ISSUE TITLE
h5py import application crash for kivy-iOS created iOS app

### ISSUE THREAD

**Issue by mamunabcoder** [kivy/kivy-ios#648]
**Versions**

* Python : 3.9.6
* MacOS version : 10.15.7
* XCode Version : 12.2
* Cython version : 0.29.24

**Describe the bug**
I have put the below command into Mac terminal and install the package into kivy-ios project, this installed and automatically showing into python site_packages

_**python3 toolchain.py pip install h5py**_       

Open Kivy-ios created app, open the app using command line

import the h5py into main.py file

build and run the app then app crash

below are the crash log

 Traceback (most recent call last):
   File "<string>", line 44, in load_module
   File "/Users/bjitlimited/Work/JASMY/RnD/kivy_investigation/kivy/kivy-ios/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
   File "<frozen importlib._bootstrap>", line 711, in _load
   File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 565, in module_from_spec
   File "<frozen importlib._bootstrap_external>", line 1108, in create_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
 ImportError: dynamic module does not define module export function (PyInit_h5py__errors)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/bjitlimited/Work/JASMY/RnD/kivy_investigation/kivy/kivy-ios/touchtracer-ios/YourApp/main.py", line 40, in <module>
   File "/Users/bjitlimited/Library/Developer/CoreSimulator/Devices/CAF69AA4-C038-4111-B0E7-BD9A6A432180/data/Containers/Bundle/Application/FADE78E1-0553-4173-B508-C245FEE9B837/touchtracer.app/lib/python3.9/site-packages/h5py/__init__.py", line 25, in <module>
     from . import _errors
   File "<string>", line 48, in load_module
   File "/Users/bjitlimited/Work/JASMY/RnD/kivy_investigation/kivy/kivy-ios/dist/root/python3/lib/python3.9/imp.py", line 342, in load_dynamic
 ImportError: dynamic module does not define module export function (PyInit__errors)
2021-09-29 15:33:06.437485+0600 touchtracer[24674:409940] Application quit abnormally!
2021-09-29 15:33:06.454424+0600 touchtracer[24674:409940] Leaving

Can any one suggest me in this situation what can do now?

**Comment by misl6** [comment]
As #649 , `h5py` is not a plain python package and needs a recipe. I'm closing this issue and keeping active the feature request you made.
