### ISSUE TITLE
Error with toolchain build kivy 

### ISSUE THREAD

**Issue by nkehoe** [kivy/kivy-ios#692]
**Versions**

* Python : 3.9.7
* MacOS version :12.3
* XCode Version :13.3
* Cython version :0.29.28

**Describe the bug**
Tried to build kivy to start a Xcode project. I'm new and not sure what's wrong.

**To Reproduce**
toolchain build kivy

**Expected behavior**
// REPLACE ME: A clear and concise description of what you expected to happen.

**Logs**
```
[DEBUG   ]     /bin/sh -c /Users/noelkehoe/build/libffi/x86_64/libffi-3.2.1/build/libffi.build/Release-iphonesimulator/libffi-iOS.build/Script-DB13B3051849E01C0010F42D.sh
[DEBUG   ] /Users/noelkehoe/build/libffi/x86_64/libffi-3.2.1/build/libffi.build/Release-iphonesimulator/libffi-iOS.build/Script-DB13B3051849E01C0010F42D.sh: line 2: /usr/bin/python: No such file or directory
[DEBUG   ] Command PhaseScriptExecution failed with a nonzero exit code
[DEBUG   ] 
[DEBUG   ] ** BUILD FAILED **
[DEBUG   ] 
[DEBUG   ] 
[DEBUG   ] The following build commands failed:
[DEBUG   ] 	PhaseScriptExecution Run\ Script /Users/noelkehoe/build/libffi/x86_64/libffi-3.2.1/build/libffi.build/Release-iphonesimulator/libffi-iOS.build/Script-DB13B3051849E01C0010F42D.sh (in target 'libffi-iOS' from project 'libffi')
[DEBUG   ] (1 failure)
Exception in thread background thread for pid 57183:
Traceback (most recent call last):
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/sh.py", line 1683, in wrap
    fn(*rgs, **kwargs)
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/sh.py", line 2662, in background_thread
    handle_exit_code(exit_code)
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/sh.py", line 2349, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_65: 

  RAN: /usr/bin/xcodebuild IDEBuildOperationMaxNumberOfConcurrentCompileTasks=8 ONLY_ACTIVE_ARCH=NO ARCHS=x86_64 BITCODE_GENERATION_MODE=bitcode -sdk iphonesimulator -project libffi.xcodeproj -target libffi-iOS -configuration Release

  STDOUT:
2022-03-29 16:40:57.632 xcodebuild[57183:248260] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-03-29 16:40:57.632 xcodebuild[57183:248260] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild IDEBuildOperationMaxNumberOfConcurrentCompileTasks=8 ONLY_ACTIVE_ARCH=NO ARCHS=x86_64 BITCODE_GENERATION_M... (33520 more, please see e.stdout)

  STDERR:

Traceback (most recent call last):
  File "/Users/noelkehoe/opt/anaconda3/bin/toolchain", line 8, in <module>
    sys.exit(main())
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1555, in main
    ToolchainCL()
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1299, in __init__
    getattr(self, args.command)()
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1368, in build
    build_recipes(args.recipe, ctx)
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1142, in build_recipes
    recipe.execute()
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 704, in execute
    self.build_all()
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 74, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 803, in build_all
    self.build(arch)
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 74, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 790, in build
    self.build_arch(arch)
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/recipes/libffi/__init__.py", line 35, in build_arch
    shprint(sh.xcodebuild, self.ctx.concurrent_xcodebuild,
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 56, in shprint
    for line in cmd:
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/sh.py", line 953, in next
    self.wait()
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/noelkehoe/opt/anaconda3/lib/python3.9/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_65: 

  RAN: /usr/bin/xcodebuild IDEBuildOperationMaxNumberOfConcurrentCompileTasks=8 ONLY_ACTIVE_ARCH=NO ARCHS=x86_64 BITCODE_GENERATION_MODE=bitcode -sdk iphonesimulator -project libffi.xcodeproj -target libffi-iOS -configuration Release

  STDOUT:
2022-03-29 16:40:57.632 xcodebuild[57183:248260] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-03-29 16:40:57.632 xcodebuild[57183:248260] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild IDEBuildOperationMaxNumberOfConcurrentCompileTasks=8 ONLY_ACTIVE_ARCH=NO ARCHS=x86_64 BITCODE_GENERATION_M... (33520 more, please see e.stdout)

  STDERR:
```

**Screenshots**

**Additional context**

**Comment by misl6** [comment]
This issue has been fixed via https://github.com/kivy/kivy-ios/pull/688

For installing a development version please refer to: https://github.com/kivy/kivy-ios#development
