### ISSUE TITLE
i use your method to make python code  all in .a and link in iOS but ...

### ISSUE THREAD

**Issue by sentball** [kivy/kivy-ios#75]
see your reply on this article

http://stackoverflow.com/questions/8366544/can-i-statically-link-cython-modules-into-an-executable-which-embeds-python

i have a try but meet some trouble

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "CGPLoad.pyx", line 19, in init CGPLoad (kivy/CGPLoad.c:3005)
  File "LogInOutShell.pyx", line 20, in init LogInOutShell (kivy/LogInOutShell.c:3032)
  File "CommonToolShell.pyx", line 19, in init CommonToolShell (kivy/CommonToolShell.c:6393)
  File "GameWorld.pyx", line 19, in init GameWorld (kivy/GameWorld.c:2516)
  File "IPY_GAMEWORLD.pyx", line 16, in init IPY_GAMEWORLD (kivy/IPY_GAMEWORLD.c:27912)
NameError: name '__file__' is not defined

**Comment by tito** [comment]
__file__ doesn't work for extension i think. This builtin variable is not always available. Just make your code using os.getcwd() instead, and it will work.
