### ISSUE TITLE
Toolchain build openssl not working

### ISSUE THREAD

**Issue by Casimir1965** [kivy/kivy-ios#819]
**Versions**

* Python : 3.11
* MacOS version : 13.4
* XCode Version : 14.3
* Cython version : 2.99
* MacBook Pro with Apple M1 Max chip

**Describe the bug**
After installing the phyton and kivy developtment environment I'm trying to build the proper toolchain for my evironment. This step always fails at the same point. Please see log below. 

I check already some webpages to nail down this but I was so far uncessful. I believe I followed the given instructions from python as well from the kivy team. Not sure what I have to change. Any help is appreciated. And unfortunately the meintion discord channel is full and I'm not able to join ...

(csh_venv) carstenschmidt@Carstens-MacBook-Pro csh_venv % toolchain build openssl
[DEBUG   ] Using selector: KqueueSelector
[INFO    ] Building with 10 processes, where supported
[INFO    ] Want to build ['openssl']
[INFO    ] Using the bundled version for recipe 'openssl'
[INFO    ] Loaded recipe openssl (depends of [], optional are [])
[INFO    ] Build order is ['openssl']
[INFO    ] Using the bundled version for recipe 'openssl'
[INFO    ] Recipe order is ['openssl']
[INFO    ] Include dir added: {arch.arch}/openssl
[DEBUG   ] Cached result: Download openssl. Ignoring
[DEBUG   ] Cached result: Extract openssl. Ignoring
[DEBUG   ] Cached result: Install_hostpython_prerequisites openssl. Ignoring
[INFO    ] Build_all openssl
[INFO    ] Build openssl for x86_64, arm64 (filtered)
[INFO    ] Build openssl
[WARNING ] Error extracting the archive /Users/carstenschmidt/csh_venv/.cache/openssl-openssl-1.1.1l.tar.gz
[WARNING ] This is usually caused by a corrupt download. The file will be removed and re-downloaded on the next run.
[WARNING ] /Users/carstenschmidt/csh_venv/.cache/openssl-openssl-1.1.1l.tar.gz
Traceback (most recent call last):
  File "/Users/carstenschmidt/csh_venv/bin/toolchain", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/carstenschmidt/csh_venv/lib/python3.11/site-packages/kivy_ios/toolchain.py", line 1564, in main
    ToolchainCL()
  File "/Users/carstenschmidt/csh_venv/lib/python3.11/site-packages/kivy_ios/toolchain.py", line 1308, in __init__
    getattr(self, args.command)()
  File "/Users/carstenschmidt/csh_venv/lib/python3.11/site-packages/kivy_ios/toolchain.py", line 1377, in build
    build_recipes(args.recipe, ctx)
  File "/Users/carstenschmidt/csh_venv/lib/python3.11/site-packages/kivy_ios/toolchain.py", line 1142, in build_recipes
    recipe.execute()
  File "/Users/carstenschmidt/csh_venv/lib/python3.11/site-packages/kivy_ios/toolchain.py", line 704, in execute
    self.build_all()
  File "/Users/carstenschmidt/csh_venv/lib/python3.11/site-packages/kivy_ios/toolchain.py", line 74, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/carstenschmidt/csh_venv/lib/python3.11/site-packages/kivy_ios/toolchain.py", line 803, in build_all
    self.build(arch)
  File "/Users/carstenschmidt/csh_venv/lib/python3.11/site-packages/kivy_ios/toolchain.py", line 74, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/carstenschmidt/csh_venv/lib/python3.11/site-packages/kivy_ios/toolchain.py", line 772, in build
    self.build_dir = self.get_build_dir(arch.arch)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carstenschmidt/csh_venv/lib/python3.11/site-packages/kivy_ios/toolchain.py", line 634, in get_build_dir
    return join(self.ctx.build_dir, self.name, arch, self.archive_root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 90, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
(csh_venv) carstenschmidt@Carstens-MacBook-Pro csh_venv % 

The phyton code (easy calculator) can be build for the macOS environment and as well for Android and is running directly in the python evorinment via python3 command.

**Comment by misl6** [comment]
That looks like a temporary download failure of the openssl package.
Consider deleting the `.cache` folder and try again.
