### ISSUE TITLE
Running example apps on iOS device fails because pygments are missing

### ISSUE THREAD

**Issue by shurik** [kivy/kivy-ios#88]
I've created a couple of app using the examples that ship with Kivy. When I try to run the app from XCode on a device (iPad) the app exits with the following output.

```
2014-03-25 13:42:59.474 kivycatalog[4019:60b] PythonHome is: /var/mobile/Applications/F50B18E6-11AC-48EC-91E8-F52068D66444/kivycatalog.app
2014-03-25 13:42:59.482 kivycatalog[4019:60b] Initializing python
2014-03-25 13:42:59.757 kivycatalog[4019:60b] Running main.pyo: /var/mobile/Applications/F50B18E6-11AC-48EC-91E8-F52068D66444/kivycatalog.app/YourApp/main.pyo
[INFO              ] Kivy v1.8.0
[INFO              ] [Factory     ] 157 symbols loaded
[DEBUG             ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
[DEBUG             ] [Cache       ] register <kv.image> with limit=None, timeout=60s
[DEBUG             ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
[DEBUG             ] [Image       ] option <dds> ignored by config
[DEBUG             ] [Image       ] option <pygame> ignored by config
[DEBUG             ] [Image       ] option <pil> ignored by config
[DEBUG             ] [Image       ] option <gif> ignored by config
[INFO              ] [Image       ] Providers: img_imageio, img_tex (img_dds, img_pygame, img_pil, img_gif ignored)
[DEBUG             ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
[DEBUG             ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
 Traceback (most recent call last):
   File "/Users/sasha/Sites/kivy/src/kivy-ios/app-kivycatalog/YourApp/main.py", line 14, in <module>
   File "/usr/local/lib/python2.7/site-packages/kivy/uix/codeinput.py", line 37, in <module>
 ImportError: No module named pygments
2014-03-25 13:43:01.165 kivycatalog[4019:60b] Application quit abnormally!
2014-03-25 13:43:01.212 kivycatalog[4019:60b] Leaving
```

**Comment by tito** [comment]
Yes, pygments is a dependency not included by default, you need to add it when building the toolchain.

**Comment by LucaInfante** [comment]
Excuse I'm a novice and I don't know how to include "pygments" in building of toolchain.

**Comment by ryandoherty** [comment]
For people googling this issue, here's what I did to 'fix' the problem (not sure if this is the best way, but it works)

For pygments, I had to manually copy the pygments directory from the Kivy.app to my app's source directory like so:

`cp -R /Applications/Kivy.app/Contents/Resources/venv/lib/python2.7/site-packages/pygments .`
