### ISSUE TITLE
zbarlight throwing error during build

### ISSUE THREAD

**Issue by subhashsharma** [kivy/kivy-ios#922]
**Versions**

* Python : Python 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
* MacOS version : 14.4.1 (23E224)
* XCode Version : Version 15.3 (15E204a)
* Cython version : 0.29.36

**Describe the bug**
zbarlight build fails

**To Reproduce**
Clone recent version of kivy-ios from GitHub
Run using:  python3 ./kivy-ios/toolchain.py build zbarlight

**Expected behavior**
// REPLACE ME: A clear and concise description of what you expected to happen.
The build should complete and give us a zbarlight library 
**Logs**
```
  STDOUT:
Biglink will create library "/Users/subhash/Development/personal/ios/Kivy/mappo/ios/build/zbarlight/iphonesimulator-arm64/zbarlight-3.0/zbarlight.a" from dirs:
/Users/subhash/Development/personal/ios/Kivy/mappo/ios/build/zbarlight/iphonesimulator-arm64/zbarlight-3.0/build/lib.macosx-14.4-arm64-cpython-311/zbarlight
Traceback (most recent call last):
  File "/Users/subhash/Development/personal/ios/Kivy/mappo/ios/kivy-ios/kivy_ios/tools/biglink", line 77, in <module>
    main()
  File "/Users/subhash/Development/personal/ios/Kivy/mappo/ios/kivy-ios/kivy_ios/tools/biglink", line 67, in main
    assert not lib_names, (
AssertionError: We should have consumed all lib_names but {'_zbarlight'} remains
```

**Comment by LauraneLN** [comment]
Hello,

I have the same issue since I update my MacOS and Xcode

**Comment by cederom** [comment]
The same here ;-)

**Comment by cederom** [comment]
What I noticed so far about recent Apple stuff:
* iPhone Simulator is buggy while app may work fine on a real phone.
* Buildozer automates more stuff than manual toolchain run (i.e. provides all recipes from buildozer.spec).

Can you try running the Buildozer in order to get xcode project created and then open build that project with XCode? That path works best for me :-)
