### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_PIL__imaging) in Xcode 15.

### ISSUE THREAD

**Issue by Kryptonh** [kivy/kivy-ios#934]
**Versions**

* Python : 3.10.10
* MacOS version : 14.5
* XCode Version : 15.4
* Cython version : 3.0.0 

**Describe the bug**

I'm trying to use pillow in my project and I get the following error: ImportError: dynamic module does not define module export function (PyInit__imaging)

(I understand that this issue has been closed, but I have new xcode)

**To Reproduce**
```
git clone https://github.com/kivy/kivy-ios.git
cd kivy-ios/
python3 -m venv venv
. venv/bin/activate
pip install -e .
python3.10 toolchain.py build kivy python3
python3.10 toolchain.py pip3 install pillow
```

**Expected behavior**
```
Trying to import Pillow in my project
```

**Logs**
```
File "/Users/kryptonh/kivy-ios/checkxcode-ios/YourApp/main.py", line 9, in <module>
   File "/private/var/containers/Bundle/Application/A526DF69-4967-4216-B81B-0368EF9B5044/checkxcode.app/lib/python3.11/site-packages/PIL/Image.py", line 114, in <module>
     from . import _imaging as core
   File "<string>", line 49, in load_module
   File "/Users/kryptonh/kivy-ios/dist/root/python3/lib/python3.11/imp.py", line 343, in load_dynamic
 ImportError: dynamic module does not define module export function (PyInit__imaging)
```

**Screenshots**

**Additional context**
```
I noticed that I don't have libpillow.a in General -> Frameworks, Libraries and Embedded Content (not available for some reason)

Moreover, when I do an update to python3.10toolchain.py [project_path], I get a series of errors:

Undefined symbol: _FT_Bitmap_Convert

Undefined symbol: _FT_Bitmap_Done

Undefined symbol: _FT_Bitmap_New

Undefined symbol: _FT_Done_Face

Undefined symbol: _FT_Done_Glyph

Undefined symbol: _FT_Get_Char_Index

Undefined symbol: _FT_Get_Glyph

Undefined symbol: _FT_Get_Kerning

Undefined symbol: _FT_Glyph_Get_CBox

Undefined symbol: _FT_Glyph_Stroke

Undefined symbol: _FT_Glyph_To_Bitmap

Undefined symbol: _FT_Init_FreeType

Undefined symbol: _FT_Library_Version

Undefined symbol: _FT_Load_Glyph

Undefined symbol: _FT_New_Face

Undefined symbol: _FT_New_Memory_Face

Undefined symbol: _FT_Select_Charmap

Undefined symbol: _FT_Set_Pixel_Sizes

Undefined symbol: _FT_Stroker_Done

Undefined symbol: _FT_Stroker_New

Undefined symbol: _FT_Stroker_Set

Undefined symbol: _jpeg_CreateCompress

Undefined symbol: _jpeg_CreateDecompress

Undefined symbol: _jpeg_add_quant_table

Undefined symbol: _jpeg_destroy_compress

Undefined symbol: _jpeg_destroy_decompress

Undefined symbol: _jpeg_finish_compress

Undefined symbol: _jpeg_finish_decompress

Undefined symbol: _jpeg_read_header

Undefined symbol: _jpeg_read_scanlines

Undefined symbol: _jpeg_resync_to_restart

Undefined symbol: _jpeg_set_defaults

Undefined symbol: _jpeg_set_quality

Undefined symbol: _jpeg_simple_progression

Undefined symbol: _jpeg_start_compress

Undefined symbol: _jpeg_start_decompress

Undefined symbol: _jpeg_std_error

Undefined symbol: _jpeg_suppress_tables

Undefined symbol: _jpeg_write_marker

Undefined symbol: _jpeg_write_scanlines

Linker command failed with exit code 1 (use -v to see invocation)

/Users/kryptonh/kivy-ios/checkxcode-ios/main.m
/Users/kryptonh/kivy-ios/checkxcode-ios/main.m:67:5 'PySys_SetArgv' is deprecated

/Users/kryptonh/kivy-ios/checkxcode-ios/main.m:70:5 'PyEval_InitThreads' is deprecated
 ```

**Comment by Kryptonh** [comment]
removed libpillow.xcframework from **Link binary with libraries** in **Build Phases** in Xcode, the project starts normally, but I get the expected error: ModuleNotFoundError: No module named 'PIL', I guess the problem is in libpillow

**Comment by Kryptonh** [comment]
Okay, after long researching I removed 2/5 files with error from libpillow.a and fixed error with importing Pillow framework in Xcode,
but I still get the error:

```
Traceback (most recent call last):
   File "<string>", line 45, in load_module
   File "/Users/kryptonh/kivy-ios/dist/root/python3/lib/python3.11/imp.py", line 343, in load_dynamic
   File "<frozen importlib._bootstrap>", line 721, in _load
   File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 573, in module_from_spec
   File "<frozen importlib._bootstrap_external>", line 1233, in create_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
 ImportError: dynamic module does not define module export function (PyInit_PIL__imaging)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/kryptonh/kivy-ios/wbstr-ios/YourApp/main.py", line 79, in <module>
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/kivy/app.py", line 956, in run
     runTouchApp()
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/kivy/base.py", line 379, in idle
     Clock.tick()
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/kivy/clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/kivy/clock.py", line 776, in post_idle
     self._process_events()
   File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "/Users/kryptonh/kivy-ios/wbstr-ios/YourApp/main.py", line 63, in updt
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/imageio/v2.py", line 396, in imwrite
     with imopen(uri, "wi", **imopen_args) as file:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/imageio/core/imopen.py", line 196, in imopen
     plugin_instance = candidate_plugin(request, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/imageio/config/plugins.py", line 107, in partial_legacy_plugin
     return LegacyPlugin(request, legacy_plugin)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/imageio/core/legacy_plugin_wrapper.py", line 85, in __init__
     if not self._format.can_write(request):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/imageio/core/format.py", line 249, in can_write
     return self._can_write(request)
            ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/imageio/plugins/pillow_legacy.py", line 269, in _can_write
     Image = self._init_pillow()
             ^^^^^^^^^^^^^^^^^^^
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/imageio/plugins/pillow_legacy.py", line 247, in _init_pillow
     from PIL import Image
   File "/private/var/containers/Bundle/Application/C41062EE-7FC2-4C5C-8BBF-58602A29653A/wbstr.app/lib/python3.11/site-packages/PIL/Image.py", line 109, in <module>
     from . import _imaging as core
   File "<string>", line 49, in load_module
   File "/Users/kryptonh/kivy-ios/dist/root/python3/lib/python3.11/imp.py", line 343, in load_dynamic
 ImportError: dynamic module does not define module export function (PyInit__imaging)
```

Maybe Pillow 8.2.0 (standard recipe version for kivy-ios) too old for Xcode 15....?

**Comment by 320V** [comment]
Kind of same error here:
**Versions**
* Python :  3.11.6
* MacOS version :  macOS Sonoma 14.7.1
* XCode Version  16.1 (16B40)
* Cython version :  0.29.36

**Describe the bug**
Getting this error after successfully build and run from Xcode on simulator. (Xcode Logs). Using pillow in main.py file. 

**To Reproduce**
python3.9 -m venv venv
. venv/bin/activate
toolchain build python3 kivy==2.3.0
python3 -m pip install git+https://github.com/kivy/kivy-ios
toolchain create synapp synapp
open synapp-ios/synapp.xcodeproj                                         
(In Xcode) > Build Phases > Run Script: [rsync -av --delete "/Users/mertmehmetaraz/synapp/synapp"/ "$PROJECT_DIR"/YourApp
] *Checked* For install builds only* 
Coppied main.py into: .../synapp-ios/YourApp folder

**Expected behavior**
Application should run without any Pillow dynamic libraries errors.

**Logs**
```
Available orientation: KIVY_ORIENTATION=LandscapeLeft LandscapeRight Portrait PortraitUpsideDown
Initializing python
<string>:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
Running main.py: /Users/mertmehmetaraz/Library/Developer/CoreSimulator/Devices/A83CA3ED-8452-4822-86F9-04505270DA43/data/Containers/Bundle/Application/727F98C8-73DD-47AF-8C44-5522EF788641/synapp.app/YourApp/main.pyc
python: 3.11.6 (main, Nov 14 2024, 14:00:17) [Clang 16.0.0 (clang-1600.0.26.4)]
[WARNING] [Config      ] Older configuration version detected (0 instead of 27)
[WARNING] [Config      ] Upgrading configuration in progress.
[DEBUG  ] [Config      ] Upgrading from 0 to 1
[INFO   ] [Logger      ] Record log in /Users/mertmehmetaraz/Library/Developer/CoreSimulator/Devices/A83CA3ED-8452-4822-86F9-04505270DA43/data/Containers/Data/Application/52AAB17F-F97F-4F6A-A2CA-306C611BABF9/Documents/.kivy/logs/kivy_24-11-14_0.txt
[INFO   ] [Kivy        ] v2.3.0
[INFO   ] [Kivy        ] Installed at "/Users/mertmehmetaraz/Library/Developer/CoreSimulator/Devices/A83CA3ED-8452-4822-86F9-04505270DA43/data/Containers/Bundle/Application/727F98C8-73DD-47AF-8C44-5522EF788641/synapp.app/lib/python3.11/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.11.6 (main, Nov 14 2024, 14:00:17) [Clang 16.0.0 (clang-1600.0.26.4)]
[INFO   ] [Python      ] Interpreter at "/Users/mertmehmetaraz/Library/Developer/CoreSimulator/Devices/A83CA3ED-8452-4822-86F9-04505270DA43/data/Containers/Bundle/Application/727F98C8-73DD-47AF-8C44-5522EF788641/synapp.app/synapp"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 195 symbols loaded
[INFO   ] [Image       ] Providers: img_imageio, img_tex, img_sdl2 (img_dds, img_ffpyplayer, img_pil ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
You need UIApplicationSupportsIndirectInputEvents in your Info.plist for mouse support
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0 APPLE-21.0.27'>
[INFO   ] [GL          ] OpenGL vendor <b'Apple Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Apple Software Renderer'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Video       ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
Pillow: 10.0.0
 Traceback (most recent call last):
   File "<string>", line 45, in load_module
   File "/Users/mertmehmetaraz/synapp/dist/root/python3/lib/python3.11/imp.py", line 343, in load_dynamic
   File "<frozen importlib._bootstrap>", line 721, in _load
   File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 573, in module_from_spec
   File "<frozen importlib._bootstrap_external>", line 1233, in create_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
 ImportError: dynamic module does not define module export function (PyInit_PIL__imaging)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/mertmehmetaraz/synapp/synapp-ios/YourApp/main.py", line 18, in <module>
   File "/Users/mertmehmetaraz/Library/Developer/CoreSimulator/Devices/A83CA3ED-8452-4822-86F9-04505270DA43/data/Containers/Bundle/Application/727F98C8-73DD-47AF-8C44-5522EF788641/synapp.app/lib/python3.11/site-packages/PIL/Image.py", line 82, in <module>
     from . import _imaging as core
   File "<string>", line 49, in load_module
   File "/Users/mertmehmetaraz/synapp/dist/root/python3/lib/python3.11/imp.py", line 343, in load_dynamic
 ImportError: dynamic module does not define module export function (PyInit__imaging)
Application quit abnormally!
Leaving```

**Additional context**
Tried Pillow library with these versions: [10.0.0 & 10.4.0]. Also these versions working well on Android.
